- sql-odbc/scripts/build_aws-sdk-cpp.ps1
Changed aws sdk cpp version to the last success version `1.8.186`. This PR is a temporary solution to fix the build errors, but we probably need to dive deeper to adapt our future versions to the new releases of aws sdk. 
https://github.com/opendistro-for-elasticsearch/sql/pull/1092
~~- [ ] New functionality has been documented.~~
~~- [ ] New functionality has javadoc added~~
~~- [ ] New functionality has user manual doc added~~
> Fix ODBC build failures

- .github/workflows/sql-workbench-release-workflow.yml
- .github/workflows/sql-workbench-test-and-build-workflow.yml
- workbench/.cypress/integration/ui.spec.js
- workbench/.cypress/utils/constants.js
- workbench/opensearch_dashboards.json
- workbench/package.json
- workbench/public/plugin.ts
- workbench/server/services/utils/constants.ts
- change workbench version to 1.0.0
- change sql api to _opensearch
- fixed cypress tests (download format a bit different)
- move to `OpenSearch Plugins` from `OpenSearch`
> Change workbench version to 1.0.0, change api to _opensearch

- .github/workflows/sql-test-and-build-workflow.yml
- build.gradle
- integ-test/build.gradle
- sql-jdbc/build.gradle
1. Build against OpenSearch 1.0.0-alpha2
2. Change SQL/PPL and JDBC artifact name to alpha2 (ODBC is not straightforward and will rename manually for now) 
N/A
> Build SQL/PPL against OpenSearch 1.0.0-alpha2

- sql-odbc/src/odfesqlodbc/setup.c
- sql-odbc/src/odfesqlodbc/win_unicode.c
Remove debug logging due to security risk. Copy from the following ODFE PRs:
1. https://github.com/opendistro-for-elasticsearch/sql/pull/1099
2. https://github.com/opendistro-for-elasticsearch/sql/pull/1100
N/A
> Remove debug logging in ODBC driver

- workbench/public/components/Main/main.tsx
Signed-off-by: Chloe Zhang chloezh1102@gmail.com
Here was a rule to mark the result as a proper output from http response rather than error output, which is applied when the http response has data body even though the status is not "ok" (response ok is false). This condition was added specially to fix the csv downloading issue, details: https://github.com/opendistro-for-elasticsearch/sql/issues/1023
But the temporary fix gave a much wider condition than necessary to mark a result as a "good result". This results in some improper behaviors, it does not show any error message in the output windows now when it should. 
This fix is to give a restriction to the last fix of the csv downloading issue. However this fix is only a temporary solution to unblock the release. We should dive deep for …
> Fix issue of workbench not outputting errors

- sql-cli/setup.py
Upgrade SQL CLI dependency Pygments to `>=2.7.4`
CVE-2021-20270
> Upgrade dependencies to address high severity CVE-2021-20270

- legacy/src/main/java/org/opensearch/sql/legacy/esdomain/LocalClusterState.java
- legacy/src/test/java/org/opensearch/sql/legacy/util/CheckScriptContents.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
Fixed index expression resolution to include backing indices of a data stream. This will make querying a data stream consistent with querying an index alias.
- Closes https://github.com/opensearch-project/sql/issues/55
Signed-off-by: Ketan Verma <ketan9495@gmail.com>
> Support querying a data stream

- workbench/CODE_OF_CONDUCT.md
- workbench/CONTRIBUTING.md
- workbench/README.md
- workbench/common/index.ts
- workbench/public/components/Main/__snapshots__/main.test.tsx.snap
- workbench/public/components/Main/main.tsx
- workbench/server/plugin.ts
Signed-off-by: David Cui <davidcui@amazon.com>
* Update documentation links to OpenSearch
* Rename remaining occurrences of `opendistro`
> Update workbench documentation links, complete renaming

- docs/category.json
- docs/user/admin/settings.rst
- integ-test/src/test/java/org/opensearch/sql/legacy/DeleteIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/PluginIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlAction.java
- legacy/src/main/java/org/opensearch/sql/legacy/plugin/SearchDao.java
- legacy/src/main/java/org/opensearch/sql/legacy/plugin/SqlSettings.java
- legacy/src/main/java/org/opensearch/sql/legacy/query/OpenSearchActionFactory.java
- legacy/src/test/java/org/opensearch/sql/legacy/unittest/JSONRequestTest.java
- legacy/src/test/java/org/opensearch/sql/legacy/unittest/QueryFunctionsTest.java
- legacy/src/test/java/org/opensearch/sql/legacy/unittest/WhereWithBoolConditionTest.java
- legacy/src/test/java/org/opensearch/sql/legacy/util/CheckScriptContents.java
- legacy/src/test/java/org/opensearch/sql/legacy/util/SqlExplainUtils.java
1. By default, the DELETE clause is disabled in SQL engine.
2. Add the opensearch.sql.delete.enabled setting which could be used to enable the DELETE clause.
3. Update the docs, https://github.com/penghuo/os-sql/blob/pr-issue59/docs/user/admin/settings.rst#opensearch-sql-delete-enabled
#59 
> Disable DELETE clause by defaut and add opensearch.sql.delete.enabled setting

- .github/workflows/sql-workbench-release-workflow.yml
- .github/workflows/sql-workbench-test-and-build-workflow.yml
- sql-cli/src/opensearch_sql_cli/__init__.py
- workbench/opensearch_dashboards.json
- workbench/package.json
Signed-off-by: David Cui <davidcui@amazon.com>
Renames remaining references to beta1 in sql-cli and workbench
https://github.com/opensearch-project/sql/issues/86
> Rename remaining beta1 references in sql-cli/workbench

- .github/workflows/sql-test-and-build-workflow.yml
As OpenSearch 1.0 ready, move SQL/PPL build from 1.x to 1.0 branch.
https://github.com/opensearch-project/sql/issues/86
> Build SQL/PPL against OpenSearch 1.0 branch

- integ-test/src/test/java/org/opensearch/sql/ppl/LegacyAPICompatibilityIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/LegacyAPICompatibilityIT.java
- plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java
Signed-off-by: Chloe Zhang <chloezh1102@gmail.com>
Example 1:
```
PUT _opendistro/_sql/settings
{
"transient" : {
"opendistro.sql.enabled" : "false"
}
}
```
Response:
```
#! Deprecation: [opendistro.ppl.enabled] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
#! Deprecation: [opendistro.sql.enabled] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
#! Deprecation: [PUT /_opendistro/_sql/settings] is deprecated! Use [PUT /_plugins/_query/settings] instead.
{
"acknowledged" : true,
"persistent" : { },
"transient" : {
"opendistro" : {
"sql" : {
"enabled" : "false"
}
}
}
}
```
Example 2:
```
PUT …
```
> Bug Fix: Enable legacy settings in new setting action

- .github/workflows/sql-workbench-release-workflow.yml
- .github/workflows/sql-workbench-test-and-build-workflow.yml
- release-notes/opensearch-sql.release-notes-1.0.0.0-rc1.md
Bump OpenSearch Dashboards version to 1.0 in Workbench workflows
> Bump OpenSearch Dashboards version to 1.0 in Workbench

- doctest/build.gradle
1. Rename gradle tasks in the manner of Opensearch
2. Fix testDistribution flag to pass local test.
#118 
> Rename doctest gradle tasks in the manner of Opensearch

- workbench/package.json
- workbench/yarn.lock
Signed-off-by: David Cui <davidcui@amazon.com>
Add testing-library/user-event to package.json to pass the CI after its removal upstream
> Fix CI for Workbench

- common/src/main/java/org/opensearch/sql/common/setting/LegacySettings.java
- docs/user/admin/settings.rst
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/LegacyOpenDistroSettings.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/setting/OpenSearchSettingsTest.java
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
1. Address #75, deprecated opendistro.sql.cursor.enabled and opendistro.sql.cursor.fetch_size
2. Address #70, deprecated opendistro.sql.engine.new.enabled
3. Address #76, deprecated opensearch.sql.query.analysis.*
4. Address #77, deprecated opensearch.sql.query.response.format
Before rolling upgrade, put the deprecated setting.
```
curl -X PUT "localhost:9200/_opendistro/_sql/settings" -H 'Content-Type: application/json' -d'
{
"persistent" : {
"opendistro": {
"sql": {
"cursor": {
"enabled" : true,
"keep_alive": "10m"
}
}
}
},
"transient" : {
"opendistro.sql.query.analysis.enabled" : false
}
}'
```
After the rolling upgrade from ODFE 1.13.2 to OpenSearch 1.0, Then update the deprecated setting. The warning will returned.
```
➜  upgrade-test curl -i -X PUT …
```
> Deprecated legacy settings instead of removing

- .codecov.yml
- .github/workflows/sql-test-and-build-workflow.yml
Adds Codecov back to SQL repo. 
> Add Codecov to SQL 

- .github/workflows/draft-release-notes-workflow.yml
- .github/workflows/sql-test-and-build-workflow.yml
- .github/workflows/sql-workbench-release-workflow.yml
- .github/workflows/sql-workbench-test-and-build-workflow.yml
- build.gradle
- integ-test/build.gradle
- sql-cli/src/opensearch_sql_cli/__init__.py
- sql-jdbc/build.gradle
- workbench/opensearch_dashboards.json
- workbench/package.json
Bump OpenSearch to version 1.0.0 and rename all artifacts by removing `-rc1`, including SQL/PPL, JDBC, ODBC, SQL CLI, and Query Workbench.
https://github.com/opensearch-project/sql/issues/144
> Build against OpenSearch 1.0.0 and bump artifact version to 1.0.0.0

- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Change ANTLR grammar to make table filter required. After fix, this is consistent with what is supported and documented.
https://github.com/opensearch-project/sql/issues/149
> Fix NPE for SHOW statement without filter

- release-notes/opensearch-sql.release-notes-1.0.0.0.md
Add release notes for OpenSearch GA which have consolidated the both release note RC1 + GA.
https://github.com/opensearch-project/sql/issues/152
> Add release notes for OpenSearch GA

- sql-odbc/src/sqlodbc/opensearch_communication.cpp
- sql-odbc/src/sqlodbc/opensearch_communication.h
Fixed aws init and shutdown behaviour. The current code can cause segmentation faults in multithreaded environments
https://github.com/opensearch-project/sql/issues/164
> Fix for SQL-ODBC AWS Init and Shutdown Behaviour

- build.gradle
Signed-off-by: dblock <dblock@amazon.com>
Allows one to run `./gradlew build --no-daemon -Dopensearch.version=1.0.0-SNAPSHOT -Dbuild.snapshot=true` to produce a `-SNAPSHOT` artifact that correctly depends on the `-SNAPSHOT` build of OpenSearch.
Closes #177 
> Use externally-defined OpenSearch version when specified.

- .github/workflows/sql-test-and-build-workflow.yml
- build.gradle
Signed-off-by: dblock <dblock@amazon.com>
Use OpenSearch 1.1 and build snapshot by default in CI.
> Use OpenSearch 1.1 and build snapshot by default in CI.

- workbench/.cypress/integration/ui.spec.js
- workbench/.cypress/support/commands.js
- workbench/.cypress/support/constants.js
- workbench/.cypress/support/index.js
- workbench/.cypress/utils/constants.js
- workbench/cypress.json
- Auto dump cypress test data (`accounts` and `employee_nested` to test sql/ppl query correctness) for workbench
- Add security support for cypress
> Workbench: auto dump cypress test data, support security

- integtest.sh
#199 puts the dumping test data logic into cypress, remove the curl commands in integtest.sh as the functionality is duplicated
> Workbench: remove curl commands in integtest.sh

- docs/dev/Pagination.md
- workbench/.cypress/support/commands.js
- workbench/.cypress/tsconfig.json
the import path for auth info was incorrect
add tsconfig.json for cypress
> Fix import path for cypress constant

- .github/workflows/draft-release-notes-workflow.yml
- .github/workflows/sql-odbc-release-workflow.yml
- .github/workflows/sql-odbc-rename-and-release-workflow.yml
- .github/workflows/sql-workbench-test-and-build-workflow.yml
- release-notes/opensearch-sql.release-notes-1.1.0.0.md
- sql-cli/src/opensearch_sql_cli/__init__.py
- sql-jdbc/build.gradle
- sql-odbc/src/CMakeLists.txt
- sql-odbc/src/TableauConnector/opensearch_sql_odbc/manifest.xml
- sql-odbc/src/TableauConnector/opensearch_sql_odbc_dev/manifest.xml
- workbench/opensearch_dashboards.json
- workbench/package.json
Bump versions from `1.0.0.0` to `1.1.0.0` for Opensearch 1.1 release
> Bump version to 1.1 for Opensearch 1.1.0.0 release 

- .github/workflows/link-checker.yml
- .github/workflows/sql-cli-release-workflow.yml
- .github/workflows/sql-cli-test-and-build-workflow.yml
- .github/workflows/sql-jdbc-push-jdbc-maven.yml
- .github/workflows/sql-release-workflow.yml
- .github/workflows/sql-test-and-build-workflow.yml
- README.md
- docs/dev/NewSQLEngine.md
- release-notes/opensearch-sql.release-notes-1.1.0.0.md
- sql-cli/CONTRIBUTING.md
- sql-cli/README.md
- sql-jdbc/CONTRIBUTING.md
- sql-odbc/CONTRIBUTING.md
- workbench/README.md
- workbench/release-notes/sql-workbench.release-notes-1.7.0.0.md
- Core has `1.1` branch cut and bumped `1.x` minor version to `1.2`, use opensearch ref to 1.1 in CI
- Ignore 999 status code in link checker for now, possibly caused by github rate limit. Pending fix from upstream `lycheeverse/lychee` issue 234.
- use ubuntu-latest instead of 16.04
> Bump opensearch ref to 1.1 in CI

- plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLQueryAction.java
Remove field member `pplRequest` and make it local to avoid state sharing between requests.
https://github.com/opensearch-project/sql/issues/196
> Fix PPL request concurrency handling issue

- core/src/main/java/org/opensearch/sql/data/model/ExprTimestampValue.java
- core/src/main/java/org/opensearch/sql/expression/operator/convert/TypeCastOperator.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LuceneQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/RangeQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/TermQuery.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
Signed-off-by: Chloe Zhang <chloezh1102@gmail.com>
By default the non literal expressions in a query are converted to scripts before put into the DSL queries to enable users to do calculations over columns in the query engine. But The scripts usually cause low efficiency as a trade-off. We would prefer pushing as much as possible of the query out of the script and directly into fields if possible. 
This PR is to optimize the following scenario:
For filters that contains castings, for example:
```
SELECT FlightNum FROM opensearch_dashboards_sample_data_flights WHERE timestamp > '2021-01-01 00:00:00' 
```
There is an implicit cast in WHERE clause, `timestamp > '2021-01-01 00:00:00' ` casts the string '2021-01-01 00:00:00' to timestamp type implicitly before translate the entire filter …
> Optimized type converting in DSL filters

- opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/ObjectContent.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
Signed-off-by: Chloe Zhang <chloezh1102@gmail.com>
```
POST _plugins/_sql
{
"query": "SELECT (CASE WHEN bool0 THEN TRUE WHEN NOT bool0 THEN FALSE ELSE NULL END) AS a FROM boolean_test GROUP BY a"
}
{
"schema": [
{
"name": "(CASE WHEN bool0 THEN TRUE WHEN NOT bool0 THEN FALSE ELSE NULL END)",
"alias": "a",
"type": "boolean"
}
],
"datarows": [
[
null
],
[
false
],
[
true
]
],
"total": 3,
"size": 3,
"status": 200
}
```
#276 
> Fixed result parsing error for boolean type

- core/src/main/java/org/opensearch/sql/expression/text/TextFunction.java
- core/src/test/java/org/opensearch/sql/expression/text/TextFunctionTest.java
- integ-test/src/test/resources/correctness/expressions/text_functions.txt
Signed-off-by: Chloe Zhang <chloezh1102@gmail.com>
- Fixed string index out of bound issue in left and right functions
- Added unit test cases
- Added comparison test cases
#266 
> Fixed StringIndexOutOfBoundsException issue of left and right text functions

- release-notes/opensearch-sql.release-notes-1.2.0.0.md
> [1.2] Update release notes for 1.2 release (#289)

- doctest/test_docs.py
- sql-cli/setup.py
- sql-cli/src/opensearch_sql_cli/opensearch_connection.py
- sql-cli/src/opensearch_sql_cli/opensearchsql_cli.py
- sql-cli/tests/test_formatter.py
- sql-cli/tests/test_opensearch_connection.py
- sql-cli/tests/test_opensearchsql_cli.py
- sql-cli/tests/utils.py
- replace elasticsearch python lib with opensearch-py in **sql-cli** and **doctest**
- reformat code
- 
#307 
> use opensearch-py client

- workbench/public/components/Main/main.tsx
- workbench/public/utils/utils.ts
- escape query string
- handle line breaks for ppl
#194 
#217 
> Fix query string handling for workbench

- .github/workflows/link-checker.yml
- .github/workflows/sql-test-and-build-workflow.yml
- .github/workflows/sql-workbench-test-and-build-workflow.yml
Uploading SQL workbench test coverage wasn't part of the build CI. 
1. Added flags for sql engine and workbench to get separate code cov results.
2. Updated Link Checker
> Added codecov for workbench

- integ-test/build.gradle
add integTestRemote task for sql
```bash
./gradlew integTestRemote -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster"
```
#281 
> Add integTestRemote for sql

- .github/workflows/sql-test-and-build-workflow.yml
- build.gradle
- common/build.gradle
- integ-test/build.gradle
- ppl/build.gradle
- release-notes/opensearch-sql.release-notes-1.2.2.0.md
backport #338 
https://github.com/opensearch-project/opensearch-build/issues/1333
> [1.2] Bump log4j to 2.16 and plugin to 1.2.2

- .github/workflows/sql-test-and-build-workflow.yml
- build.gradle
- common/build.gradle
- integ-test/build.gradle
- ppl/build.gradle
- release-notes/opensearch-sql.release-notes-1.2.2.0.md
Bump log4j to 2.16 and plugin to 1.2.2
> Bump log4j to 2.16 and plugin to 1.2.2

- common/build.gradle
- integ-test/build.gradle
- ppl/build.gradle
- release-notes/opensearch-sql.release-notes-1.2.3.0.md
Bumped up log4j to 2.17 
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105
https://github.com/opensearch-project/opensearch-build/issues/1365
> Bump log4j to 2.17

- README.md
Update readme badges
1. added untriaged and nolabel badges
> added untriaged and nolabel badges

- common/build.gradle
- integ-test/build.gradle
- ppl/build.gradle
Signed-off-by: dblock <dblock@amazon.com>
Upgrade to log4j 2.17.1.
> Upgrade to log4j 2.17.1.

- core/src/main/java/org/opensearch/sql/data/model/ExprDatetimeValue.java
- core/src/main/java/org/opensearch/sql/data/model/ExprStringValue.java
- core/src/main/java/org/opensearch/sql/data/model/ExprTimeValue.java
- core/src/main/java/org/opensearch/sql/data/model/ExprTimestampValue.java
- core/src/test/java/org/opensearch/sql/data/model/DateTimeValueTest.java
- docs/user/general/datatypes.rst
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/system/OpenSearchDescribeIndexRequest.java
- use `ExprCoreType.TIMESTAMP` for `date_nanos` OpenSearch field type
- increase precision of `ExprTimeValue` and `ExprDatetimeValue` to 9 digits
- update unit tests
NOTE: if a `date_nanos` field is constructed using a number instead of ISO string, the number will be parsed as milliseconds. This is a limitation from upstream, for details see elasticsearch issue 43917
closes #358 
> Support date_nanos OpenSearch field type

- integ-test/build.gradle
- protocol/build.gradle
- workbench/package.json
- workbench/yarn.lock
Bump gson to 2.8.9 in sql
Bump json-schema to 0.4.0 in workbench
> Bump gson and json-schema

- integ-test/build.gradle
- protocol/build.gradle
- workbench/package.json
- workbench/yarn.lock
> [1.2] Bump gson and json-schema

- sql-cli/README.md
- sql-cli/setup.py
- sql-cli/src/opensearch_sql_cli/__init__.py
- use `1.0.0` for initial launch 
- fixed an issue by pinning the version number of `pygment`
- Update README with new gif
#384 
#374 
#243 
> [SQL-CLI] set version number to 1.0.0

- .github/workflows/link-checker.yml
- .github/workflows/sql-cli-test-and-build-workflow.yml
- sql-cli/README.md
- sql-cli/development_guide.md
- sql-cli/setup.py
Backport PR #388 to `sql-cli-1.0` branch.
- rename package to `opensearch-sqlcli`
> [sql-cli-1.0] Rename `opensearch-sql-cli` to `opensearch-sqlcli` to unblock release

- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
Parse none type field as null instead of throw exception.
```
POST /empty-test-00002/_doc/
{ "l1": 1, "l2":{"l2": []}}
POST {{baseUrl}}/_plugins/_sql
{
"query": "select * from empty-test-00001"
}
{
"schema": [
{
"name": "l1",
"type": "long"
},
{
"name": "l2",
"type": "object"
}
],
"datarows": [
[
1,
{}
]
],
"total": 1,
"size": 1,
"status": 200
}
```
#398
> Parse none type field as null instead of throw exception

- sql-odbc/docs/user/tableau_support.md
ODBC ignores the default profile (#328), so adding instructions on which profile name to use.
This can be reverted after https://github.com/opensearch-project/sql/issues/328 is resolved
> Add how to setup aws credentials for ODBC Tableau

- build.gradle
- common/build.gradle
- integ-test/build.gradle
- legacy/build.gradle
- opensearch/build.gradle
- plugin/build.gradle
- ppl/build.gradle
- protocol/build.gradle
- sql-jdbc/build.gradle
Bumping up version for Jackson libraries to 2.12.6
> Jackson-databind bump to 2.12.6

- protocol/src/main/java/org/opensearch/sql/protocol/response/format/ErrorFormatter.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/ErrorFormatterTest.java
Disable html escape when formatting response.
Issue:
```
curl --request POST \
--url http://localhost:9200/_plugins/_ppl/_explain \
--header 'content-type: application/json' \
--header 'user-agent: vscode-restclient' \
--data '{"query": "source=test | fields long"}'
{
"root": {
"name": "ProjectOperator",
"description": {
"fields": "[long]"
},
"children": [
{
"name": "OpenSearchIndexScan",
"description": {
"request": "OpenSearchQueryRequest(indexName\u003dtest, sourceBuilder\u003d{\"from\":0,\"size\":200,\"timeout\":\"1m\",\"_source\":{\"includes\":[\"long\"],\"excludes\":[]}}, searchDone\u003dfalse)"
},
"children": []
}
]
}
}
```
Expected
```
{
"root": {
"name": "ProjectOperator",
"description": {
"fields": "[long]"
},
"children": [
{
"name": …
```
> Bug Fix, disable html escape when formatting response

- core/src/main/java/org/opensearch/sql/ast/tree/Relation.java
- core/src/test/java/org/opensearch/sql/ast/tree/RelationTest.java
- docs/user/general/identifiers.rst
- docs/user/ppl/general/identifiers.rst
- doctest/test_data/account2.json
- doctest/test_docs.py
- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchClient.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchRestClient.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequest.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequest.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/system/OpenSearchDescribeIndexRequest.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexScan.java
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
* [PPL doc](https://github.com/penghuo/os-sql/blob/issue-396-pr/docs/user/ppl/general/identifiers.rst#multiple-indices)
* [SQL doc](https://github.com/penghuo/os-sql/blob/issue-396-pr/docs/user/general/identifiers.rst#multiple-indices) 
#396 
> Support multiple indices in PPL and SQL

- .github/workflows/sql-odbc-main.yml
Revert to previous windows version for now to unblock PRs
> Revert to windows 2019 for odbc CI

- docs/user/ppl/cmd/stats.rst
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
1.Span expression should always be first in by list if exist
2.Update [doc](https://github.com/penghuo/os-sql/blob/fix-span/docs/user/ppl/cmd/stats.rst). 
> Span expression should always be first in by list if exist

- core/build.gradle
- plugin/build.gradle
- ppl/build.gradle
- sql/build.gradle
Version Bump
* springframework 5.2.5 -> 5.2.19
* jackson 2.10.5 -> 2.12.6
* #424
* #426
* #428
> Version Bump: springframework and jackson

- integ-test/build.gradle
- integ-test/src/test/java/org/opensearch/sql/correctness/runner/connection/JDBCConnection.java
- integ-test/src/test/java/org/opensearch/sql/correctness/runner/resultset/DBResult.java
- integ-test/src/test/java/org/opensearch/sql/correctness/runner/resultset/Row.java
- integ-test/src/test/java/org/opensearch/sql/correctness/tests/JDBCConnectionTest.java
- integ-test/src/test/java/org/opensearch/sql/sql/SQLCorrectnessIT.java
- integ-test/src/test/resources/correctness/expressions/cast.txt
- integ-test/src/test/resources/correctness/queries/window.txt
* Bump H2 from 1.x -> 2.x.
* Comments out test cases which are not supported in H2 2.x.
* #425
* #429 
* #430
> Version Bump: H2 1.x -> 2.x

- legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlAction.java
Treating ExpressionEvaluationException as client Error.
In the SQL plugin interface we currently treat ExpressionEvaluationException as back end error instead of client. This PR makes changes to include ExpressionEvaluationException to the list of client errors.
https://github.com/opensearch-project/sql/issues/423
> Treating ExpressionEvaluationException as client Error.

- docs/user/ppl/cmd/dedup.rst
- docs/user/ppl/cmd/eval.rst
- docs/user/ppl/cmd/head.rst
- docs/user/ppl/cmd/rare.rst
- docs/user/ppl/cmd/rename.rst
- docs/user/ppl/cmd/top.rst
Add limitation section in PPL docs for commands [dedup, eval, head, rare, rename, top] which are not rewritten to OpenSearch DSL and only executed on the coordination node.
N/A
> Add limitation section in PPL docs

- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFormatterUtil.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
- docs/user/dql/functions.rst
- docs/user/ppl/functions/datetime.rst
- integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilderTest.java
Supported ISO 8601 Format in Date Format. IN order to solve this we are allowing all the alphabet characters with a '%' character behind to be replicated into the output format as is.
Eg: 
%Y-%m-%dT%TZ   --- 2022-01-15T11:12:29Z
https://github.com/opensearch-project/sql/pull/434
> Support ISO 8601 Format in Date Format.

- sql-odbc/scripts/build_aws-sdk-cpp.ps1
- sql-odbc/scripts/build_libcurl-vcpkg.ps1
- sql-odbc/scripts/build_windows.ps1
- sql-odbc/src/installer/CMakeLists.txt
- sql-odbc/src/sqlodbc/opensearch_communication.cpp
Signed-off-by: Yury Fridlyand <yuryf@bitquilltech.com>
* Having this fix driver doesn't ignore user preferences for Hostname Verification parameter, and once it unset driver can establish SSL connection even if self-signed certificates are used
* AWS SDK compilation workflow changed to use `libcurl` instead of `winhttp` as a transport library for Windows builds
* `libcurl` shipped by vcpkg according to the [doc](https://curl.se/docs/install.html)
* `libcurl` built with `schannel` SSL backend which uses Windows Trust Certificate Store to validate certificates
* AWS SDK updated
* Fixed crash in driver caused by improper `libcurl` resource release (incorrect order)
https://github.com/opendistro-for-elasticsearch/sql/issues/686
https://github.com/opendistro-for-elasticsearch/sql/issues/783 …
> Fix certificate validation for ODBC driver

- release-notes/opensearch-sql.release-notes-1.3.0.0.md
Signed-off-by: Eugene Lee <eugenesk@amazon.com>
(cherry picked from commit fff24aaca82fba99b54fb14f9bc2a623d1a3e566)
Add 1.3.0 release notes
> [Backport 1.3] Add 1.3.0 release notes

- docs/category.json
- docs/user/ppl/cmd/ad.rst
- docs/user/ppl/cmd/kmeans.rst
- docs/user/ppl/index.rst
- doctest/build.gradle
- doctest/test_data/nyc_taxi.json
- doctest/test_docs.py
- doctest/test_mapping/nyc_taxi.json
Signed-off-by: jackieyanghan <jkhanjob@gmail.com>
- Add Kmeans and AD command documentation
- Add doc-test for AD command. Not going to add doc-test for Kmeans command because the query result (ClusterID) serves as a symbol of different classifications, the map relationship is not fixed. Therefore, it's difficult to predict the query result in doc-test. Will add integration tests in the next PR to cover this.
https://github.com/opensearch-project/sql/issues/470
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-ori …
> Add Kmeans and AD command documentation

- docs/user/ppl/cmd/ad.rst
- docs/user/ppl/cmd/kmeans.rst
Signed-off-by: Naarcha-AWS <naarcha@amazon.com>
This PR fixes small grammar mistakes in the AD and KMEANs docs.
> AD and Kmeans grammar edits

- core/build.gradle
- core/src/main/java/org/opensearch/sql/expression/text/TextFunction.java
- core/src/test/java/org/opensearch/sql/expression/aggregation/AggregationTest.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
- core/src/test/java/org/opensearch/sql/expression/text/TextFunctionTest.java
- docs/user/dql/functions.rst
- docs/user/ppl/functions/math.rst
- integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
Removed changes introduced to support JDK8.
https://github.com/opensearch-project/sql/issues/466
> Removed changes introduced to support JDK8

- .github/workflows/sql-jdbc-test-and-build-workflow.yml
- .github/workflows/sql-test-and-build-workflow.yml
- DEVELOPER_GUIDE.rst
- build.gradle
- core/build.gradle
- legacy/build.gradle
- opensearch/build.gradle
- ppl/build.gradle
- protocol/build.gradle
- sql/build.gradle
1. Add JDK 17 to CI/CD. To pass all SQL build, `lombok`, `mockito` and `jacoco` is upgraded to newer version accordingly. 
2. Add JDK 17 to SQL JDBC CI/CD as well.
3. Update developer guide doc to clarify the JDK version supported.
https://github.com/opensearch-project/sql/issues/467
> Add JDK 17 support

- integ-test/build.gradle
Replace checked-in ZIP with a dynamic dependency
#491 
> Replace checked-in ZIP with a dynamic dependency

- .github/workflows/draft-release-notes-workflow.yml
- .github/workflows/sql-test-and-build-workflow.yml
- build.gradle
- opensearch/build.gradle
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 1.3.1
https://github.com/opensearch-project/opensearch-build/issues/1805
> Bump version to 1.3.1

- integ-test/build.gradle
Java 17 bwc test failed, because of
`Could not find matching constructor for: java.io.File(String, File)`
https://github.com/opensearch-project/sql/runs/5725756591?check_suite_focus=true
None
> Fix bwc build issue with jdk17

- .github/workflows/sql-test-and-build-workflow.yml
- build.gradle
- bwctest.sh
- integ-test/build.gradle
- integ-test/src/test/java/org/opensearch/sql/legacy/JoinAliasWriterRuleIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/QueryIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SourceFieldIT.java
- legacy/build.gradle
- legacy/src/main/java/org/opensearch/sql/legacy/domain/From.java
- legacy/src/main/java/org/opensearch/sql/legacy/domain/Query.java
- legacy/src/main/java/org/opensearch/sql/legacy/esdomain/mapping/FieldMapping.java
- legacy/src/main/java/org/opensearch/sql/legacy/esdomain/mapping/IndexMappings.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/format/BindingTupleResultSet.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/format/Schema.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/format/SelectResultSet.java
- legacy/src/test/java/org/opensearch/sql/legacy/unittest/parser/SqlParserTest.java
- opensearch/build.gradle
- plugin/build.gradle
- protocol/build.gradle
- sql-jdbc/build.gradle
- workbench/public/components/Main/__snapshots__/main.test.tsx.snap
- workbench/public/components/PPLPage/__snapshots__/PPLPage.test.tsx.snap
- workbench/public/components/QueryLanguageSwitch/__snapshots__/Switch.test.tsx.snap
- workbench/public/components/QueryResults/__snapshots__/QueryResults.test.tsx.snap
- workbench/public/components/QueryResults/__snapshots__/QueryResultsBody.test.tsx.snap
- workbench/public/components/SQLPage/__snapshots__/SQLPage.test.tsx.snap
Upgrade OpenSearch version to 2.0.0-alpha1-SNAPSHOT  which has more changes corresponding to removal of mapping types.
https://github.com/opensearch-project/sql/issues/452
https://github.com/opensearch-project/sql/issues/485
> Upgrade OS Version to 2.0.0-alpha1-SNAPSHOT

- build.gradle
- sql-jdbc/build.gradle
> 2.0 build fix

- integ-test/src/test/java/org/opensearch/sql/legacy/JdbcTestIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/utils/LogUtils.java
- legacy/src/test/java/org/opensearch/sql/legacy/unittest/utils/LogUtilsTest.java
Bug Fix, return default ID when log4j ThreadContext is empty.
#537 
- [] New functionality has been documented.
> Bug Fix, return default ID when log4j ThreadContext is empty

- .github/workflows/sql-workbench-test-and-build-workflow.yml
- workbench/opensearch_dashboards.json
- workbench/package.json
- workbench/yarn.lock
Bump dashboards plugin to 1.3.1
> Bump workbench to 1.3.1

- .github/workflows/sql-jdbc-test-and-build-workflow.yml
- .github/workflows/sql-test-and-build-workflow.yml
Removing JDK14 from CI as we will be only supporting Java LTS versions(11&17) from 2.0 release.
> Removign JDK14 from CI

- workbench/opensearch_dashboards.json
- workbench/package.json
rc1 will be used instead of alpha1, will send another PR to update for opensearch plugins when core is ready
> Change alpha1 to rc1 for first 2.0 release

- .github/workflows/sql-cli-release-workflow.yml
- .github/workflows/sql-jdbc-release-workflow.yml
- .github/workflows/sql-release-workflow.yml
- DEVELOPER_GUIDE.rst
- docs/attributions.md
- docs/dev/Architecture.md
- docs/dev/Doctest.md
- docs/presentations/20201116-sql-demo.md
- plugin/build.gradle
- sql-cli/README.md
- sql-jdbc/docs/tableau.md
- sql-odbc/THIRD-PARTY
- sql-odbc/docs/dev/run_tests.md
- workbench/CONTRIBUTING.md
Change master nomenclature: Change `master` (mostly Github link) to `main` in docs and comments.
The only code using master nomenclature is in OpenSearch API call which doesn't seem have alternative clusterManager class or method:
```
RestQuerySettingsAction:
final ClusterUpdateSettingsRequest clusterUpdateSettingsRequest =
Requests.clusterUpdateSettingsRequest();
clusterUpdateSettingsRequest.timeout(request.paramAsTime(
"timeout", clusterUpdateSettingsRequest.timeout()));
clusterUpdateSettingsRequest.masterNodeTimeout(request.paramAsTime(
"master_timeout", clusterUpdateSettingsRequest.masterNodeTimeout()));
```
The following `master` in doc link are also not changed due to `main` branch missing:
``` …
```
> Change master nomenclature

- integ-test/src/test/java/org/opensearch/sql/legacy/SQLFunctionsIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/utils/SQLFunctions.java
- legacy/src/test/java/org/opensearch/sql/legacy/antlr/SyntaxAnalysisTest.java
Change blacklist and whitelist nomenclature: from blacklist and whitelist to denylist and allowlist.
https://github.com/opensearch-project/sql/issues/464
> Change blacklist and whitelist nomenclature

- plugin/build.gradle
Signed-off-by: Owais Kazi <owaiskazi19@gmail.com>
> Removed ES reference from build.gradle

- docs/category.json
- doctest/build.gradle
Signed-off-by: jackiehanyang <jkhanjob@gmail.com>
- Fix doctest not running issue. 
- Comment out `ad` in doctest running list as it takes more time to investigate. It looks like something is wrong in the doctest-cluster transport layer when ppl makes the call to ml-commons. Will take look into it. 
> Fix doctest not running issue

- bi-connectors/TableauConnector/opensearch_sql_jdbc/dialect.tdd
Added function to cast string to int. The generated query will cast to DOUBLE before casting to INT to cover the case of "2.1".
https://github.com/opensearch-project/sql/issues/554
> Added function to cast string to int

- bi-connectors/TableauConnector/opensearch_sql_jdbc/dialect.tdd
Tests fixed:
- exprtests/standard\setup.string.left.real.txt
- exprtests/standard\setup.string.right.real.txt
- exprtests/standard\setup.string.rtrim.txt
- exprtests/standard\setup.cast.float.string.txt
- exprtests/standard\setup.string.mid.calc.txt
- staples\setup.Filter.Add_to_context.simple_lower.xml
Functions removed as they are unsupported:
- SPACE
- CHAR
- SPLIT
> Fix String Functions in the Tableau Connector

- bi-connectors/TableauConnector/opensearch_sql_jdbc/dialect.tdd
Fixed functions for IFNULL with date as the old formula was incorrect.
> Fix IFNULL Function in the Tableau Connector

- bi-connectors/TableauConnector/opensearch_sql_jdbc/dialect.tdd
The test case `ISDATE("2015-01-01")` passes but `ISDATE("data")` fails because of the issue below.
This function will work as expected when https://github.com/opensearch-project/sql/issues/580 is fixed.
> TDVT Add ISDATE back as a Tableau function

- .github/workflows/sql-workbench-test-and-build-workflow.yml
- workbench/package.json
> Remove explicit node version for workbench

- .github/workflows/sql-test-and-build-workflow.yml
- .github/workflows/sql-workbench-test-and-build-workflow.yml
- build.gradle
- doctest/build.gradle
- opensearch/build.gradle
- workbench/opensearch_dashboards.json
- workbench/package.json
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Incremented version to 1.3.2.
Part of https://github.com/opensearch-project/opensearch-build/issues/1882
> Incremented version to 1.3.2.

- build.gradle
- doctest/build.gradle
- doctest/opensearch-ml/.gitignore
- workbench/opensearch_dashboards.json
- workbench/package.json
closes #597 
CI will fail until ml-commons 2.0 is ready
> Remove rc1 qualifier for 2.0

- integ-test/src/test/java/org/opensearch/sql/correctness/tests/TestConfigTest.java
- integ-test/src/test/java/org/opensearch/sql/correctness/tests/TestDataSetTest.java
- integ-test/src/test/java/org/opensearch/sql/correctness/tests/TestQuerySetTest.java
- integ-test/src/test/java/org/opensearch/sql/util/MatcherUtils.java
- legacy/src/test/java/org/opensearch/sql/legacy/antlr/semantic/SemanticAnalyzerBasicTest.java
- legacy/src/test/java/org/opensearch/sql/legacy/antlr/semantic/scope/EnvironmentTest.java
- legacy/src/test/java/org/opensearch/sql/legacy/antlr/semantic/scope/SymbolTableTest.java
- legacy/src/test/java/org/opensearch/sql/legacy/esdomain/mapping/FieldMappingTest.java
- legacy/src/test/java/org/opensearch/sql/legacy/unittest/cursor/DefaultCursorTest.java
- legacy/src/test/java/org/opensearch/sql/legacy/unittest/expression/model/ExprValueUtilsTest.java
- legacy/src/test/java/org/opensearch/sql/legacy/util/MatcherUtils.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/UnresolvedPlanHelperTest.java
Changes the deprecated method, org.junit.Assert.assertThat, to  org.hamcrest.MatcherAssert.assertThat.
Replaces deprecated method org.junit.Assert.assertThat.
> Integ replace junit assertthat with hamcrest import

- integ-test/src/test/java/org/opensearch/sql/legacy/AggregationExpressionIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/AggregationIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/DateFormatIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/JdbcTestIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLFunctionsIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SubqueryIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TypeInformationIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/ConditionalIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/RelevanceFunctionIT.java
- plugin/build.gradle
Integration test failing with base class using JUnit4. Integration test queries required FROM clause in SELECT statements.
> Integ relevance function it fix

- ppl/src/test/java/org/opensearch/sql/ppl/antlr/PPLSyntaxParserTest.java
This PR is to fix a conflict that should've been solved before merging #646 .
> Fix merge conflict on function name

- integ-test/src/test/java/org/opensearch/sql/ppl/RelevanceFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/MultiMatchIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiMatchQuery.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MultiMatchTest.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Signed-off-by: Yury Fridlyand <yuryf@bitquilltech.com>
Hotfix for PR #649.
Fix `fuzziness` parsing in `multi_match` query builder. Tests are updated to extend coverage.
> Fix `fuzziness` parsing in `multi_match` function. Update tests.

- DEVELOPER_GUIDE.rst
- doctest/build.gradle
- integ-test/build.gradle
- settings.gradle
Signed-off-by: Kavitha Conjeevaram Mohan <mohakavi@amazon.com>
Providing alias for plugin folder name and changing the plugin name in respective files too.
this PR ports #662 to main
> change plugin folder name to opensearch-sql-plugin

- sql-cli/README.md
Signed-off-by: Yury Fridlyand [yuryf@bitquilltech.com](mailto:yuryf@bitquilltech.com)
Re-applying (cherry-pick) c523102 made by @dai-chen. Should be merged into all PRs opened now.
Fixes link checker failures.
> Fix broken forum link

- sql-jdbc/build.gradle
- sql-jdbc/src/test/java/org/opensearch/jdbc/transport/http/auth/aws/AWSRequestSigningApacheInterceptorTests.java
Bump dependency version:
1. Httpclient
2. Wiremock (test dependency)
3. Guava (test dependency introduced by wiremock)
4. Json-smart (test dependency introduced by wiremock)
N/A
> Bump JDBC driver's dependency version

- build.gradle
- core/build.gradle
- integ-test/build.gradle
- opensearch/build.gradle
- plugin/build.gradle
- ppl/build.gradle
- protocol/build.gradle
- sql-jdbc/build.gradle
- sql/build.gradle
Bump Jackson dependency version and extract hardcoding version number to root Gradle script. Will back port this to 1.3 branch after merged.
Verify all Jackson dependencies upgraded to latest 2.13.3:
```
$ ./gradlew clean
$ ./gradlew assemble
$ unzip -l plugin/build/distributions/opensearch-sql-2.2.0.0-SNAPSHOT.zip | grep -E 'spring|jackson'
1275108  08-04-2022 11:08   spring-context-5.3.22.jar
382963  08-04-2022 11:08   spring-aop-5.3.22.jar
699011  08-04-2022 11:08   spring-beans-5.3.22.jar
75714  07-19-2022 13:34   jackson-annotations-2.13.3.jar
1536542  07-19-2022 13:34   jackson-databind-2.13.3.jar
289392  08-04-2022 11:08   spring-expression-5.3.22.jar
1486059  08-04-2022 11:08   spring-core-5.3.22.jar
24436  08-04-2022 11:08   spring-jcl-5.3.22.jar
```
Note that SQL JDBC only has …
> Bump Jackson dependency version

- build.gradle
- core/build.gradle
- plugin/build.gradle
- ppl/build.gradle
- sql/build.gradle
Back porting https://github.com/opensearch-project/sql/pull/745 to OpenSearch 1.3. The Github action is failing due to Jackson which will be version bumped in separate PR.
N/A
> Bump Spring version in 1.3

- build.gradle
- opensearch/build.gradle
- protocol/build.gradle
- sql-jdbc/build.gradle
Back porting https://github.com/opensearch-project/sql/pull/745 to 1.3 branch. Change jackson-databind version to 1.13.2.2 to match jackson introduced in OpenSearch core's: https://github.com/opensearch-project/OpenSearch/blob/1.3/buildSrc/version.properties#L13
N/A
> Bump jackson-databind version 1.13.2.2

- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchPhrasePrefixQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchPhraseQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiMatchQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/QueryStringQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SimpleQueryStringQuery.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchPhrasePrefixQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchPhraseQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MultiMatchTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/QueryStringTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/RangeQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/SimpleQueryStringTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQueryBuildTest.java
Allows for any case on argument name for relevancy based function (Match Phrase Prefix, Simple Query String,  Match Bool Prefix, Match, Multi-Match, Query String, Relevance, Simple Query String). 
e.g. 
`AnalyZer` can work instead of just `analyzer`
`Zero_Terms_Query` can work instead of just `zero_terms_query`
`BOOst` can work instead of just `boost`
Allows for `zero_term_query` arguments to be of any case.
e.g.
`All` can work instead of `ALL`
> Add any case of arguments in relevancy based functions to be allowed

- build.gradle
- core/build.gradle
- opensearch/build.gradle
- plugin/build.gradle
- ppl/build.gradle
- protocol/build.gradle
- sql-jdbc/build.gradle
- sql/build.gradle
Backporting #751 and #756 to 1.x branch.
N/A
> Backport Spring and jackson-databind version bump to 1.x

- workbench/public/components/Main/main.tsx
> Update PPL docs link for workbench

- legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlAction.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/executor/Scheduler.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/executor/SchedulerTest.java
- plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLQueryAction.java
* Schedule request in worker thread.
> Schedule request in worker thread

- .github/workflows/sql-test-and-build-workflow.yml
- .github/workflows/sql-workbench-test-and-build-workflow.yml
- build.gradle
- doctest/build.gradle
- scripts/build.sh
- workbench/opensearch_dashboards.json
- workbench/package.json
Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
Version increment 1.3.5
Part of: https://github.com/opensearch-project/opensearch-build/issues/2348
> [Release 1.3.5] Version increment and add `build.sh`

- build.gradle
- config/checkstyle/google_checks.xml
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
- core/src/test/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitorTest.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/core/ExpressionScript.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtectorTest.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/Format.java
1. Bump checkstyle from 8.28 to the latest version and fixed all violations.
2. Change `subprojects` to `allprojects` to enforce root project using same version as subproject (specified by `toolVersion`). Otherwise, the default Checkstyle version (8.37) defined by Gradle is in use.
```
$ ./gradlew dependencies :sql:dependencies :ppl:dependencies :core:dependencies :protocol:dependencies :opensearch-sql-plugin:dependencies :opensearch:dependencies :legacy:dependencies :common:dependencies | grep checkstyle
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:10.3.2
checkstyle - The Checkstyle libraries to be used for this project.
\--- com.puppycrawl.tools:checkstyle:10.3.2
checkstyle - The …
```
> Bump Checkstyle version to latest

- docs/user/ppl/admin/security.rst
- docs/user/ppl/index.rst
PPL Security Setting Documentations. https://github.com/penghuo/os-sql/blob/main-pplSecurityDoc/docs/user/ppl/admin/security.rst
> Add PPL security setting documentation

- plugin/build.gradle
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
- plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLQueryAction.java
- plugin/src/main/java/org/opensearch/sql/plugin/transport/PPLQueryAction.java
- plugin/src/main/java/org/opensearch/sql/plugin/transport/TransportPPLQueryAction.java
- plugin/src/main/java/org/opensearch/sql/plugin/transport/TransportPPLQueryRequest.java
- plugin/src/main/java/org/opensearch/sql/plugin/transport/TransportPPLQueryResponse.java
- plugin/src/test/java/org/opensearch/sql/plugin/transport/TransportPPLQueryRequestTest.java
- ppl/src/main/java/org/opensearch/sql/ppl/domain/PPLQueryRequest.java
> [Backport] implement transport api for PPL inter-plugin communication (#533)

- legacy/src/main/java/org/opensearch/sql/legacy/plugin/OpenSearchSQLPluginConfig.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
- plugin/src/main/java/org/opensearch/sql/plugin/rest/OpenSearchPluginConfig.java
cherry pick. https://github.com/opensearch-project/sql/pull/774
> Deprecated ClusterService and Using NodeClient to fetch meta data (#774)

- plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java
Change `masterNodeTimeout` to new API `clusterManagerNodeTimeout`.
https://github.com/opensearch-project/sql/issues/463
> Change master node timeout to new API

- bi-connectors/PowerBIConnector/src/OpenSearchProject.query.pq
Last time we updated PowerBI connector, we missed to update embedded unit tests.
These tests may be executed by a developer only. To run tests you need to install `PowerQuerySDK for Visual Studio`, open `mproj` file (`bi-connectors/PowerBIConnector/src/OpenSearchProject.mproj`) with Visual Studio and run it.
> Fix unit test in PowerBI connector.

- .github/workflows/draft-release-notes-workflow.yml
- .github/workflows/sql-odbc-release-workflow.yml
- .github/workflows/sql-workbench-release-workflow.yml
- .github/workflows/sql-workbench-test-and-build-workflow.yml
- build.gradle
- sql-jdbc/build.gradle
- workbench/opensearch_dashboards.json
- workbench/package.json
> Bump version to 2.3.0

- legacy/build.gradle
- legacy/src/main/java/org/opensearch/sql/legacy/executor/csv/CSVResultsExtractor.java
- legacy/src/main/java/org/opensearch/sql/legacy/query/maker/AggMaker.java
Fix build issue with 2.3 release. OpenSearch core move geo to separate module. https://github.com/opensearch-project/OpenSearch/pull/4180. Plugin need add geo module as dependency.
> Fix compile issue, add geo module as dependency

- core/src/main/java/org/opensearch/sql/planner/physical/AggregationOperator.java
- core/src/test/java/org/opensearch/sql/planner/physical/AggregationOperatorTest.java
> Bugfix, copy of AggregationOperator should be same

- README.md
Signed-off-by: cwillum <cwmmoore@amazon.com>
Added Forum header section that includes verbiage and a link to the OpenSearch Forum page for the SQL plugin.
This more closely corresponds to the information found in the README.md file in all of the other plugins bundled with OpenSearch.
This fixes the issue for the SQL plugin in [#921](https://github.com/opensearch-project/documentation-website/issues/921).
> Add Forum link in SQL plugin README.md

- release-notes/opensearch-sql.release-notes-2.3.0.0.md
> add 2.3 release notes

- core/src/main/java/org/opensearch/sql/planner/physical/AggregationOperator.java
- core/src/main/java/org/opensearch/sql/planner/physical/DedupeOperator.java
- core/src/main/java/org/opensearch/sql/planner/physical/FilterOperator.java
- core/src/main/java/org/opensearch/sql/planner/physical/LimitOperator.java
- core/src/main/java/org/opensearch/sql/planner/physical/ProjectOperator.java
- core/src/main/java/org/opensearch/sql/planner/physical/RareTopNOperator.java
- core/src/main/java/org/opensearch/sql/planner/physical/RemoveOperator.java
- core/src/main/java/org/opensearch/sql/planner/physical/RenameOperator.java
- core/src/main/java/org/opensearch/sql/planner/physical/SortOperator.java
Fix warning messages in GitHub actions associated with EqualsAndHashCode annotations.
> Fix EqualsAndHashCode Annotation Warning Messages

- build.gradle
`./gradlew compile` currently fails because sql plugin uses jackson 2.13.3, but opensearch snapshot it depends on is now on [2.13.4](https://github.com/opensearch-project/OpenSearch/pull/4556).
Signed-off-by: MaxKsyunz <maxk@bitquilltech.com>
> Update com.fasterxml.jackson to 2.13.4 to match opensearch repo.

- .github/workflows/bi-connectors.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/draft-release-notes-workflow.yml
- .github/workflows/link-checker.yml
- .github/workflows/sql-cli-test-and-build-workflow.yml
- .github/workflows/sql-jdbc-test-and-build-workflow.yml
- .github/workflows/sql-odbc-main.yml
- .github/workflows/sql-test-and-build-workflow.yml
- .github/workflows/sql-workbench-test-and-build-workflow.yml
Build is not getting triggered on updating PR with new commits.
Removed types under pull_request. This would default to opened, reopened, synchronize.
Ref for synchronize def: https://frontside.com/blog/2020-05-26-github-actions-pull_request/
> Trigger build on pull request synchronize action.

- .github/workflows/sql-test-and-build-workflow.yml
- .github/workflows/sql-workbench-test-and-build-workflow.yml
- workbench/package.json
* Fix java installation for SQL plugin workflow;
* Backport workbench CI fixes from #588 and #704.
See most recent workflow runs in https://github.com/Bit-Quill/opensearch-project-sql/actions?query=branch%3Adev-fix-ci-1.x
Fix failing CI workflows: https://github.com/opensearch-project/sql/actions/workflows/sql-test-and-build-workflow.yml?query=branch%3A1.x
> Fix CI workflows on `1.x`

- core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
- core/src/main/java/org/opensearch/sql/analysis/model/CatalogName.java
- core/src/main/java/org/opensearch/sql/analysis/model/CatalogSchemaIdentifierName.java
- core/src/main/java/org/opensearch/sql/analysis/model/SchemaName.java
- core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java
- core/src/main/java/org/opensearch/sql/ast/tree/Relation.java
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
- core/src/test/java/org/opensearch/sql/analysis/model/CatalogSchemaIdentifierNameTest.java
- plugin/src/main/java/org/opensearch/sql/plugin/catalog/CatalogServiceImpl.java
- plugin/src/test/java/org/opensearch/sql/plugin/catalog/CatalogServiceImplTest.java
- plugin/src/test/resources/duplicate_catalog_names.json
- plugin/src/test/resources/illegal_catalog_name.json
- ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
Restricting catalog name to [a-zA-Z0-9_-] characters.
https://github.com/opensearch-project/sql/issues/619
Will raise document PR separately.
- [x ] Commits are signed per the DCO using --signoff 
> Restricted catalog name to [a-zA-Z0-9_-] characters

- core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
- core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java
- core/src/main/java/org/opensearch/sql/analysis/HighlightAnalyzer.java
- core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
- core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java
- core/src/main/java/org/opensearch/sql/ast/expression/HighlightFunction.java
- core/src/main/java/org/opensearch/sql/expression/HighlightExpression.java
- core/src/main/java/org/opensearch/sql/expression/function/OpenSearchFunctions.java
- core/src/main/java/org/opensearch/sql/planner/logical/LogicalHighlight.java
- core/src/main/java/org/opensearch/sql/planner/logical/LogicalPlanDSL.java
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
- core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
- core/src/test/java/org/opensearch/sql/analysis/NamedExpressionAnalyzerTest.java
- core/src/test/java/org/opensearch/sql/expression/HighlightExpressionTest.java
- core/src/test/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitorTest.java
- integ-test/src/test/java/org/opensearch/sql/sql/HighlightFunctionIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchDefaultImplementorTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexScanTest.java
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Add support for wildcard in SQL with optional arguments `pre_tags` and `post_tags`.
`select highlight('Body'), highlight('T*') from beer where multi_match([Title, Body, Tags], 'taste');`
Issue: [636](https://github.com/opensearch-project/sql/issues/636)
> Add Support for Highlight Wildcard in SQL

- plugin/build.gradle
Added groupId as org.opensearch.plugin in pluginZip publication
https://github.com/opensearch-project/opensearch-build/issues/2521
https://github.com/opensearch-project/sql/issues/790
> add groupId to pluginzip publication

- release-notes/opendistro-for-elasticsearch-sql.release-notes-1.3.0.0.md
- release-notes/opensearch-sql.release-notes-1.2.0.0.md
Fix broken links.
Link checker GHA failed: https://github.com/Bit-Quill/opensearch-project-sql/actions/runs/3239220029/jobs/5308341724
```
* [https://github.com/opendistro-for-elasticsearch/sql/issues215](https://github.com/opendistro-for-elasticsearch/sql/issues215): Failed: Network error (status code: 404)
* [https://github.com/kylepbi%E2%80%A6](https://github.com/kylepbi%E2%80%A6): Failed: Network error (status code: 404)
```
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develo …
> Fix broken links

- sql-cli/src/opensearch_sql_cli/main.py
- sql-cli/src/opensearch_sql_cli/opensearch_connection.py
How to test:
`sudo apt-get install awscli`
or
`brew install awscli`
if this doesn't work, try
`pip3 install --upgrade awscli`
`awscli configure`
or if you installed it using `pip`
`python3 -m awscli configure`
Enter your access key, secret key and region
Run
`awscli sts get-session-token`
the output is like
```json
{
"Credentials": {
"AccessKeyId": "...",
"SecretAccessKey": "...",
"SessionToken": "...",
"Expiration": "2022-10-15T04:31:24Z"
}
}
```
Record your temporary keys and session token.
Follow the guide https://github.com/opensearch-project/sql/blob/2.x/sql-cli/development_guide.md#development-environment-set-up
Ensure that `~/.aws/credentials` contains `default` profile with your permanent keys, no session token yet there. …
> Update SQL CLI to use AWS session token.

- plugin/src/main/plugin-metadata/plugin-security.policy
ml-commons requires `setContextClassLoader` to run, ref: https://github.com/opensearch-project/neural-search/blob/d8b24bf5f71c7e8cba5988d6bd18462002802cf7/src/main/plugin-metadata/plugin-security.policy
error: 
```
java.lang.ExceptionInInitializerError
at org.opensearch.ml.common.output.MLOutput.fromStream(MLOutput.java:35)
at org.opensearch.ml.common.transport.MLTaskResponse.<init>(MLTaskResponse.java:38)
at org.opensearch.ml.common.transport.MLTaskResponse.fromActionResponse(MLTaskResponse.java:55)
at org.opensearch.ml.client.MachineLearningNodeClient.lambda$getMlPredictionTaskResponseActionListener$8(MachineLearningNodeClient.java:148)
at org.opensearch.ml.client.MachineLearningNodeClient.lambda$wrapActionListener$9(MachineLearningNodeCli …
```
> Add security policy for ml-commons library

- core/src/main/java/org/opensearch/sql/planner/physical/ProjectOperator.java
- core/src/test/java/org/opensearch/sql/planner/physical/ProjectOperatorTest.java
- integ-test/src/test/java/org/opensearch/sql/ppl/ParseCommandIT.java
ProjectOperator assumes derived fields comes at last, since they are generated at run time. it's incorrect since there could be other run time fields (e.g. `eval`, `AD`). This PR fixes it.
Maybe `parse` should not allow overwriting original fields so ProjectOperator doesn't have to maintain a separate named expression list and handle conflicts.
> Fix result order of parse with other run time fields

- core/src/main/java/org/opensearch/sql/utils/MLCommonsConstants.java
- docs/category.json
- docs/user/ppl/cmd/ad.rst
- doctest/test_data/nyc_taxi.json
- doctest/test_mapping/nyc_taxi.json
- opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/ADOperator.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/MLCommonsOperatorActions.java
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
Add `category_field` to `AD` command. PPL will group inputs by category, and each group will be sent to AD for predictions separately. This is a temporary solution before ml-commons supports 2 dimensional data.
Enabled doctest for AD (which was disabled by #575)
> Add category_field to AD command in PPL

- .gitignore
- docs/user/ppl/admin/catalog.rst
- docs/user/ppl/index.rst
- doctest/build.gradle
- doctest/catalog/catalog.json
Documentation for catalog and added prometheus connector in doctest cluster.
One can view the page here: https://github.com/vamsi-amazon/sql/blob/docs-prometheus/docs/user/ppl/admin/catalog.rst
https://github.com/opensearch-project/sql/issues/939
> Adding docs related to catalog.

- workbench/package.json
- workbench/yarn.lock
> Bump ansi-regex for workbench

- .github/workflows/sql-test-workflow.yml
* Fix manual CI workflow.
* Add `name` optional parameter; If not given `<branch name> @ <commit sha>` is used.
Workflow ignored all test errors and reported always success. Workflow was introduced in #837.
> Fix manual CI workflow and add `name` option.

- sql-jdbc/build.gradle
Removed json-smart in the jdbc driver as it introduces a CVE (CVE-2021-31684).
> Removed json-smart in the JDBC driver

- core/src/main/java/org/opensearch/sql/planner/streaming/windowing/Window.java
- core/src/main/java/org/opensearch/sql/planner/streaming/windowing/assigner/SlidingWindowAssigner.java
- core/src/main/java/org/opensearch/sql/planner/streaming/windowing/assigner/TumblingWindowAssigner.java
- core/src/main/java/org/opensearch/sql/planner/streaming/windowing/assigner/WindowAssigner.java
- core/src/main/java/org/opensearch/sql/utils/DateTimeUtils.java
- core/src/test/java/org/opensearch/sql/planner/streaming/windowing/WindowTest.java
- core/src/test/java/org/opensearch/sql/planner/streaming/windowing/assigner/SlidingWindowAssignerTest.java
- core/src/test/java/org/opensearch/sql/planner/streaming/windowing/assigner/TumblingWindowAssignerTest.java
Add window and window assigner interface along with tumbling and sliding window assigner implementation. This PR is only focus on core `WindowAssigner` interface. The future tasks in https://github.com/opensearch-project/sql/issues/954 will integrate it and other new windowing components with query plan operator.
A Window is a time interval which has start timestamp and end timestamp. For convenience, the end timestamp is exclusive and thus the window boundary is actually `[startTime, endTime-1]`.
A WindowAssigner identifies which window(s) the event belong. This is the first step and foundation of handling unbounded streaming data. As follows, an event may be assigned to a single window or multiple windows according to the windowing function. …
> Add time window and window assigner

- core/src/main/java/org/opensearch/sql/executor/streaming/DefaultMetadataLog.java
- core/src/main/java/org/opensearch/sql/executor/streaming/MetadataLog.java
- core/src/test/java/org/opensearch/sql/executor/streaming/DefaultMetadataLogTest.java
1. Add metadatalog interface which is used by stream source, microbatch execution.
2. Add default in memory implementation of metadatalog.
> Add metadatalog interface and default in memory implementation

- .github/workflows/sql-test-and-build-workflow.yml
- .github/workflows/sql-workbench-test-and-build-workflow.yml
- build.gradle
- doctest/build.gradle
- workbench/opensearch_dashboards.json
- workbench/package.json
* Bump version to 1.3.7.
* Bump jackson-databind to 2.13.4.2.
* Disable doctest for ml-commons. 
> Bump version to 1.3.7

- docs/user/general/identifiers.rst
- docs/user/ppl/cmd/describe.rst
- integ-test/src/test/java/org/opensearch/sql/ppl/DescribeCommandIT.java
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClientImpl.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/client/PrometheusClientImplTest.java
* Describe command for prometheus table.
* Documentation and Integration tests.
> Describe Table with catalog name.

- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- legacy/src/main/java/org/opensearch/sql/legacy/utils/QueryDataAnonymizer.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/FunctionParameterRepository.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchBoolPrefixQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchPhrasePrefixQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchPhraseQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiFieldQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiMatchQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/QueryStringQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SimpleQueryStringQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQuery.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MultiMatchTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/QueryStringTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/SimpleQueryStringTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiFieldQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQueryBuildTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQueryTest.java
Rework on #691
Co-authored-by: MaxKsyunz <maxk@bitquilltech.com>
Co-authored-by: forestmvey <forestv@bitquilltech.com>
**1.**
Added cast validation and user-friendly error messages
```sql
SELECT phrase, insert_time2 from phrase WHERE match_phrase(phrase, 'brown fox', slop = 0.5);
```
before
```
{'reason': 'Invalid SQL query', 'details': 'For input string: "0.5"', 'type': 'NumberFormatException'}
```
after
```
{'reason': 'There was internal problem at backend', 'details': "Invalid slop value: '0.5'. Accepts only integer values.", 'type': 'RuntimeException'}
```
**2.**
Cast validation and user-friendly errors for all enum types
```sql
select `key` from calcs where multi_match([str1], 'DVD', zero_terms_query=meow);
```
before
``` …
```
> Rework on error reporting to make it more verbose and human-friendly.

- core/src/main/java/org/opensearch/sql/planner/streaming/watermark/BoundedOutOfOrderWatermarkGenerator.java
- core/src/main/java/org/opensearch/sql/planner/streaming/watermark/WatermarkGenerator.java
- core/src/test/java/org/opensearch/sql/planner/streaming/watermark/BoundedOutOfOrderWatermarkGeneratorTest.java
Watermark is a monotonically increasing timestamp of the oldest work not yet completed. The work can be any grouping operation, such as aggregate or join, that accumulate stream events to a table and maintain the state. In other words, watermark is the way of how we reason about the completeness of accumulated window state.
There are several aspects of watermark implementation, including watermark generation, watermark emit frequency and watermark propagation. This PR is focused on the watermark generation which has no dependency on how we integrate with query plan later.
What's covered in this PR is the common generate strategy: *Bounded Out-Of-Order Watermark Generator* which allows a fixed delay for disordered data. …
> Add watermark generator

- core/src/main/java/org/opensearch/sql/planner/streaming/StreamContext.java
- core/src/main/java/org/opensearch/sql/planner/streaming/windowing/trigger/AfterWatermarkWindowTrigger.java
- core/src/main/java/org/opensearch/sql/planner/streaming/windowing/trigger/TriggerResult.java
- core/src/main/java/org/opensearch/sql/planner/streaming/windowing/trigger/WindowTrigger.java
- core/src/test/java/org/opensearch/sql/planner/streaming/windowing/trigger/AfterWatermarkWindowTriggerTest.java
As another main component for stream data windowing, this PR adds Window Trigger along with Stream Context.
A stream context holds useful context information for all stream processing components. It’s also easy to store and restore between executions by put all state in one place.
A window trigger determines whether to trigger window state output (a window pane). Common trigger implementation includes:
* After Watermark: trigger if the window is below watermark.
* Count: trigger based on a counter. A special case is per-event trigger for materialized view semantics.
* Time: trigger when its time comes.
Note that window trigger is easy to be confused with watermark. Watermark is the way to reason about the completeness of window state. Window trigger upon user configuration can decide to …
> Add stream context and window trigger

- docs/user/ppl/cmd/ad.rst
- docs/user/ppl/cmd/kmeans.rst
- docs/user/ppl/cmd/ml.rst
- docs/user/ppl/index.rst
Signed-off-by: Jing Zhang <jngz@amazon.com>
Add document for the generic ml command in PPL.
https://github.com/opensearch-project/sql/issues/849
> Add document for ml command.

- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- legacy/src/main/java/org/opensearch/sql/legacy/utils/QueryDataAnonymizer.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/FunctionParameterRepository.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchBoolPrefixQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchPhrasePrefixQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchPhraseQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MatchQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiFieldQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiMatchQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/QueryStringQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SimpleQueryStringQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQuery.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MultiMatchTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/QueryStringTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/SimpleQueryStringTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/MultiFieldQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQueryBuildTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQueryTest.java
Rework on error reporting to make it more verbose and human-friendly.
(cherry picked from commit 21373b9380dea321063dc6a5532b84a2ebec32a4)
Backport #839 to `2.4`.
Please see #839
> [Backport 2.4] Merge pull request #839 from Bit-Quill/integ-improve-error-reporting

- docs/user/ppl/cmd/ad.rst
- docs/user/ppl/cmd/kmeans.rst
- doctest/build.gradle
[temporary] Disable doctests which use `ML-common` plugin.
https://github.com/opensearch-project/sql/pull/915#issuecomment-1294048850
Unblocks #999
> Disable loading `ML-commons` plugin for doctests

- release-notes/opensearch-sql.release-notes-2.4.0.0.md
Add release note for OpenSearch 2.4 release.
https://github.com/opensearch-project/sql/issues/905
> Add 2.4 release note for SQL/PPL

- .github/workflows/sql-test-workflow.yml
Fix manual CI workflow and add `name` option.
(cherry picked from commit ccc223099f142386f260558d78b039dc50994d1f)
Backport #904 into `1.x`
> [Backport 1.x] Fix manual CI workflow and add name option. #904

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/function/OpenSearchFunctions.java
- core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
- core/src/test/java/org/opensearch/sql/expression/function/OpenSearchFunctionsTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/legacy/MethodQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/QueryIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilder.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/NoFieldQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/QueryQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/RelevanceQuery.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/QueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/NoFieldQueryTest.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Query function was added to SQL plugin as alternate syntax to query_string Function. Achieved by routing function calls from the SQL plugin to the query_string function which currently exists in OpenSearch.
> Add Query Function As Alternate Syntax to Query_string Function

- integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusCatalogCommandsIT.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/response/PrometheusResponse.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/storage/implementor/PrometheusDefaultImplementor.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/storage/model/PrometheusResponseFieldNames.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/storage/querybuilder/AggregationQueryBuilder.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricScanTest.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTableTest.java
Backquotes in stats groupby list is causing errors in prometheus connector.
Eg command: 
source=prometheus.promhttp_metric | stats avg(@value) by span(@timestamp, 15s), \`instance\`
> Fix for errors in prometheus connector when backquotes are used for fieldnames in aggregations.

- build.gradle
bump to be consistent with core 2.4 branch: https://github.com/opensearch-project/OpenSearch/commit/7c184ab77c14fd73e76df9c2cea7f610fba21f39
closes https://github.com/opensearch-project/sql/issues/1057
> [2.4] Bump jackson to 2.14.0

- build.gradle
- doctest/build.gradle
- integ-test/build.gradle
This is to fix integration test errors for arm64 archetype.
RCA: using wrong binary to start prometheus server for integ tests.
https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/3242/pipeline/131
> Integ tests fix for arm64.[Failure in starting up prometheus server]

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
- core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
Adds CBRT() math function to the V2 engine.
Usage: CBRT(number) calculates the cube root of a number
Argument type: INTEGER/LONG/FLOAT/DOUBLE
Return type: DOUBLE
(Non-negative) INTEGER/LONG/FLOAT/DOUBLE -> DOUBLE
(Negative) INTEGER/LONG/FLOAT/DOUBLE -> DOUBLE
Example::
opensearchsql> SELECT CBRT(8), CBRT(9.261), CBRT(-27);
+-----------+---------------+-------------+
| CBRT(8)   | CBRT(9.261)   | CBRT(-27)   |
|-----------+---------------+-------------|
| 2.0       | 2.1           | -3.0        |
+-----------+---------------+-------------+
For more information on following Developer Certificate of Origin …
> Add CBRT to the V2 engine

- prometheus/build.gradle
CVE-2020-15250 fix 
```
❯ gradle -q dependencyInsight --configuration testRuntimeClasspath  --dependency junit:junit
=======================================
OpenSearch Build Hamster says Hello!
Gradle Version        : 7.5.1
OS Info               : Mac OS X 12.6 (x86_64)
JDK Version           : 11 (Amazon Corretto JDK)
JAVA_HOME             : /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
Random Testing Seed   : 3EBDD3744BBE9892
In FIPS 140 mode      : false
=======================================
junit:junit:4.13.2 (forced)
Variant runtime:
| Attribute Name                 | Provided     | Requested    |
|--------------------------------|--------------|--------------|
| org.gradle.status              | release      |              |
| org.gradle.category …
```
> CVE-2020-15250 fix

- .gitignore
- DEVELOPER_GUIDE.rst
- plugin/build.gradle
1. Support  opensearch-sql:run
2. Update developer_guide doc. add prometheus and filesystem description.
3. Add .java-version to .gitignore
> Support opensearch-sql:run and update developer_guide doc

- integ-test/build.gradle
> CVE-2022-45868 fix

- core/src/main/java/org/opensearch/sql/expression/function/OpenSearchFunctions.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/MatchIT.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchQueryTest.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Adds `match_query` and `matchquery` as alternate syntax for `match` function which currently exists in OpenSearch.
This is being done to support legacy syntax.
Queries can be performed using the following syntax : 
```
matchquery(field, 'query')
match_query(field, 'query')
```
Example:
```
SELECT field FROM index WHERE matchquery(field, 'query');
SELECT field FROM index WHERE match_query(field, 'query');
```
These queries should return the same result as `match(field, 'query')`
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-c …
> Add Support For Legacy Syntax For Match Function In New Engine

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Adds the `day_of_year` function to the SQL plugin. It behaves like the `dayofyear` function which already exists in the new engine, and both are aligned with [MySQL](https://www.w3schools.com/sql/func_mysql_dayofyear.asp)
*Note: This function does not currently support the `TIME` type because adding support for this is currently blocked by [PR 1047](https://github.com/opensearch-project/sql/pull/1047). This will be accomplished in future work.
#722 
> Add Day_Of_Year Function To OpenSearch

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Adds the `month_of_year` function to the SQL plugin. It behaves like the `month` function which already exists in the new engine, and both are aligned with [MySQL](https://www.w3schools.com/sql/func_mysql_month.asp)
*Note: This function does not currently support the `TIME` type because adding support for this is currently blocked by [PR 1047](https://github.com/opensearch-project/sql/pull/1047). This will be accomplished in future work.
#722 
> Add Month_Of_Year Function To OpenSearch

- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/main/java/org/opensearch/sql/expression/function/OpenSearchFunctions.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/MultiMatchIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilder.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MultiMatchTest.java
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Add support for alternative syntax of `MULTI_MATCH` relevance search functions. Legacy engine supports parameter keys as quoted, or unquoted values for both required and optional arguments. This syntax has been ported over to all relevance functions in the V2 engine.
```
SELECT * FROM stackexchange_beer WHERE MULTI_MATCH('query'='cicerone', 'fields'='Tags');
SELECT * FROM stackexchange_beer WHERE MULTIMATCH('query'='cicerone', 'fields'='Tags');
SELECT * FROM stackexchange_beer WHERE MULTIMATCHQUERY('query'='cicerone', fields='Tags');
SELECT * FROM stackexchange_beer WHERE MULTIMATCHQUERY(query='cicerone', 'fields'=['Title,Tags^2.0']);
```
For more information on following …
> Add Support for Alternate Legacy MULTIMATCH syntax

- docs/user/ppl/functions/string.rst
- integ-test/src/test/java/org/opensearch/sql/ppl/PositionFunctionIT.java
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
* Add position() string function to PPL
Signed-off-by: Margarit Hakobyan <margarith@bitquilltech.com>
Usage: The syntax POSITION(substr IN str) returns the position of the first occurrence of substring substr in string str. Returns 0 if substr is not in str. Returns NULL if any argument is NULL.
Argument type: STRING, STRING
Return type INTEGER:
(STRING IN STRING) -> INTEGER
Example::
os> source=people | eval `POSITION('world' IN 'helloworld')` = POSITION('world' IN 'helloworld'), `POSITION('invalid' IN 'helloworld')`= POSITION('invalid' IN 'helloworld')  | fields `POSITION('world' IN 'helloworld')`, `POSITION('invalid' IN 'helloworld')`
+-------------------------------------+---------------------------------------+
| POSITION('world' IN 'helloworld')   | …
> Add position() string function to PPL

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/main/java/org/opensearch/sql/expression/text/TextFunction.java
- core/src/test/java/org/opensearch/sql/expression/text/TextFunctionTest.java
- docs/user/dql/functions.rst
- docs/user/ppl/functions/string.rst
- integ-test/src/test/java/org/opensearch/sql/ppl/TextFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/TextFunctionIT.java
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
* Add reverse() string function to V2
Signed-off-by: Margarit Hakobyan <margarith@bitquilltech.com>
Usage: REVERSE(str) returns reversed string of the string supplied as an argument. Returns NULL if the argument is NULL.
Argument type: STRING
Return type: STRING
Example::
os> SELECT REVERSE('abcde')
+--------------------+
| REVERSE('abcde')   |
|--------------------|
| edcba              |
+--------------------+
Example::
os> source=people | eval `REVERSE('abcde')` = REVERSE('abcde') | fields `REVERSE('abcde')`
+--------------------+
| REVERSE('abcde')   |
|--------------------|
| edcba              |
+--------------------+
By submitting this pull request, I confirm that my contribution …
> Add reverse() string function to V2

- build.gradle
- integ-test/build.gradle
- plugin/build.gradle
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
The distribution builds [1] are failing with:
```
Execution failed for task ':opensearch-sql-plugin:compileJava'.
> Could not resolve all dependencies for configuration ':opensearch-sql-plugin:compileClasspath'.
> Conflict(s) found for the following module(s):
- com.fasterxml.jackson.dataformat:jackson-dataformat-smile between versions 2.14.1 and 2.13.4
- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml between versions 2.14.1 and 2.13.4
Run with:
--scan or
:opensearch-sql-plugin:dependencyInsight --configuration compileClasspath --dependency com.fasterxml.jackson.dataformat:jackson-dataformat-smile
to get more insight on how to solve the conflict.
```
[1]  https://build.ci.opensearch.org/job/distribution-build-opensearch/6673/con …
> Update Jackson to 2.14.1 and fix dependency resolution issues

- build.gradle
- core/build.gradle
- integ-test/build.gradle
- opensearch/build.gradle
- plugin/build.gradle
- prometheus/build.gradle
- protocol/build.gradle
Using jackson and jackson_databind version defined in OpenSearch.  SQL plugins's jackson depedency will automatically allign with OpenSearch core then.
> Using jackson and jackson_databind version defined in OpenSearch

- build.gradle
- integ-test/build.gradle
- opensearch/build.gradle
- plugin/build.gradle
- protocol/build.gradle
(cherry picked from commit 5073215f813bad5fdad0d5d37a20c7cb100296fd)
Related to https://github.com/opensearch-project/sql/pull/1169
> Using jackson and jackson_databind version defined in OpenSearch (#1169)

- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
This PR fixed arithmetic operator precedence reported in the issue below. I tried to reorder operator in `mathOperator` rule (Reference: https://github.com/antlr/grammars-v4/blob/master/sql/mysql/Positive-Technologies/MySqlParser.g4#L2598). However, reordering operator inside `mathOperator` rule didn't work at all.
Finally, I split the `mathExpressionAtom` rule and order them by precedence (Reference: https://github.com/crate/crate/blob/master/libs/sql-parser/src/main/antlr/SqlBaseParser.g4#L299).
https://github.com/opensearch-project/sql/issues/293 …
> Fix arithmetic operator precedence

- core/src/main/java/org/opensearch/sql/expression/function/OpenSearchFunctions.java
- core/src/main/java/org/opensearch/sql/expression/function/RelevanceFunctionResolver.java
- core/src/test/java/org/opensearch/sql/analysis/ExpressionAnalyzerTest.java
- core/src/test/java/org/opensearch/sql/config/TestConfig.java
- core/src/test/java/org/opensearch/sql/expression/function/RelevanceFunctionResolverTest.java
- integ-test/src/test/java/org/opensearch/sql/sql/MatchIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQuery.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchBoolPrefixQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchPhrasePrefixQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchPhraseQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/MatchQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/WildcardQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/relevance/SingleFieldQueryTest.java
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Relevance functions that query fields should act similar to how a `SELECT` query works. If a field is queried that does not exist, a `SemanticCheckException` should be thrown.
`SELECT * FROM stackexchange_beer WHERE query_string([invalid], 'beer');`
```
{'reason': 'Invalid SQL query', 'details': "can't resolve Symbol(namespace=FIELD_NAME, name=invalid) in type env", 'type': 'SemanticCheckException'}
```
`SELECT * FROM stackexchange_beer WHERE match(invalid, 'beer');`
```
{'reason': 'Invalid SQL query', 'details': "can't resolve Symbol(namespace=FIELD_NAME, name=invalid) in type env", 'type': 'SemanticCheckException'}
```
[Issue: 613](https://github.com/opensearch-project/sql/issues/613)
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> Validate Field and Fields Parameters in Relevance Search Functions

- docs/user/limitations/limitations.rst
- integ-test/src/test/resources/correctness/bugfixes/550.txt
- sql/src/main/java/org/opensearch/sql/sql/parser/AstBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
Previously, FROM subquery alias was not unquoted in AST layer. This caused back quoted symbol name pushed to symbol table and thus fall back to legacy subquery logic due to semantic exception. 
Take ```SELECT `a`.`name` FROM (...) AS `a` ``` for example. In AST node, alias name of `RelationSubquery` is still ``` `a` ``` and then Analyzer push ``` `a` ``` to symbol table. When resolving `a` in `a.name`, semantic exception is thrown because there is ``` `a` ``` instead of `a` in symbol table. Please check the comments in https://github.com/opensearch-project/sql/issues/550 below for more details.
The comparison test seems broken due to failed OpenSearch address resolving. I made local changes and ran it manually. Need to send separate PR to fix the comparison test framework.
```
$ ./gradlew …
```
> Fix back quoted alias of FROM subquery

- core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
- core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
- integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
* Fix truncate() function
Signed-off-by: Margarit Hakobyan <margarith@bitquilltech.com>
Signed-off-by: Margarit Hakobyan <margarit.hakobyan@improving.com>
Fixes `truncate()` returning incorrect results for some input data issue.
Example of a query result after the proposed fix:
opensearchsql> SELECT ddouble.key, ddouble.val, TRUNCATE(ddouble.val, 1) AS `EXPR$2` FROM ddouble;                                                    
fetched rows / total rows = 20/20
+----------------------------+------------------------+------------------------+
| key                        | val                    | EXPR$2                 |
|----------------------------+------------------------+------------------------|
| null                       | null                   | null                   |
| 001: min …
> Fix truncate() function

- .github/workflows/sql-test-and-build-workflow.yml
The proposed fix suppresses errors from the uploading step. [ref](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error)
Sometimes CI fails to upload test reports and marks that entire workflow had failed.
Example:
https://github.com/Bit-Quill/opensearch-project-sql/actions/runs/3681582096/jobs/6228417004#step:8:19
Seen only in `SQL Java CI`, I guess it is caused by big amount of files and/or big total zip size.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-cer …
> Suppress CI failures not related to testing/building

- MAINTAINERS.md
- sql-cli/MAINTAINERS.md
- sql-jdbc/MAINTAINERS.md
- sql-odbc/MAINTAINERS.md
Coming from https://github.com/opensearch-project/.github/issues/121, updated MAINTAINERS.md to match opensearch-project recommended format.
> Updated MAINTAINERS.md format.

- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/legacy/MethodQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/MatchIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/MatchPhraseIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/MultiMatchIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Adds alternate syntax for the `match_query`, `match_phrase`, and `multi_match` functions.
Example: 
`SELECT * FROM stackexchange_beer WHERE Tags = match_query('taste');`
`SELECT * FROM stackexchange_beer WHERE Tags = match_phrase('taste');`
`SELECT * FROM stackexchange_beer WHERE Tags = multi_match('taste');`
#787 
> Add Alternate Syntax For Match_Query And Other Functions

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Added Testing And Implementation For Second_Of_Minute Function
Signed-off-by: GabeFernandez310 <Gabriel.Fernandez@improving.com>
Adds support for the `second_of_minute` function as an alias for the `second` function which currently exists in opensearch
#722
> Add Second_Of_Minute Function As An Alias Of The Second Function

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Signed-off-by: GabeFernandez310 <Gabriel.Fernandez@improving.com>
Adds support for the `minute_of_hour` function as an alias for the `minute` function which currently exists in opensearch
#722
> Add Minute_Of_Hour Function As An Alias Of Minute Function (#196)

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Adds support for the `day_of_week` function as an alias for the `dayofweek` function which currently exists in opensearch
#722 
> Add Day_Of_Week Function As An Alias Of DayOfWeek

- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Signed-off-by: GabeFernandez310 <Gabriel.Fernandez@improving.com>
Fixes CI build failure occurring in backport
Fixes https://github.com/opensearch-project/sql/pull/1236
https://github.com/opensearch-project/sql/actions/runs/3857798129/jobs/6575599281
> Hot Fix For CI Build

- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/legacy/MethodQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/MatchIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/MatchPhraseIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/MultiMatchIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Backport https://github.com/opensearch-project/sql/commit/b919ba023a48f0d73a58c94a79354b6ffe291384 from https://github.com/opensearch-project/sql/pull/1166. Backport aae57a0bdc995bd53bd88eb812d329761c4333a6 from #1241
> [Backport 2.x] Add Alternate Syntax For Match_Query And Other Functions

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Backport https://github.com/opensearch-project/sql/commit/61e2374eace01945bb8b083c8b19859e5042e228 from https://github.com/opensearch-project/sql/pull/1230. Added imports causing checks to fail.
> [Backport 2.x] Add Minute_Of_Hour Function As An Alias Of Minute Function

- integ-test/build.gradle
Signed-off-by: Andrew Carbonetto <andrewc@bitquilltech.com>
SQLITE is not supported with jdk 11 using sqlite-jdbc version '3.28.0' and can cause connection issues. SQLITE is used in our correctness tests by comparing SQL-Plugin results to H2 and SQLITE output.
See: https://youtrack.jetbrains.com/issue/DBE-12342
Upgrade to '3.32.3.3' should fix this problem.
fixes #1282
> Upgrade sqlite to 3.32.3.3

- .github/workflows/sql-pitest.yml
- .github/workflows/sql-test-and-build-workflow.yml
- .github/workflows/sql-test-workflow.yml
* Move PiTest to a new workflow. Triggerable on demand
* Minor fixes in the build workflow:
* Upload doctest and integtest cluster logs
* Suppress uploading failures
* Keep reports and artifact from all jobs (now CI stores only them from first or last job only)
Make main CI workflow faster.
See #1204 
> Move PiTest to a new workflow.

- integ-test/src/test/java/org/opensearch/sql/legacy/AggregationExpressionIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/AggregationBuilderHelper.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilderTest.java
* Support constant in aggregation.
* Minor fix for aggregation
* Fix and reactivate some aggregation integration tests
Fix query like
```sql
select 1 from <any table> GROUP BY 1
```
Query is pretty useless, but fix is pretty simple though.
> Allow literal in aggregation (#203)

- legacy/src/main/java/org/opensearch/sql/legacy/query/planner/physical/node/join/BlockHashJoin.java
- legacy/src/main/java/org/opensearch/sql/legacy/query/planner/physical/node/scroll/Scroll.java
- legacy/src/test/java/org/opensearch/sql/legacy/unittest/QueryFunctionsTest.java
Changed calls of Strings.toString to match the new signature.
https://github.com/opensearch-project/sql/issues/1308
> Update usage of Strings.toString

- integ-test/src/test/resources/correctness/expressions/date_and_time_functions.txt
Signed-off-by: Matthew Wells <matthew.wells@improving.com>
Wrote correctness tests for date and time functions, some tests were not including due to them failing.
All string functions that have no been included in the test is because they either aren't implemented in OpenSearch, or they aren't implemented in H2 and SQLite. Because of the small number of string functions in SQLite and the fact that all correctness tests need to pass against at least one database all functions are taken from the overlap of functions between OpenSearch and H2. All functions that are implemented in both OpenSearch and H2 that do not pass have their specific reasons for failure mentioned below.
- TIME does not work when adding milliseconds because of a …
> Added Correctness Tests For Date And Time Functions

- plugin/src/test/java/org/opensearch/sql/plugin/datasource/DataSourceMetaDataTest.java
(cherry picked from commit 513428be833d9937860f27206c40f0effbc48a18)
> [Backport 2.x] Fix ArgumentCaptor can't capture varargs (#1320)

- integ-test/src/test/java/org/opensearch/sql/legacy/PluginIT.java
Request:
```
curl -s -XPUT http://localhost:9200/_plugins/_query/settings -H 'Content-Type: application/json' -d '{ "transient" : { "plugins.sql.query.state.city" : 200 }}'
```
Response was changed. Recently it was
```json
{
"error": {
"root_cause": [
{
"type": "illegal_argument_exception",
"reason": "transient setting [plugins.sql.query.state.city], not recognized"
}
],
"type": "illegal_argument_exception",
"reason": "transient setting [plugins.sql.query.state.city], not recognized"
},
"status": 400
}
```
Tonight it was changed to
```json
{
"error": {
"root_cause": [
{
"type": "settings_exception",
"reason": "transient setting [plugins.sql.query.state.city], not recognized"
}
],
"type": "settings_exception",
"reason": …
```
> Fix IT according to OpenSearch changes.

- scripts/integtest.sh
Background:
Integ tests during opensearch version release run on a separate local cluster. For sql integ tests to work properly, we need to setup prometheus datasource configuration in keystore. Since this is a customization specific to sql plugin, infra team advised us to maintain a custom script in sql plugin itself. Build system is intelligent enough to decide on which script to run.
Our custom script is a modification of below script.
Reference integtest.sh: https://github.com/opensearch-project/opensearch-build/blob/main/scripts/default/integtest.sh
For more information on following …
> Create custom integ test file for sql plugin.

- core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
- core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
- integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
Signed-off-by: Guian Gumpac <guian.gumpac@improving.com>
Modified `ln`, `log`, `log10`, and `log2` functions to return `null` when the Math functions return `NaN`.
https://github.com/opensearch-project/sql/issues/1280
> Modified returning NaN to NULL

- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
- docs/user/dql/functions.rst
Adds the support to the `get_format` function to the OpenSearch SQL Plugin for `JIS`, `ISO`, `EUR`, and `INTERNAL` formats for `DATE`, `TIME`, `TIMESTAMP` and `DATETIME`. It's implementation is aligned with the [MySQL Documentation](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_get-format).
#722
> Support More Formats For `GET_FORMAT` Function

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Adds the `last_day` function to the SQL plugin according to [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_last-day). It returns a `DATE` for the last day of the given month based on the input argument.
Examples:
```
opensearchsql> SELECT last_day('2020-02-03');
+--------------------------+
| last_day('2020-02-03')   |
|--------------------------|
| 2020-02-29               |
+--------------------------+
```
```
opensearchsql> SELECT last_day('2021-02-03 10:11:12');
+-----------------------------------+
| last_day('2021-02-03 10:11:12')   |
|-----------------------------------|
| 2021-02-28                        |
+-----------------------------------+
```
#722
By …
> Add `last_day` Function To OpenSearch SQL Plugin

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeFunctionTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
Adds the `WeekOfYear` function to the SQL plugin. It behaves like the `week` function which already exists in the new engine, and both are aligned with [MySQL](https://www.w3schools.com/sql/func_mysql_week.asp). It has been added as an alias.
[722 ](https://github.com/opensearch-project/sql/issues/722)
> Add WeekOfYear Function To OpenSearch

- integ-test/src/test/java/org/opensearch/sql/ppl/PPLPluginIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
`IndexNotFoundException` thrown from OpenSearch get index mapping API is treated as server error. This caused breaking behavior as reported in issue below. More importantly, this may cause false alarm if monitoring logic on SQL plugin.
Due to security concern, we switched from OpenSearch's `ClusterService.getIndexMapping()` to our current `OpenSearchNodeClient.getIndexMapping()`. OpenSearchNodeClient captures every exception thrown from underlying OpenSearch API, including `IndexNotFoundException`, and wrap it by `IllegalStateException`. On the high level, `isClientError()` determines if this is a client error on IllegalStateException instead of the IndexNotFoundException wrapped inside.
1. Capture IndexNotFoundException individually and re-throw it directly to fix the issue
2. Add IT in …
> Fix index not found reported as server error bug

- core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
- core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
- integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
Signed-off-by: Guian Gumpac <guian.gumpac@improving.com>
(cherry picked from commit de40f4284ec428e1d24fc1112cce7fdfb7c1d787) from https://github.com/opensearch-project/sql/pull/1341
> [Backport 2.x] Modified returning NaN to NULL

- release-notes/opensearch-sql.release-notes-2.6.0.0.md
> Add release notes for 2.6.0

- integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java
Many IT failed in 2.6 release test due to no permission to delete system index `.opensearch-observability`. Fixed IT base class to exclude `.opensearch-xxx` index when IT cleanup. Meanwhile as quick fix, ignore exception just in case system index with different naming.
```
Suite: Test class org.opensearch.sql.legacy.AggregationExpressionIT
2> org.opensearch.client.ResponseException: method [DELETE], host [https://localhost:9200], URI [/.opensearch-observability], status line [HTTP/1.1 403 Forbidden]
{"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"}],"type":"security_exception","reason":"no permissions for [] and User [name=admin, backend_roles=[admin], …
```
> Exclude OpenSearch system index when IT cleanup

- .github/workflows/sql-test-and-build-workflow.yml
- .gitignore
- build-tools/sqlplugin-coverage.gradle
- buildSrc/src/main/groovy/com/wiredforcode/spawn/KillProcessTask.groovy
- buildSrc/src/main/groovy/com/wiredforcode/spawn/SpawnProcessTask.groovy
- doctest/build.gradle
- integ-test/build.gradle
- integ-test/src/test/java/org/opensearch/sql/ppl/CsvFormatIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/DescribeCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/CsvFormatIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/RawFormatIT.java
- scripts/integtest.sh
Refactored to skip integ tests with datasources and prometheus in windows platform.
Changes Included:
* Changed release integ tests script to perform datasource creation action only in case of non-windows OS types.
* Changed integ test task to exclude `org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.class`
`org/opensearch/sql/ppl/ShowDataSourcesCommandIT.class`, `org/opensearch/sql/ppl/InformationSchemaCommandIT.class` in case of non-windows OS Types.
* Fixed Integ Tests failures in windows platform due to line separators.
* Added support for windows in SpawnGradleTask and KillGradleTask. This is required for doctests. Even after fixing this doctests are still failing in windows due to bootstrap.sh. We can tackle doctests fix in a separate issue.
[List any issues this PR will …
> Integ Test Refactoring

- plugin/build.gradle
- prometheus/build.gradle
- prometheus/src/main/java/org/opensearch/sql/prometheus/authinterceptors/AwsSigningInterceptor.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/authinterceptors/AwsSigningInterceptorTest.java
Refactored sigv4auth support to use credential Providers. 
> Refactor AWSSigV4 auth to support different AWSCredentialProviders

- .github/workflows/maven-publish.yml
Typo fix in `maven-publish` GHA workflow - branch list has to be a comma-separate list or list of entries.
I also updated `aws-actions/configure-aws-credentials` used to avoid coming deprecation and disabled this workflow to run on forks.
#1358, #1359
> Typo fix and minor improvement in `maven-publish` GHA workflow.

- .gitignore
- core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
- core/src/main/java/org/opensearch/sql/datasource/DataSourceMetadataStorage.java
- core/src/main/java/org/opensearch/sql/datasource/DataSourceService.java
- core/src/main/java/org/opensearch/sql/datasource/DataSourceServiceImpl.java
- core/src/main/java/org/opensearch/sql/datasource/model/DataSourceMetadata.java
- core/src/main/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScan.java
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
- core/src/test/java/org/opensearch/sql/datasource/DataSourceServiceImplTest.java
- core/src/test/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScanTest.java
- integ-test/src/test/java/org/opensearch/sql/ppl/StandaloneIT.java
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
- plugin/src/test/java/org/opensearch/sql/plugin/datasource/DataSourceMetaDataTest.java
* **Datasource** : Datasource class holds basic datasource info(name, connector), storage engine and other objects created specific to a datasource.
* **DatasourceMetadata**:  DatasourceMetadata class carries all the metadata required for a datasource.
* **DatasourceService**: This class acts as interface for datasources and datasource metadata management.
* **DatasourceMetadataStorageService**: This class acts as interface for datasource metadata storage.
* CRUD APIs for datasources.
* Analyzer class
* Fully Qualified Name Resolution requires names of all datasources. [Queries GetAllDatasourceMetadata]
* DataSourceTable class requires metadata(name, connector) of all datasources for show datasources command. [Queries GetAllDatasourceMetadata]
* Requires storage engine to implement and …
> [main]Changes in DataSourceService and DataSourceMetadataStorage interface

- .github/workflows/backport.yml
Backport often fails last time, even if there are no merge conflicts. I hope updating the workflow would fix this.
@VachaShah, could you please describe what was fixed?
Failed ports:
https://github.com/opensearch-project/sql/pull/839#issuecomment-1299300328
https://github.com/opensearch-project/sql/pull/716#issuecomment-1213323984
https://github.com/opensearch-project/sql/pull/745#issuecomment-1213351676
https://github.com/opensearch-project/sql/pull/747#issuecomment-1213364601
https://github.com/opensearch-project/sql/pull/748#issuecomment-1218213039
...
For more information on following Developer Certificate of Origin …
> Bump backport version.

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
- core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
Updated SINH function to V2 engine, added documentation, unit/IT tests
> Added SINH function to V2 engine

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
- core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
Added math function RINT to V2 engine, updated documentation, and added unit/IT tests. Additionally fixed small typo in the EXPM1 description 
> Added RINT function to V2 engine 

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/YearweekTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
The `yearweek(date [, mode])` function accepts a first argument representing a date, and an optional second argument containing a mode. It extract the **year** and **week of the year** from the input argument, and formats it as an integer which is returned. If an argument of type `TIME` is provided, the current date is used. The mode argument defines a set of rules to decide how to parse the **year** and **week of the year** and are based on [MySQL](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_yearweek).
Example:
```
opensearchsql> SELECT YEARWEEK('2020-08-26');
+--------------------------+
| YEARWEEK('2020-08-26')   |
|--------------------------|
| 202034                   |
+--------------------------+
```
``` …
```
> Add `YEARWEEK` Function To OpenSearch SQL

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/YearweekTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Manually backport 03e4f97b4f41074d9bf79584a36a56bf90ee221c from #1417 
> [Backport 2.x] Add `YEARWEEK` Function To OpenSearch SQL

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/ExtractTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Manually backport [87018c6](https://github.com/opensearch-project/sql/commit/87018c654ed648615984071203fa9016d4c414f5) from #1421 
> [Backport 2.x] Add `EXTRACT` Function To OpenSearch SQL Plugin

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFormatterUtil.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/StrToDateTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Manually backport [40336d4](https://github.com/opensearch-project/sql/commit/40336d4dd38bbd015564e03e4b16429b59c6412f) from https://github.com/opensearch-project/sql/pull/1420
> [Backport 2.x] Add `STR_TO_DATE` Function To The SQL Plugin

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/main/java/org/opensearch/sql/utils/DateTimeFormatters.java
- core/src/test/java/org/opensearch/sql/expression/datetime/ToSecondsTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
Manually backport d38a6ec20d1ddc035adf53f610af05cfad812b6a FROM #1419.
> [Backport 2.x] Add The `TO_SECONDS` Function To The SQL Plugin

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/main/java/org/opensearch/sql/expression/function/FunctionDSL.java
- core/src/main/java/org/opensearch/sql/expression/function/SerializableQuadFunction.java
- core/src/test/java/org/opensearch/sql/expression/datetime/TimeStampAddTest.java
- core/src/test/java/org/opensearch/sql/expression/function/FunctionDSLTestBase.java
- core/src/test/java/org/opensearch/sql/expression/function/FunctionDSLimplFourArgTest.java
- core/src/test/java/org/opensearch/sql/expression/function/FunctionDSLimplWithPropertiesThreeArgsTest.java
- core/src/test/java/org/opensearch/sql/expression/function/FunctionDSLnullMissingHandlingTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Adds the `timestampadd()` function to the OpenSearch SQL Plugin. Based off of the [MySQL Implementation](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_timestampadd), but some changes were made due to the limitations of the plugin. Specifically, the return of this function is always a `DATETIME`. If an argument of type `TIME` is provided for the third argument, the `DATE` portion of the returned `DATETIME` will be filled in with values using the current date.
Examples:
```
opensearchsql> SELECT TIMESTAMPADD(MINUTE, 1, '2003-01-02 00:00:00');
+--------------------------------------------------+
| TIMESTAMPADD(MINUTE, 1, '2003-01-02 00:00:00')   |
|--------------------------------------------------|
| 2003-01-02 00:01:00 …
```
> Add `TIMESTAMPADD` Function To OpenSearch SQL Plugin

- core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
- core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
- integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
Changed implementation of pow and power such that when an invalid response would be returned from having a negative base and a floating point exponent it returns null instead of crashing.
In addition I also added integration testing which was previously missing.
> Fix null response from pow/power and added missing integration testing

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/datetime/TimeStampDiffTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Add the `timestampdiff` function to the SQL plugin. The function takes an argument for the unit of time used to measure the difference between the second argument (start time) and third argument (end time). The units allowed for the first argument are the same as those allowed for the `timestampadd` [function and are also aligned with MySQL]( https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_timestampadd:~:text=MICROSECOND%20(microseconds)%2C%20SECOND%2C%20MINUTE%2C%20HOUR%2C%20DAY%2C%20WEEK%2C%20MONTH%2C%20QUARTER%2C%20or%20YEAR.).
Example:
```
opensearchsql> SELECT TIMESTAMPDIFF(YEAR, '1997-01-01 00:00:00', '2001-03-06 00:00:00'), TIMESTAMPDIFF(SECOND, time('00:00:23'), time('00:00:00')); …
```
> Add `Timestampdiff` Function To OpenSearch SQL

- common/src/test/java/org/opensearch/sql/common/grok/BasicTest.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- docs/user/dql/functions.rst
- docs/user/ppl/functions/datetime.rst
- integ-test/src/test/java/org/opensearch/sql/legacy/MethodQueryIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/domain/Condition.java
- legacy/src/main/java/org/opensearch/sql/legacy/domain/Field.java
- legacy/src/main/java/org/opensearch/sql/legacy/domain/MethodField.java
- legacy/src/main/java/org/opensearch/sql/legacy/domain/Order.java
- legacy/src/main/java/org/opensearch/sql/legacy/domain/SearchResult.java
- legacy/src/main/java/org/opensearch/sql/legacy/domain/Select.java
- legacy/src/main/java/org/opensearch/sql/legacy/esdomain/mapping/FieldMappings.java
- legacy/src/main/java/org/opensearch/sql/legacy/parser/FieldMaker.java
- legacy/src/main/java/org/opensearch/sql/legacy/query/maker/AggMaker.java
- legacy/src/main/java/org/opensearch/sql/legacy/query/maker/Maker.java
- legacy/src/main/java/org/opensearch/sql/legacy/query/maker/QueryMaker.java
Replace non-ASCII characters in code and docs.
Characters left:
```
DEVELOPER_GUIDE.rst:132:   │   ├── attributions.md
DEVELOPER_GUIDE.rst:133:   │   ├── category.json
DEVELOPER_GUIDE.rst:134:   │   ├── dev
DEVELOPER_GUIDE.rst:135:   │   └── user
```
and `°` (temperature degree symbol) in IT sample data:
```
integ-test/src/test/resources/beer.stackexchange.json:26
integ-test/src/test/resources/beer.stackexchange.json:60
```
**UPD**
Removed all non-English comments from legacy engine
Fixes #1364
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTI …
> Replace non-ASCII characters in code and docs.

- .github/workflows/link-checker.yml
- .github/workflows/maven-publish.yml
- plugin/build.gradle
Backporting https://github.com/opensearch-project/sql/pull/1359 to 2.x
Local testing output
```
maharup@b0f1d879dff7 plugin % find snapshots | sort 
snapshots
snapshots/org
snapshots/org/opensearch
snapshots/org/opensearch/plugin
snapshots/org/opensearch/plugin/opensearch-sql-plugin
snapshots/org/opensearch/plugin/opensearch-sql-plugin/2.7.0.0-SNAPSHOT
snapshots/org/opensearch/plugin/opensearch-sql-plugin/2.7.0.0-SNAPSHOT/maven-metadata.xml
snapshots/org/opensearch/plugin/opensearch-sql-plugin/2.7.0.0-SNAPSHOT/maven-metadata.xml.md5
snapshots/org/opensearch/plugin/opensearch-sql-plugin/2.7.0.0-SNAPSHOT/maven-metadata.xml.sha1
snapshots/org/opensearch/plugin/opensearch-sql-plugin/2.7.0.0-SNAPSHOT/maven-metadata.xml.sha256
snapshots/org/opensearch/plugin/opensearch-sql-plugin/2.7.0.0-SNAPSHO …
```
> [Backport 2.x] Add publish snapshots to maven via GHA

- core/src/main/java/org/opensearch/sql/datasource/DataSourceLoaderCache.java
- core/src/main/java/org/opensearch/sql/datasource/DataSourceLoaderCacheImpl.java
- core/src/main/java/org/opensearch/sql/datasource/DataSourceService.java
- core/src/main/java/org/opensearch/sql/datasource/DataSourceServiceImpl.java
- core/src/main/java/org/opensearch/sql/datasource/exceptions/DataSourceNotFoundException.java
- core/src/main/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScan.java
- core/src/main/java/org/opensearch/sql/storage/DataSourceFactory.java
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
- core/src/test/java/org/opensearch/sql/datasource/DataSourceLoaderCacheImplTest.java
- core/src/test/java/org/opensearch/sql/datasource/DataSourceServiceImplTest.java
- core/src/test/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScanTest.java
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
- plugin/src/main/java/org/opensearch/sql/plugin/datasource/OpenSearchDataSourceMetadataStorage.java
- plugin/src/main/java/org/opensearch/sql/plugin/model/DeleteDataSourceActionRequest.java
- plugin/src/main/java/org/opensearch/sql/plugin/model/DeleteDataSourceActionResponse.java
- plugin/src/main/java/org/opensearch/sql/plugin/model/GetDataSourceActionRequest.java
- plugin/src/main/java/org/opensearch/sql/plugin/model/GetDataSourceActionResponse.java
- plugin/src/main/java/org/opensearch/sql/plugin/model/UpdateDataSourceActionRequest.java
- plugin/src/main/java/org/opensearch/sql/plugin/model/UpdateDataSourceActionResponse.java
- plugin/src/main/java/org/opensearch/sql/plugin/rest/RestDataSourceQueryAction.java
- plugin/src/main/java/org/opensearch/sql/plugin/transport/datasource/TransportCreateDataSourceAction.java
- plugin/src/main/java/org/opensearch/sql/plugin/transport/datasource/TransportDeleteDataSourceAction.java
- plugin/src/main/java/org/opensearch/sql/plugin/transport/datasource/TransportGetDataSourceAction.java
- plugin/src/main/java/org/opensearch/sql/plugin/transport/datasource/TransportUpdateDataSourceAction.java
- plugin/src/test/java/org/opensearch/sql/plugin/datasource/OpenSearchDataSourceMetadataStorageTest.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java
These changes introduce REST APIs for GET DATASOURCE, UPDATE DATASOURCE and DELETE DATASOURCE APIS as follow up to CREATE DATASOURCE APIs https://github.com/opensearch-project/sql/pull/1458 
* https://github.com/opensearch-project/sql/issues/1462
* https://github.com/opensearch-project/sql/issues/1461
* https://github.com/opensearch-project/sql/issues/1460
Modification of datasource is similar to create apis. Below images corresponds to GET ALL and DELETE APIs.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-ori …
> REST API for GET,PUT and DELETE

- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
Fix build for https://github.com/opensearch-project/sql/pull/1509 
https://github.com/opensearch-project/sql/pull/1509
> Fix AstExpressionBuilder.java in 2.7 for backport 1456 to 2.7

- integ-test/build.gradle
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/ShowDataSourcesCommandIT.java
* with the current state, integ-state fails when cluster restricts actions on system index .ql-datasources.
* In order to avoid this, moved populating datasources using APIs instead of loading data directly in .ql-datasources.
https://github.com/opensearch-project/sql/issues/1538
> Datasources Integ Test Fix

- core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
- integ-test/src/test/java/org/opensearch/sql/sql/NestedIT.java
- sql/src/main/java/org/opensearch/sql/sql/parser/AstSortBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
Fallback to legacy engine when the nested function is used in the `WHERE`, `GROUP BY`, `ORDER BY`, and `HAVING` clauses. Support has not been added to the V2 engine for the nested query in these clauses.
[1548](https://github.com/opensearch-project/sql/issues/1548)
> Ensure Nested Function Falls Back to Legacy Engine Where Not Supported

- ppl/build.gradle
> adding reflections as a dependency

- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
- core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
Backporting https://github.com/opensearch-project/sql/pull/1428 to 2.x
> [Backport 2.x] Added COSH to V2 engine

- legacy/src/main/java/org/opensearch/sql/legacy/esdomain/mapping/IndexMappings.java
- legacy/src/main/java/org/opensearch/sql/legacy/esdomain/mapping/Mappings.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/format/DescribeResultSet.java
- legacy/src/test/java/org/opensearch/sql/legacy/util/CheckScriptContents.java
- legacy/src/test/java/org/opensearch/sql/legacy/util/MultipleIndexClusterUtils.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
Fix failing build due to upstream refactor.
https://github.com/opensearch-project/sql/issues/1570
> Update SQL plugin to resolve build failures

- integ-test/src/test/java/org/opensearch/sql/legacy/AggregationIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/NestedFieldQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SubqueryIT.java
- integ-test/src/test/java/org/opensearch/sql/util/MatcherUtils.java
- legacy/build.gradle
- legacy/src/main/java/org/opensearch/sql/legacy/expression/model/ExprValueFactory.java
- opensearch/build.gradle
- ppl/build.gradle
- prometheus/build.gradle
- sql/build.gradle
1. Bumped `org.json` version in all submodules for CVE fix
2. Fixed failed UT and IT assertion due to breaking changes in https://github.com/stleary/JSON-java/issues/441 (more details below)
`org.json` use BigDecimal to interpret floating point text in JSON. This caused the return value of `JSONObject/JSONArray.get() and query()` get changed from double to BigDecimal class.
Minor changes I noticed in our response format which seems an improvement:
Previously:
```
POST _plugins/_sql
{
"query": "SELECT 123.0"
}
{
"schema": [
{
"name": "123.0",
"type": "double"
}
],
"datarows": [
[
123  <-- the decimal part was missing
]
],
"total": 1,
"size": 1,
"status": 200
}
```
Now:
```
curl -XPOST 'http://localhost:9200/_plugins/_sql' \
--header 'Content-Type: application/json' \
--data '{
"query": …
```
> Bump org.json dependency version

- integ-test/src/test/java/org/opensearch/sql/legacy/AggregationIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/NestedFieldQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SubqueryIT.java
- integ-test/src/test/java/org/opensearch/sql/util/MatcherUtils.java
- legacy/build.gradle
- legacy/src/main/java/org/opensearch/sql/legacy/expression/model/ExprValueFactory.java
- opensearch/build.gradle
- ppl/build.gradle
- prometheus/build.gradle
- sql/build.gradle
Cherry pick https://github.com/opensearch-project/sql/pull/1586 because auto backport PR failed.
> Bump org.json dependency version (#1586)

- integ-test/build.gradle
(cherry picked from commit 34be98d24a36ffce9e70c2e5c436045babe4dc37)
> [Backport 1.3] CVE-2022-45868 fix (#1107)

- sql-jdbc/build.gradle
- sql-jdbc/src/test/java/org/opensearch/jdbc/test/TLSServer.java
- sql-jdbc/src/test/java/org/opensearch/jdbc/transport/http/auth/aws/AWSRequestSigningApacheInterceptorTests.java
Update `httpclient`, `aws-java-sdk-core`, `wiremock`, `jetty-server`, `guava`
Patch the following CVE:
* CVE-2018-12536
* CVE-2019-10241
* CVE-2019-10246
* CVE-2019-10247
* CVE-2019-10426
* CVE-2020-13956
* CVE-2020-28491
* CVE-2021-34428
* CVE-2022-2047
* CVE-2023-26048
> Update dependencies to patch CVE

- build.gradle
- config/checkstyle/google_checks.xml
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
- core/src/test/java/org/opensearch/sql/planner/logical/LogicalPlanNodeVisitorTest.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/core/ExpressionScript.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtectorTest.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/Format.java
- sql-jdbc/build.gradle
Patched CVE's
* CVE-2019-10782
* CVE-2020-8908
* CVE-2023-1370
* CVE-2023-20861
* CVE-2023-20863
* CVE-2023-24998
* CVE-2023-26048 (*)
* CVE-2023-26049 (*)
(\*) This requires the use of `jetty-server@11.0.14` instead of `jetty-server@11.0.12`
However, the latest version of `wiremock@3.0.0-beta-8` still uses `jetty-server@11.0.12`
Wiremock is used in testing only. We can probably exempt these CVE's *after* we make sure that wiremock is the only source of these CVE's.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/ …
> Patch 1.3 MED+ CVE's

- .github/CODEOWNERS
- MAINTAINERS.md
Backport #1384, #1466 #1579 to 2.x.
#1337
> Backport codeowners changes to 2.x

- docs/user/ppl/admin/cross_cluster_search.rst
Backport d0b6b3a738c3f87c6bf8b4f90dd482d13b5d6bcc from #1610 
> [Backport 2.x] Update usage example doc for PPL cross-cluster search (#1610)

- flint/build.sbt
- flint/flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
- flint/flint-core/src/main/scala/org/opensearch/flint/core/FlintIndex.scala
- flint/flint-core/src/main/scala/org/opensearch/flint/core/metadata/FlintMetadata.java
- flint/flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
- flint/integ-test/src/test/scala/org/opensearch/flint/OpenSearchSuite.scala
- flint/integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
1. Add `FlintClient` interface with basic Flint index management API
2. Add OpenSearch implementation for the client
3. Copy and remove Spark dependency in `OpenSearchSuite` (will discuss with @penghuo if we want to move all IT stuff from `flint-spark-integration` to `integ-test` module)
Please see detailed design in https://github.com/opensearch-project/sql/issues/1602 and read on below for more details. Later I will convert everything into individual doc in future PR.
**Note that Flint spec is subject to change during development and thus `FlintMetadata` stores everything in Map. Will change this to strong type once finalized.**
Flint metadata sample:
```
{
"version": "0.1",
"indexConfig": {
"kind": "SkippingIndex",
"indexedColumns": ...
}
},
"source": "alb_logs", …
```
> Add Flint client and index management API

- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionReaderFactory.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintScan.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintScanBuilder.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/storage/FlintQueryCompiler.scala
- flint/flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/storage/FlintQueryCompilerSuit.scala
- flint/flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/storage/FlintQueryCompilerSuite.scala
- flint/integ-test/src/test/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala
> add filter push down

- docs/dev/index.md
- docs/dev/sql-nested-function-select-clause.md
- docs/dev/sql-nested-function.md
Added documentation for architectural changes from [PR-1490](https://github.com/opensearch-project/sql/pull/1490). The added features covers the `nested` function used in the `SELECT` clause of an SQL statement. Future work has placeholders in documentation and can be added to with proposals as development continues. 
> Add Nested Documentation for 2.7 Related Features

- .github/CODEOWNERS
- MAINTAINERS.md
Backport #1648, #1609 and #1614
> [Backport 2.x] Maintainer list update

- docs/dev/index.md
- docs/dev/sql-nested-function-select-clause.md
- docs/dev/sql-nested-function.md
(cherry picked from commit [83ad16603337208f4ee1edd623d94034dfd7ccb7](https://github.com/opensearch-project/sql/commit/83ad16603337208f4ee1edd623d94034dfd7ccb7)
Backport from [1620](https://github.com/opensearch-project/sql/pull/1620)
> Backport/backport 1620 to 2.x

- docs/dev/Pagination-v2.md
This updates accounts for the following:
1. Merge of `OpenSearchIndexScan` and `OpenSearchPagedIndexScan`, related builder classes and changes to logical plan optimization.
2. Removal of `ContinuePaginatedPlan` and how initial and subsequent paged requests are expressed in logical query plan.
3. Changes to `OpenSearchIndexScan` and `OpenSearchScrollRequest` necessary to support pagination.
> Document pagination design changes based on review feedback

- flint/flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
- flint/flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
- flint/flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
- flint/flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintWriter.java
- flint/flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchWriter.java
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionWriter.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionWriterFactory.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintTable.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintWrite.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintWriteBuilder.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/json/FlintJacksonGenerator.scala
- flint/integ-test/src/test/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala
- flint/integ-test/src/test/scala/org/opensearch/flint/OpenSearchSuite.scala
- flint/integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
1. Add FlintWriter in Flint core.
2. Support Batch Write in Spark.
`FlintTable` is capable of batch write operations in overwrite mode. This interacts with the `FlintOpenSearchClient` within the FlintCore package. During this process, we utilize the `CREATE` action within the OpenSearch bulk request. Users have the capability to provide an ID field within their options. If no ID is provided, OpenSearch will generate one automatically. When writing to FlintCore, the following conditions are checked:
If a document with the same ID already exists, the system will skip this entry and do nothing.
If no document with the same ID is found, the system will index the new document.
The INDEX action will delete doc with same id, and index new doc. In case Luncene does not really delete the doc, the …
> Support FlintTable batch write

- integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java
IT fails on 2.x branch (can't compile)
```
2023-05-25T18:49:40.0119575Z /home/runner/work/sql/sql/integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java:36: error: package org.opensearch.core.internal.io does not exist
2023-05-25T18:49:40.0120005Z 
2023-05-25T18:49:40.0120688Z import org.opensearch.core.internal.io.IOUtils;
```
caused by https://github.com/opensearch-project/OpenSearch/pull/7612
Fortunately, it is a simple fix.
on `main` it was fixed in scope of #1512, but this specific fix wasn't backported.
Fix CI on 2.x …
> Fix IT on 2.x - address breaking changes from upstream.

- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionWriter.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionWriterFactory.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintTable.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintWrite.scala
- flint/integ-test/src/test/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala
1. Add Streaming write support for FlintTable. As Streaming Sink, FlintWriter depend on _id field in DataFrame to achieve idempotent. It is should fine for now. We will revist it if sink commit id is required.
> Add Streaming write support

- docs/user/ppl/interfaces/protocol.rst
Fixes error in `protocol.rst` test.
**Old:**
```
"error": {
"reason": "Error occurred in OpenSearch engine: no such index [unknown]",
"details": "org.opensearch.index.IndexNotFoundException: no such index [unknown]\nFor more details, please send request for Json format to see the raw response from OpenSearch engine.",
"type": "IndexNotFoundException"
```
**New:**
```
"error": {
"reason": "Error occurred in OpenSearch engine: no such index [unknown]",
"details": "[unknown] IndexNotFoundException[no such index [unknown]]\nFor more details, please send request for Json format to see the raw response from OpenSearch engine.",
"type": "IndexNotFoundException"
```
For more …
> Doctest fix in protocol

- flint/docs/index.md
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingStrategy.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/partition/PartitionSkippingStrategy.scala
- flint/flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala
- flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSuite.scala
Please see more details in changes in doc: https://github.com/dai-chen/sql-1/blob/add-partion-index-building/flint/docs/index.md
Update metadata with more info (index kind, column name and type). In this way, `FlintSparkSkippingIndex` can be deserialized out of `_meta` JSON.
Add `refreshIndex` API with `FULL` (batch) and `INCREMENTAL` (streaming) mode.
Followed the first approach below for now. Need to evaluate the performance later.
- Approach 1: treat partition columns as normal and use `FIRST_VALUE` function to aggregate
- Approach 2: treat partition columns as special and add partition columns to `GROUP BY`
```
scala> spark.sql("select first_value(year, true) as year, first_value(month, true) as month, first_value(day, true), first_value(hour, true), input_file_name() from alb_logs …
```
> Add refresh index API for partition skipping index

- integ-test/build.gradle
The 2.8.0 snapshot is ready not. https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/opensearch-sql-plugin/2.8.0.0-SNAPSHOT/
Bump BWC test version to 2.8.0. 
N/A
> Bump BWC test version to 2.8

- docs/dev/index.md
- docs/dev/sql-nested-function-where-clause.md
Add documentation for `nested` function use in `WHERE` clause of an SQL statement. Document covers two syntax options brought forward from legacy engine. Work on implementation is WIP but should align with this added documentation.
Syntax Options:
- `nested(path, condition)`
- `nested(field, field | path) OPERATOR LITERAL`
> Documentation Proposal for `Nested` Function in WHERE Clause

- core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/NestedIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilder.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LikeQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LuceneQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/NestedQuery.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilderTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
- sql/src/main/java/org/opensearch/sql/sql/parser/AstBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
Syntax: `nested( [field] | [field,path] )`
Add support for use of the nested function in the `WHERE` clause as a predicate expression. Supports `nested` function on left of operator, and literal on right. When using `nested` function in `WHERE` clause, the inner hits of the query are not added to the `nested` query DSL. To do this you must use the `nested` function in conjunction with a `SELECT` clause nested function call. See documentation for this nested implementation [HERE (WIP)](https://github.com/opensearch-project/sql/pull/1640). 
`SELECT message.info FROM nested_objects WHERE nested(message.info, message) = 'a';`
`SELECT nested(message.info) FROM nested_objects WHERE nested(message.info, message) = 'a';`
`SELECT message.info FROM nested_objects WHERE nested(message.info) = 'a' OR …
> Add Support for Nested Function Use In WHERE Clause Predicate Expresion

- legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlAction.java
- sql/src/main/java/org/opensearch/sql/sql/antlr/AnonymizerListener.java
- sql/src/main/java/org/opensearch/sql/sql/antlr/SQLSyntaxParser.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AnonymizerListenerTest.java
Created a new listener for the SQLSyntaxParser to anonymize all queries going through the new engine, calling the old anonymizer only if the query falls back to the legacy engine.
Through the update of the anonymizer there are a few differences between between the current and old anonymization including:
- Dots are used to access elements of a table, e.g. `identifier.identifier` instead of simplifying as just `identifier`
- All functions are capitalized
- Adds a space between all nodes except for before and after a dot, before a comma, and between compound comparison symbols (<=, >=, <>, !=)
- Includes the negative symbol when anonymizing numbers, e.g. `number / - number` instead `number / number`
https://github.com/opensearch-project/sql/issues/821
By submitting this pull request, I …
> Create new anonymizer for new engine

- flint/docs/index.md
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionReader.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionReaderFactory.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionWriter.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintTable.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintWrite.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintWriteBuilder.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/json/FlintJacksonParser.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/storage/FlintQueryCompiler.scala
- flint/flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
- flint/integ-test/src/test/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala
> add flint date type support

- core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/ArithmeticFunction.java
- core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/ArithmeticFunctionTest.java
Previously there was no handling of a 0 denominator for byte and short in the divide and modulus arithmetic operators, I have fixed that and updated it's testing.
https://github.com/opensearch-project/sql/issues/1582
> Fixed bug of byte/short not handling 0 denominator in divide/modulus equations

- core/src/main/java/org/opensearch/sql/ast/expression/Cast.java
- core/src/main/java/org/opensearch/sql/executor/pagination/CanPaginateVisitor.java
- core/src/test/java/org/opensearch/sql/executor/pagination/CanPaginateVisitorTest.java
- integ-test/src/test/java/org/opensearch/sql/legacy/CursorIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/LegacyAPICompatibilityIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/PaginationFallbackIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/PaginationFilterIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/PaginationIT.java
- integ-test/src/test/java/org/opensearch/sql/util/TestUtils.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequest.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequestTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchDefaultImplementorTest.java
Pagination in V2: Phase 2. See Phase 1 in #1497.
Doc: https://github.com/Bit-Quill/opensearch-project-sql/blob/61767f2b200b2a7f8c8b2df32de209b3c30caa61/docs/dev/Pagination-v2.md
```
curl -XPOST http://localhost:9200/_plugins/_sql -H 'Content-Type: application/json' -d '{"query": "select highlight(\"Body\") from beer.stackexchange where simple_query_string([\"Tags\" ^ 1.5, \"Title\", \"Body\" 4.2], \"taste\") and Tags like \"% % %\" and Title like \"%\";", "fetch_size": 20 }'
```
You can use attached script for testing as well. Command line: `./cursor_test.sh <table> <page size>`. Requires `jq`. Rename the script before use.
[cursor_test.sh.txt](https://github.com/opensearch-project/sql/files/11166838/cursor_test.sh.txt)
```
./cursor_test.sh 'SELECT date0, DATE_ADD(CAST(date0 AS date), …
```
> Pagination Phase 2: Support `WHERE` clause, column list in `SELECT` clause and for functions and expressions in the query.

- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanBuilder.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanOptimizationTest.java
Refactoring OpenSearchIndexScanBuilder to address [feedback](https://github.com/opensearch-project/sql/pull/1666#discussion_r1210770635) from pagination PR.
> Simplify OpenSearchIndexScanBuilder (#275)

- docs/user/ppl/admin/prometheus_connector.rst
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
- ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/functions/response/DefaultQueryRangeFunctionResponseHandle.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/functions/response/QueryRangeFunctionResponseHandle.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/functions/scan/QueryRangeFunctionTableScanBuilder.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/functions/scan/QueryRangeFunctionTableScanOperator.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/response/PrometheusResponse.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTable.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/functions/scan/QueryRangeFunctionTableScanBuilderTest.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/functions/scan/QueryRangeFunctionTableScanOperatorTest.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTableTest.java
Enable Table function and promQL function. This also enables to build spark sql function.
https://github.com/opensearch-project/sql/issues/1019
> Enable Table Function and PromQL function

- core/src/main/java/org/opensearch/sql/executor/pagination/CanPaginateVisitor.java
- core/src/main/java/org/opensearch/sql/planner/DefaultImplementor.java
- core/src/test/java/org/opensearch/sql/executor/pagination/CanPaginateVisitorTest.java
- core/src/test/java/org/opensearch/sql/planner/DefaultImplementorTest.java
- core/src/test/java/org/opensearch/sql/planner/physical/PhysicalPlanTestBase.java
- integ-test/src/test/java/org/opensearch/sql/sql/PaginationFallbackIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/PaginationIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequestTest.java
Pagination in V2: Phase 2. See Phase 1 in #1497.
Doc: https://github.com/Bit-Quill/opensearch-project-sql/blob/61767f2b200b2a7f8c8b2df32de209b3c30caa61/docs/dev/Pagination-v2.md
This PR depends on #1500.
```
curl -XPOST http://localhost:9200/_plugins/_sql -H 'Content-Type: application/json' -d '{"query": "select * from calcs order by int0, num1;", "fetch_size": 3 }'
```
You can use attached script for testing as well. Command line: `./cursor_test.sh <table> <page size>`. Requires `jq`. Rename the script before use.
[cursor_test.sh.txt](https://github.com/opensearch-project/sql/files/11166838/cursor_test.sh.txt)
Add support for more complex queries in paged requests.
Supported things:
- `GROUP BY` clause
- queries without `FROM` clause
Unsupported things:
- expressions in `GROUP BY` - …
> Pagination Phase 2: Support `ORDER BY` clauses and queries without `FROM`.

- flint/docs/index.md
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionReader.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionWriter.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintConfig.scala
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkOptimizer.scala
- flint/flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala
- flint/flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
- flint/integ-test/src/test/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala
- flint/integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
improve the FlintSparkConf to support the following use cases.
- storage options, user provide options in DF
- `write.refresh_policy`
- flint spark configuration, user set using spark.conf.set(). there are two set of configs
- `spark.flint.xxx.yyy`, for example, `spark.flint.optimizer.enabled`
- `spark.datasource.flint.xxx.yyy` , for example, `spark.datasource.flint.write.refresh_policy`
- sql configuration, generic configuration defined by spark
- `spark.sql.session.timeZone` …
> enhance flint spark configuration

- datasources/src/main/java/org/opensearch/sql/datasources/exceptions/ErrorMessage.java
- datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
Currently all the security exceptions related to datasource APIs are thrown as internal server errors.
With this change, the error message will respect the status received from upstream core service/plugins.
> Improved error codes in case of security exception

- doctest/build.gradle
Stop Prometheus was not running in doctest in cases of some run errors causing Prometheus to keep running after build is stopped. This will cause failure upon next attempt of startPrometheus due to the existing Prometheus running on localhost:9090.
Steps to reproduce error that is fixed.
1. Run an OpenSearch instance
2. Run build in OpenSearch SQL
3. Observe that OpenSearch SQL crashes due to step 1
4. Stop OpenSearch instance started in step 1
5. Re-run build for OpenSearch SQL
6. Observe that there is error about Prometheus already running.
Same steps can be taken working from this PR branch and it will not show the error in step 6.
[1083](https://github.com/opensearch-project/sql/issues/1083) 
By submitting this pull request, I confirm that my contribution is made under the terms of …
> Stop prometheus in doctest build.gradle now runs upon project failure in startOpenSearch

- build.gradle
- integ-test/build.gradle
- plugin/build.gradle
Update guava for CVE fix.
[1767](https://github.com/opensearch-project/sql/issues/1767)
> Fixing CVE 1767

- integ-test/build.gradle
- integ-test/src/test/java/org/opensearch/sql/correctness/runner/resultset/DBResult.java
CVE is [here](https://www.mend.io/vulnerability-database/CVE-2023-32697).
This CVE does not affect deployments of sql plugin because only integration tests use `sqlite-jdbc`.
https://github.com/opensearch-project/sql/issues/1669
> Update sqlite-jdbc to 3.41.2.2 to address CVE-2023-32697

- integ-test/src/test/java/org/opensearch/sql/legacy/ObjectFieldSelectIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/NestedIT.java
- integ-test/src/test/resources/indexDefinitions/nested_simple_index_mapping.json
- integ-test/src/test/resources/nested_simple.json
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/Content.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/ObjectContent.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/OpenSearchJsonContent.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/response/OpenSearchResponse.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/core/ExpressionScript.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/response/OpenSearchResponseTest.java
With the addition of the nested function support in the V2 engine the `inner_hits` portion of the OS response needs to  be parsed for OS types. Previously arrays were not entirely parsed due to lack of support.
Parsing of each value in arrays needs to be supported for proper `nested` functionality. The following gives examples of the current response formats when parsing arrays.
***
Dataset:
`"obj": [{"key": "val1"}, {"key": "val2"}]`
SQL Query:
```sql
SELECT obj FROM objects;
```
V1 Engine Response:
`[{'key': 'val1'},{'key': 'val2'}]`
V2 Engine Response:
`{'key': 'val1'}`
***
Dataset:
`"obj": [{"key": "val1"}, {"key": "val2"}]`
SQL Query:
```sql
SELECT obj FROM nested_objects;
```
V1 and V2 Engine Response:
`[{'key': 'val1'},{'key': 'val2'}]`
***
Dataset:
`"obj": ["val1", "val2"]`
SQL …
> Support Array and ExprValue Parsing With Inner Hits

- core/src/main/java/org/opensearch/sql/analysis/NestedAnalyzer.java
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/NestedIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanBuilder.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LuceneQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/sort/SortQueryBuilder.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanOptimizationTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/sort/SortQueryBuilderTest.java
- sql/src/main/java/org/opensearch/sql/sql/parser/AstSortBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
Add support for nested function use in the `ORDER BY` clause.
```sql
SELECT nested(message.info) from nested_objects ORDER BY nested(message.info);
```
Portion of Issue: [1111](https://github.com/opensearch-project/sql/issues/1111)
Note this does not resolve issue [1777](https://github.com/opensearch-project/sql/issues/1788) but only bring V2 engine to parity with V1 engine.
> Add Support for Nested Function in Order By Clause

- integ-test/build.gradle
- integ-test/src/test/java/org/opensearch/sql/correctness/runner/resultset/DBResult.java
- legacy/src/main/java/org/opensearch/sql/legacy/esdomain/mapping/IndexMappings.java
- legacy/src/main/java/org/opensearch/sql/legacy/esdomain/mapping/Mappings.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/format/DescribeResultSet.java
- legacy/src/test/java/org/opensearch/sql/legacy/util/CheckScriptContents.java
- legacy/src/test/java/org/opensearch/sql/legacy/util/MultipleIndexClusterUtils.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
Backport #1571, #1580 and #1667
Backport breaking changes to 2.x, since they were backported in core.
> Backport breaking changes to 2.x

- integ-test/src/test/java/org/opensearch/sql/sql/CsvFormatIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/RawFormatIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/SimpleQueryStringIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSQLQueryAction.java
- plugin/build.gradle
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/JsonResponseFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/ResponseFormatter.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/CommandResponseFormatterTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/CsvResponseFormatterTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/VisualizationResponseFormatterTest.java
When making SQL calls with `csv` or `raw` outputs the formatting would be incorrect as the header sets the format to `application/json` rather than `plain/text` like the legacy engine did.
This PR adds a format getter to both response formatters to allow it to be set correctly.
https://github.com/opensearch-project/sql/issues/1572
> Fix CSV/RAW output header being application/json rather than plain/text

- core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
- core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java
- core/src/main/java/org/opensearch/sql/analysis/NestedAnalyzer.java
- core/src/main/java/org/opensearch/sql/analysis/SelectExpressionAnalyzer.java
- core/src/main/java/org/opensearch/sql/analysis/TypeEnvironment.java
- core/src/main/java/org/opensearch/sql/analysis/symbol/SymbolTable.java
- core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
- core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java
- core/src/main/java/org/opensearch/sql/ast/expression/NestedAllTupleFields.java
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
- docs/user/dql/functions.rst
- integ-test/src/test/java/org/opensearch/sql/legacy/PrettyFormatResponseIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/NestedIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstBuilderTest.java
Add support for using the `*` at end of field parameter in the nested function. All nested fields under supplied path will be expanded as column identifiers. Grammar has been added to only support the `AllTupleFields` usage with the nested function since this change will effect field usage in all queries and needs further planning with V2 implementation.
```sql
SELECT nested(message.*) from nested_objects;
```
Portion of Issue: [1111](https://github.com/opensearch-project/sql/issues/1111)
- Path parameter is redundant therefore not supported in parser and will fallback to legacy engine.
Queries that produce repeating column identifiers like: 
```sql
SELECT nested(field.*), nested(field.innerField) ...
```
Or 
```sql
SELECT nested(field.*), nested(field.*) ...
```
Will result in error: …
> Add Support for Field Star in Nested Function

- integ-test/src/test/java/org/opensearch/sql/sql/CsvFormatIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/RawFormatIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/SimpleQueryStringIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSQLQueryAction.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/JsonResponseFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/ResponseFormatter.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/CommandResponseFormatterTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/CsvResponseFormatterTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/VisualizationResponseFormatterTest.java
Manually backporting #1779 into 2.x as a few of the IT tests failed due to a small difference in the `getContentType` method
Automatic [backport](https://github.com/opensearch-project/sql/pull/1795) to 2.x failing
> Manually Backporting 1779 to 2.x

- integ-test/build.gradle
Disable CCS IT test case. It fails when security plugin is enabled.
Currently we don't have a way to run IT test with security plugin. Fix for the CCS IT will come after that is ready. Tracking issue: #1713
#1707 
> Disable CCS IT test

- datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
Will add IT later because current IT RestTestIT does not support configure nodes for each test and I do not want to configure nodes for all the IT now which will be also risky.
Create an issue for impove IT framework.https://github.com/opensearch-project/sql/issues/1816
#1801
> Guarantee datasource read api is strong consistent read

- build.gradle
- docs/user/dql/basics.rst
- docs/user/dql/functions.rst
- integ-test/build.gradle
- integ-test/src/test/java/org/opensearch/sql/sql/IdentifierIT.java
- plugin/build.gradle
Add the `_routing` reserved word as a metafield accessible as an identifier from any opensearch index. 
Example: 
```
select _id, _index, _routing, int0 from calcs limit 5
```
Example response:
```
[
"1",
"calcs",
"[xoyIAOdqQsS74x2yKSgiEQ][calcs][0]",
1
],
```
Partially resolves: [sql#1478](https://github.com/opensearch-project/sql/issues/1478)
> Add _routing to SQL includes list (#277)

- protocol/src/main/java/org/opensearch/sql/protocol/response/QueryResult.java
* Fix flaktest found in IT when -Dtests.locale=tr.
* Failed IT.
```
./gradlew ':integ-test:integTest' --tests "org.opensearch.sql.ppl.StandaloneIT.testSourceFieldQuery" -Dtests.seed=8DBF6CCDC4AAC1CC -Dtests.security.manager=false -Dtests.locale=tr -Dtests.timezone=Pacific/Marquesas -Druntime.java=11
```
n/a
> fix flakytest when tests.locale=tr

- common/build.gradle
- core/build.gradle
- legacy/build.gradle
- ppl/build.gradle
- protocol/build.gradle
- sql/build.gradle
- Bump guava version to 32.0.1
CVE-2023-2976
> Bump guava version to 32.0.1

- common/build.gradle
- integ-test/build.gradle
- ppl/build.gradle
`log4j` was updated on upstream https://github.com/opensearch-project/OpenSearch/pull/8307.
Fix build failures caused by referencing different `log4j` versions.
```
Could not determine the dependencies of task ':opensearch-sql-plugin:thirdPartyAudit'.
> Could not resolve all dependencies for configuration ':opensearch-sql-plugin:runtimeClasspath'.
> Conflict(s) found for the following module(s):
- org.apache.logging.log4j:log4j-api between versions 2.20.0 and 2.17.1
- org.apache.logging.log4j:log4j-core between versions 2.20.0 and 2.17.1
Run with:
--scan or
:opensearch-sql-plugin:dependencyInsight --configuration runtimeClasspath --dependency org.apache.logging.log4j:log4j-api
to get more insight on how to solve the conflict.
```
By submitting this pull request, I confirm that my …
> Bump `log4j` version.

- datasources/src/main/java/org/opensearch/sql/datasources/exceptions/ErrorMessage.java
- datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
(cherry picked from commit bb020ace1c2e61c499e17f958ddc0651c635a905) (cherry picked from commit ee62371105b2407b98c7797c5ddb728e3f9c35b1)
> Improved error codes in case of security exception (#1753) (#1811)

- flint/docs/index.md
- flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndex.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingFileIndex.scala
- flint/flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala
- flint/flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingFileIndexSuite.scala
- flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSuite.scala
Add hybrid scan mode which covers the latest source files that haven't refreshed to Flint index yet:
1. For skipping index, this means source file unknown in skipping index will not be skipped (because we're not sure if it has the answer for a query <= this is covered in this PR
2. For covered index/MV, this means we need to union all the results from unknown files and index data
https://github.com/opensearch-project/opensearch-spark/issues/2
> Provide hybrid scan setting for consistency requirement

- datasources/src/main/java/org/opensearch/sql/datasources/encryptor/EncryptorImpl.java
- datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
- datasources/src/test/java/org/opensearch/sql/datasources/encryptor/EncryptorImplTest.java
- docs/user/ppl/admin/datasources.rst
- integ-test/build.gradle
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
* `plugins.query.datasources.encryption.masterkey` is being used for encrypting auth information in datasource metadata configuration. In previous versions, this config will default to 0000000000000000 if not provided. 
* However, we have decided to remove the logic of defaulting for better security posture. So with this change, User has to generate a master key and configure in the opensearch.yml for using datasource CRUD APIs.
* Updated documentation: https://github.com/vamsi-amazon/sql/blob/remove-default-master-key/docs/user/ppl/admin/datasources.rst#master-key-config-for-encrypting-credential-information
Request:
```
{
"name": "aws_prometheus3",
"connector": "PROMETHEUS",
"allowedRoles": [],
"prometheus.uri": "https://localhost:9090",
"prometheus.auth.type" : …
```
> Remove Default master encryption key from settings.

- integ-test/build.gradle
Instead of applying master key config to all clusters. Applied only to integTest cluster.
> Restrict master key config only to integTest cluster

- flint/docs/index.md
- flint/flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
- flint/flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingStrategy.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/minmax/MinMaxSkippingStrategy.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/partition/PartitionSkippingStrategy.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/valueset/ValueSetSkippingStrategy.scala
- flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlAstBuilder.scala
- flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
- flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSuite.scala
- flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSqlITSuite.scala
- flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSqlSuite.scala
1. Add SQL support for create and refresh skipping index statement. Please find SQL syntax and example in https://github.com/dai-chen/sql-1/blob/add-create-skipping-index-sql-statement/flint/docs/index.md#sql
2. Rename skipping kind to match its name in SQL grammar
3. Add check for manual refresh on incremental refreshing index
https://github.com/opensearch-project/opensearch-spark/issues/2
> Add Flint create and refresh index SQL support

- DEVELOPER_GUIDE.rst
- docs/user/ppl/admin/spark_connector.rst
- spark/build.gradle
- spark/src/main/java/org/opensearch/sql/spark/client/EmrClientImpl.java
- spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
- spark/src/main/java/org/opensearch/sql/spark/functions/response/DefaultSparkSqlFunctionResponseHandle.java
- spark/src/main/java/org/opensearch/sql/spark/functions/response/SparkSqlFunctionResponseHandle.java
- spark/src/main/java/org/opensearch/sql/spark/functions/scan/SparkSqlFunctionTableScanBuilder.java
- spark/src/main/java/org/opensearch/sql/spark/functions/scan/SparkSqlFunctionTableScanOperator.java
- spark/src/main/java/org/opensearch/sql/spark/helper/FlintHelper.java
- spark/src/main/java/org/opensearch/sql/spark/response/SparkResponse.java
- spark/src/main/java/org/opensearch/sql/spark/storage/SparkScan.java
- spark/src/main/java/org/opensearch/sql/spark/storage/SparkStorageFactory.java
- spark/src/main/java/org/opensearch/sql/spark/storage/SparkTable.java
- spark/src/test/java/org/opensearch/sql/spark/client/EmrClientImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/constants/TestConstants.java
- spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionImplementationTest.java
- spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanBuilderTest.java
- spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanOperatorTest.java
- spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlTableFunctionResolverTest.java
- spark/src/test/java/org/opensearch/sql/spark/response/SparkResponseTest.java
- spark/src/test/java/org/opensearch/sql/spark/storage/SparkScanTest.java
- spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageEngineTest.java
- spark/src/test/java/org/opensearch/sql/spark/storage/SparkStorageFactoryTest.java
- spark/src/test/java/org/opensearch/sql/spark/storage/SparkTableTest.java
- spark/src/test/java/org/opensearch/sql/spark/utils/TestUtils.java
- spark/src/test/resources/all_data_type.json
- spark/src/test/resources/invalid_data_type.json
- spark/src/test/resources/invalid_response.json
- spark/src/test/resources/select_query_response.json
- cherry-picked 392a72000224f36a75222b22398357933d18c015 https://github.com/opensearch-project/sql/pull/1790
> [Backport 2.9] Add EMR client to spark connector (#1790)

- release-notes/opensearch-sql.release-notes-2.9.0.0.md
Addressing comments on 2.9 release notes.
> Addressing comments on 2.9 release notes

- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
Fixes for upstream refactor [8730](https://github.com/opensearch-project/OpenSearch/pull/8730).
N/A
> Fix Build from Upstream Refactor

- docs/user/ppl/functions/datetime.rst
Fixed the `day_of_week` PPL doctest accidentally calling the `dayofweek` function instead
No related issues
> Fixed missing underscores in day_of_week doctest

- integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
- integ-test/src/test/resources/expectedOutput/ppl/explain_query_range.json
- prometheus/src/main/java/org/opensearch/sql/prometheus/functions/response/DefaultQueryRangeFunctionResponseHandle.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/response/PrometheusResponse.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusMetricScan.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTable.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/storage/implementor/PrometheusDefaultImplementor.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/functions/scan/QueryRangeFunctionTableScanOperatorTest.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricScanTest.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTableTest.java
This PR is for changing the response structure of query_range table function in Prometheus Connector.
BWC failures are unrelated. WIll get fixed with the below PRs
https://github.com/opensearch-project/sql/pull/1876
https://github.com/opensearch-project/sql/pull/1868
Request::
PUT http://localhost:9200/_plugins/_ppl
```
{
"query" : "source = my_prometheus.query_range('prometheus_http_requests_total',1689281439,1689291439,14)"
}
```
Sample Old Response
```
{
"schema": [
{
"name": "@timestamp",
"type": "timestamp"
},
{
"name": "@value",
"type": "double"
},
{
"name": "handler",
"type": "string"
},
{
"name": "code",
"type": "string"
},
{
"name": "instance",
"type": "string"
},
{
"name": "__name__",
"type": "string"
},
{
"name": "job",
"type": "string"
}
],
"datarows": [
[
"2023-07-17 …
```
> Change query range response structure

- DEVELOPER_GUIDE.rst
- build.gradle
Adds support for Spotless code formatter via ./gradlew spotlessApply and ./gradlew spotlessCheck. Apply applies the checks, check notifies which changes need to be applied.
Proposed checks commented out:
License header
Import order - sorts imports
Remove unused imports
Trim trailing whitespace
End with newline
Google Java format - https://github.com/google/google-java-format 
**Note: proposed spotless checks will be commented out until fix for each individual is merged. Lines will be uncommented as part of PRs addressing change.**
For more information on following Developer Certificate of Origin and signing off your …
> Adding Spotless support framework

- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
`OpenSearchExprValueFactory` created for every query for every index and it creates a constant `typeActionMap` every time from the scratch.
Current fix makes `typeActionMap` initiated statically, so it will be created only once. This slightly increases query processing performance.
Performance boost.
> Statically init `typeActionMap` in `OpenSearchExprValueFactory`.

- docs/user/dql/expressions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/common/antlr/SyntaxParserTestBase.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/BracketedTimestampTest.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLParserTest.java
Added support for using timestamp/date/time using curly brackets in the following ways to fix failing date filters in PowerBI:
| Definition | Type |
| --- | --- |
| {ts 'YYYY-MM-DD hh:mm:ss[.SSS]'} | Timestamp |
| {timestamp 'YYYY-MM-DD hh:mm:ss[.SSS]'} | Timestamp |
| {d 'YYYY-MM-DD'} | Date |
| {date 'YYYY-MM-DD'} | Date |
| {t 'hh:mm:ss[.SSS]'} | Time |
| {time 'hh:mm:ss[.SSS]'} | Time |
https://github.com/opensearch-project/sql/issues/364
> Added support of timestamp/date/time using curly brackets

- build.gradle
- integ-test/build.gradle
- plugin/build.gradle
- sql-jdbc/build.gradle
Update guava to address [CVE-2023-2976](https://www.cve.org/CVERecord?id=CVE-2023-2976).
It looks like https://github.com/opensearch-project/sql/pull/1768 has already addressed this for 2.x so this is just a backport into 1.3.
https://github.com/opensearch-project/sql/issues/1767
> Update guava to address CVE-2023-2976

- DEVELOPER_GUIDE.rst
- build.gradle
Adds support for Spotless code formatter via ./gradlew spotlessApply and ./gradlew spotlessCheck. Apply applies the checks, check notifies which changes need to be applied.
Proposed checks commented out:
License header
Import order - sorts imports
Remove unused imports
Trim trailing whitespace
End with newline
Google Java format - https://github.com/google/google-java-format 
**Note: proposed spotless checks will be commented out until fix for each individual is merged. Lines will be uncommented as part of PRs addressing change.**
For more information on following Developer Certificate of Origin and signing off your …
> [Backport 2.x] Adding Spotless support framework #1888

- docs/user/dql/expressions.rst
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/test/java/org/opensearch/sql/common/antlr/SyntaxParserTestBase.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/BracketedTimestampTest.java
- sql/src/test/java/org/opensearch/sql/sql/antlr/SQLParserTest.java
Backport https://github.com/opensearch-project/sql/commit/1a7134b79044de655445f2c1e24ec56467544f50 from https://github.com/opensearch-project/sql/pull/1894
> [Backport 2.x] Added support of timestamp/date/time using curly brackets

- integ-test/src/test/java/org/opensearch/sql/legacy/DateFunctionsIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/JSONRequestIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/MathFunctionsIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/NestedFieldQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/QueryFunctionsIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLFunctionsIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SourceFieldIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/ConditionalIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/join/ElasticUtils.java
- legacy/src/main/java/org/opensearch/sql/legacy/query/join/JoinRequestBuilder.java
- legacy/src/main/java/org/opensearch/sql/legacy/query/join/NestedLoopsElasticRequestBuilder.java
- legacy/src/main/java/org/opensearch/sql/legacy/query/multi/MultiQueryRequestBuilder.java
- legacy/src/main/java/org/opensearch/sql/legacy/request/SqlRequest.java
- legacy/src/main/java/org/opensearch/sql/legacy/utils/JsonPrettyFormatter.java
- legacy/src/test/java/org/opensearch/sql/legacy/util/AggregationUtils.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/response/AggregationResponseUtils.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilderTest.java
- plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java
Breaking changes come from https://github.com/opensearch-project/OpenSearch/pull/8826.
Fix broken build. Again.
> Fix breaking changes.

- .github/workflows/backport.yml
Adds to the workflow to add a "failed-backport" label on the PR if a backport fails. This will help us filter by those PRs which failed the backport and reconcile before release/for CVEs
> fix fail backport

- common/build.gradle
- core/build.gradle
- legacy/build.gradle
- ppl/build.gradle
- protocol/build.gradle
- sql/build.gradle
Upgrade guava version to 32.0.1-jre
There was a mismatch among files updated for guava version, few were pointing to 31 where others were pointing to 32 version. 
> Upgrade guava version to 32.0.1-jre

- build.gradle
- common/build.gradle
- common/src/main/java/org/opensearch/sql/common/antlr/CaseInsensitiveCharStream.java
- common/src/main/java/org/opensearch/sql/common/antlr/SyntaxAnalysisErrorListener.java
- common/src/main/java/org/opensearch/sql/common/antlr/SyntaxCheckException.java
- common/src/main/java/org/opensearch/sql/common/authinterceptors/AwsSigningInterceptor.java
- common/src/main/java/org/opensearch/sql/common/authinterceptors/BasicAuthenticationInterceptor.java
- common/src/main/java/org/opensearch/sql/common/grok/Converter.java
- common/src/main/java/org/opensearch/sql/common/grok/Grok.java
- common/src/main/java/org/opensearch/sql/common/grok/GrokCompiler.java
- common/src/main/java/org/opensearch/sql/common/grok/GrokUtils.java
- common/src/main/java/org/opensearch/sql/common/grok/Match.java
- common/src/main/java/org/opensearch/sql/common/grok/exception/GrokException.java
- common/src/main/java/org/opensearch/sql/common/response/ResponseListener.java
- common/src/main/java/org/opensearch/sql/common/setting/LegacySettings.java
- common/src/main/java/org/opensearch/sql/common/setting/Settings.java
- common/src/main/java/org/opensearch/sql/common/utils/QueryContext.java
- common/src/main/java/org/opensearch/sql/common/utils/StringUtils.java
- common/src/test/java/org/opensearch/sql/common/authinterceptors/AwsSigningInterceptorTest.java
- common/src/test/java/org/opensearch/sql/common/authinterceptors/BasicAuthenticationInterceptorTest.java
- common/src/test/java/org/opensearch/sql/common/grok/ApacheDataTypeTest.java
- common/src/test/java/org/opensearch/sql/common/grok/ApacheTest.java
- common/src/test/java/org/opensearch/sql/common/grok/BasicTest.java
- common/src/test/java/org/opensearch/sql/common/grok/CaptureTest.java
- common/src/test/java/org/opensearch/sql/common/grok/GrokDocumentationTest.java
- common/src/test/java/org/opensearch/sql/common/grok/GrokTest.java
- common/src/test/java/org/opensearch/sql/common/grok/MessagesTest.java
- common/src/test/java/org/opensearch/sql/common/grok/ResourceManager.java
Applies spotless for Google Java Code Format for the common directory.
**Note**: https://github.com/opensearch-project/sql/issues/889 for the codeql bot comments below.
> [Spotless] Applying Google Code Format for common #7

- build.gradle
Okio upgrade to 3.5.0
Fixes CVE-2023-3635 from transitive dependency 
> Okio upgrade to 3.5.0

- build.gradle
- ppl/build.gradle
- ppl/src/main/java/org/opensearch/sql/ppl/PPLService.java
- ppl/src/main/java/org/opensearch/sql/ppl/antlr/PPLSyntaxParser.java
- ppl/src/main/java/org/opensearch/sql/ppl/domain/PPLQueryRequest.java
- ppl/src/main/java/org/opensearch/sql/ppl/domain/PPLQueryResponse.java
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstStatementBuilder.java
- ppl/src/main/java/org/opensearch/sql/ppl/utils/ArgumentFactory.java
- ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
- ppl/src/main/java/org/opensearch/sql/ppl/utils/UnresolvedPlanHelper.java
- ppl/src/test/java/org/opensearch/sql/ppl/PPLServiceTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/antlr/NowLikeFunctionParserTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/antlr/PPLSyntaxParserMatchBoolPrefixSamplesTests.java
- ppl/src/test/java/org/opensearch/sql/ppl/antlr/PPLSyntaxParserMatchPhraseSamplesTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/antlr/PPLSyntaxParserTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/domain/PPLQueryRequestTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/domain/PPLQueryResponseTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstNowLikeFunctionTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstStatementBuilderTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/ArgumentFactoryTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/UnresolvedPlanHelperTest.java
Applies spotless for ppl directory in project. Sets checkstyle to not fail on failure for ppl directory.
> [Spotless] Applying Google Code Format for ppl files #12

- build.gradle
- integ-test/src/test/java/org/opensearch/sql/bwc/SQLBackwardsCompatibilityIT.java
- integ-test/src/test/java/org/opensearch/sql/correctness/TestConfig.java
- integ-test/src/test/java/org/opensearch/sql/correctness/tests/OpenSearchConnectionTest.java
- integ-test/src/test/java/org/opensearch/sql/correctness/testset/TestDataSet.java
- integ-test/src/test/java/org/opensearch/sql/jdbc/CursorIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/AggregationIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/DateFormatIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/MetaDataQueriesIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/MethodQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/NestedFieldQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/OrderIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/PrettyFormatResponseIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/QueryFunctionsIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/QueryIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/RestIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TermQueryExplainIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java
- integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeImplementationIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/MatchPhrasePrefixIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/ObjectFieldOperateIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/ConvertTZFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeImplementationIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/ScoreQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/StringLiteralIT.java
- integ-test/src/test/java/org/opensearch/sql/util/ExecuteOnCallerThreadQueryManager.java
- integ-test/src/test/java/org/opensearch/sql/util/TestUtils.java
Applies spotless for  integ-test directory in project. Sets checkstyle to not fail on failure for  integ-test directory.
> [Spotless] Applying Google Code Format for integ-test directory (pt 4/4) #18

- build.gradle
- protocol/build.gradle
- protocol/src/main/java/org/opensearch/sql/protocol/response/QueryResult.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/CommandResponseFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/CsvResponseFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/ErrorFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/Format.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/JdbcResponseFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/JsonResponseFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/RawResponseFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/ResponseFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/SimpleJsonResponseFormatter.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/VisualizationResponseFormatter.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/QueryResultTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/CommandResponseFormatterTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/CsvResponseFormatterTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/FormatTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/JdbcResponseFormatterTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/SimpleJsonResponseFormatterTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/VisualizationResponseFormatterTest.java
Applies spotless for protocol directory in project. Sets checkstyle to not fail on failure for protocol directory.
> [Spotless] Applying Google Code Format for protocol files #14

- doctest/test_data/nested_objects.json
- doctest/test_data/wildcard.json
Clean up doctest test data. Fortunately, no test failed due to incorrect import.
Doctest uses python client to manipulate with test data and it interpreted `{"index":{"_id":"0"}}` as a doc to import. Fortunately, opensearch DSL ignores such docs for queries being tested, so it didn't affect the test.
```
opensearchsql> select * from nested;
fetched rows / total rows = 4/4
+--------------+------------------------------+---------+-------------+------------------------------------------------+
| index        | comment                      | myNum   | someField   | message                                        |
|--------------+------------------------------+---------+-------------+------------------------------------------------|
| {'_id': '1'} | null                         | null    | …
```
> Fix doctest data

- .github/workflows/integ-tests-with-security.yml
- integ-test/build.gradle
- integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java
- integ-test/src/test/java/org/opensearch/sql/ppl/CrossClusterSearchIT.java
- integ-test/src/test/java/org/opensearch/sql/security/CrossClusterSearchIT.java
This PR adds a new IT gradle task: `integTestWithSecurity`. It starts a cluster with security plugin installed (it takes latest snapshot), configures cluster, http client for tests and runs one test which required to be run with security plugin.
A new GHA is added which runs this test task.
Please, see team review and discussion in https://github.com/Bit-Quill/opensearch-project-sql/pull/335.
fixes #1713
> Run IT tests with security plugin (#335)

- DEVELOPER_GUIDE.rst
Adds more information and links about spotless and google java formatter in the developer guide.
> Developer guide update with Spotless details

- datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
- datasources/src/test/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorageTest.java
In the current state when datasource is updated with existing configuration, it results in 503 error.
With this PR, it returns 200.
> Fixed exception when datasource is updated with existing configuration.

- .github/workflows/integ-tests-with-security.yml
- integ-test/build.gradle
- integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java
- integ-test/src/test/java/org/opensearch/sql/security/CrossClusterSearchIT.java
Backport #1986 to 2.x
This PR adds a new IT gradle task: integTestWithSecurity. It starts a cluster with security plugin installed (it takes latest snapshot), configures cluster, http client for tests and runs one test which required to be run with security plugin.
A new GHA is added which runs this test task.
Please, see team review and discussion in https://github.com/Bit-Quill/opensearch-project-sql/pull/335.
fixes https://github.com/opensearch-project/sql/issues/1713
New functionality includes testing.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/mai …
> [Backport 2.x] Run IT tests with security plugin (#335) #1986

- build.gradle
Spotless runs on generated files. Generated files may not be properly formatted, and spotless should not try to modify them. This PR adds `**/gen/**` to the excludes list, for example `ppl\src\main\antlr\gen\OpenSearchPPLLexer.java`.
> [Spotless] Exclude generated files from spotless 

- legacy/src/main/antlr/OpenSearchLegacySqlParser.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
Changed formatting of Antlr parser files based on Spotless changes. I have not applied the changes made to the lexer files as it completely rewrites the files to make them much less readable
N/A
> [Backport 2.x] Applied formatting improvements to Antlr files based on spotless changes (#2017)

- datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
This reverts commit f38ffed084cdcfc288eb32b35f3f3f1e5f5425d9.
This change reverts the commit f38ffed084cdcfc288eb32b35f3f3f1e5f5425d9 as 
1. With https://github.com/opensearch-project/OpenSearch/issues/8536, core now supports realtime reads with [get](https://opensearch.org/docs/latest/api-reference/document-apis/get-documents/)/[mget](https://opensearch.org/docs/latest/api-reference/document-apis/multi-get/) APIs. Thus, if strong reads are desired plugin can use get/mget queries. get/mget is recommended over `_primary` based routing preference in order to reduce load on primary.
2. Existing OpenSearchDataSourceMetadataStorage.java uses `match_all` & `term` based search queries which does not provide strong reads and thus as part of https://github.com/opensearch-project/sql/issues/1801 …
> Revert "Guarantee datasource read api is strong consistent read (#1815)"

- datasources/src/main/java/org/opensearch/sql/datasources/exceptions/DataSourceClientException.java
- plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLQueryAction.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClientImpl.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/exceptions/PrometheusClientException.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/request/system/PrometheusDescribeMetricRequest.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/client/PrometheusClientImplTest.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java
- prometheus/src/test/resources/non_json_response.json
* For requests with security access exception, we are currently throwing 503 which is not recommended.
With this change, we are setting the status received from Opensearch Security Exception.
* All the prometheus errors are captured in PrometheusClientException and we are throwing 400 error to let customer fix the setup.
* Disabled redirects in okhttp client to block any ssrf issues.
* https://github.com/opensearch-project/sql/issues/2035 Issue for improving error response code.
* https://github.com/opensearch-project/sql/issues/2034 Issue for improving security integ tests framework to incorportate users with multiple permissions personas.
**Before Changes:**
POST _plugins/_ppl
{
"query" : "source=prometheus10.instance_cpu_time_ns"
}
**After Changes:**
POST _plugins/_ppl
{
"query" : …
> Fixed response codes For Requests With security exception.

- datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
- datasources/src/test/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorageTest.java
Adds _primary preference only for segment replication enabled indices. 
#1801 
> Add _primary preference only for segment replication enabled indices

- datasources/build.gradle
fix CVE-2023-33201 by changing jdk15on to jdk15to18
> bump aws-encryption-sdk-java to 1.71

- common/build.gradle
- common/src/main/java/org/opensearch/sql/common/interceptors/AwsSigningInterceptor.java
- common/src/main/java/org/opensearch/sql/common/interceptors/BasicAuthenticationInterceptor.java
- common/src/main/java/org/opensearch/sql/common/interceptors/URIValidatorInterceptor.java
- common/src/main/java/org/opensearch/sql/common/setting/Settings.java
- common/src/main/java/org/opensearch/sql/common/utils/URIValidationUtils.java
- common/src/test/java/org/opensearch/sql/common/interceptors/AwsSigningInterceptorTest.java
- common/src/test/java/org/opensearch/sql/common/interceptors/BasicAuthenticationInterceptorTest.java
- datasources/build.gradle
- datasources/src/main/java/org/opensearch/sql/datasources/utils/DatasourceValidationUtils.java
- datasources/src/test/java/org/opensearch/sql/datasources/utils/DatasourceValidationUtilsTest.java
- docs/user/ppl/admin/datasources.rst
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
- prometheus/build.gradle
- prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClientImpl.java
- prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/client/PrometheusClientImplTest.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java
* Changed allowlist config to denylist of ips.
`plugins.query.datasources.uri.hosts.denylist` is the new property.
* Validating datasource URL in every interaction. So the datasource validation happens during datasource creation and datasource queries.
Current Process of Validation:
* Before interacting with any customer provided URI, we do dns resolution and validate the ip against the denylist provided in the config.
* The new config specifes denied IP CIDR blocks. For eg: `127.0.0.0/8` …
> Changed allowlist config to denylist ip config for datasource uri hosts

- build.gradle
- integ-test/build.gradle
Build is failing when we run with snapshot=false. This is due to downloading non-snapshot version of security plugin.
As a temporary fix, we will always download snapshot version of security plugin irrespective of security plugin.
> Always use snapshot version for security plugin download

- integ-test/build.gradle
Security Plugin zip is downloaded even when the file is already downloaded in the prior run.
Added a check to stop downloading multiple times.
> Check for existence of security plugin

- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
- spark/build.gradle
- spark/src/main/java/org/opensearch/sql/spark/rest/RestJobManagementAction.java
- spark/src/main/java/org/opensearch/sql/spark/rest/model/CreateJobRequest.java
- spark/src/main/java/org/opensearch/sql/spark/transport/TransportCreateJobRequestAction.java
- spark/src/main/java/org/opensearch/sql/spark/transport/TransportDeleteJobRequestAction.java
- spark/src/main/java/org/opensearch/sql/spark/transport/TransportGetJobRequestAction.java
- spark/src/main/java/org/opensearch/sql/spark/transport/TransportGetQueryResultRequestAction.java
- spark/src/main/java/org/opensearch/sql/spark/transport/model/CreateJobActionRequest.java
- spark/src/main/java/org/opensearch/sql/spark/transport/model/CreateJobActionResponse.java
- spark/src/main/java/org/opensearch/sql/spark/transport/model/DeleteJobActionRequest.java
- spark/src/main/java/org/opensearch/sql/spark/transport/model/DeleteJobActionResponse.java
- spark/src/main/java/org/opensearch/sql/spark/transport/model/GetJobActionRequest.java
- spark/src/main/java/org/opensearch/sql/spark/transport/model/GetJobActionResponse.java
- spark/src/main/java/org/opensearch/sql/spark/transport/model/GetJobQueryResultActionRequest.java
- spark/src/main/java/org/opensearch/sql/spark/transport/model/GetJobQueryResultActionResponse.java
- spark/src/test/java/org/opensearch/sql/spark/transport/TransportCreateJobRequestActionTest.java
- spark/src/test/java/org/opensearch/sql/spark/transport/TransportDeleteJobRequestActionTest.java
- spark/src/test/java/org/opensearch/sql/spark/transport/TransportGetJobRequestActionTest.java
- spark/src/test/java/org/opensearch/sql/spark/transport/TransportGetQueryResultRequestActionTest.java
- spark/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
* Contains Rest, Transport Layer Files for new job APIs.
* Currently we are making the changes in spark connector module, we may move to a new module once the design becomes concrete.
* Documentation will be added in individual API PRs.
> Initial commit of new job APIs

- datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
- docs/user/interfaces/asyncqueryinterface.rst
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorService.java
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
- spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
- spark/src/main/java/org/opensearch/sql/spark/client/SparkJobClient.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/rest/RestAsyncQueryManagementAction.java
- spark/src/main/java/org/opensearch/sql/spark/transport/TransportCancelAsyncQueryRequestAction.java
- spark/src/main/java/org/opensearch/sql/spark/transport/model/CancelAsyncQueryActionRequest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- spark/src/test/java/org/opensearch/sql/spark/transport/TransportCancelAsyncQueryRequestActionTest.java
* This PR covers Cancel Async Query API.
* Throws error incase of already successful async query and cancels a query which is IN_PROGRESS/QUEUED/RUNNING.
* Only unit tests are covered since there is not integration test setup.
> Cancel Async Query API

- plugin/build.gradle
Fix mockito core conflicts with core.
> Fix mockito core conflict.

- datasources/src/main/java/org/opensearch/sql/datasources/utils/DatasourceValidationUtils.java
- datasources/src/test/java/org/opensearch/sql/datasources/utils/DatasourceValidationUtilsTest.java
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
- prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java
* Currently in datasource uri validation, we validate domain which is excessively restrictive and hampering ease of use in case of docker and using ips in prometheus URL. This PR addresses this problem by removing the restriction. 
* We can always avoid ssrf issue by specifying the host denylist `plugins.query.datasources.uri.hosts.denylist` 
Manual Testing
```
curl --location 'localhost:9200/_plugins/_query/_datasources/' \
--header 'Content-Type: application/json' \
--data '{
"name": "my_prometheus3",
"connector": "PROMETHEUS",
"allowedRoles": [],
"prometheus.uri": "http://10.0.0.1:9090"
}
}'
```
This call worked which used to not function earlier.
By submitting this pull request, I confirm that my contribution is made under the …
> Removed Domain Validation

- core/src/main/java/org/opensearch/sql/datasource/model/DataSourceMetadata.java
- datasources/src/main/java/org/opensearch/sql/datasources/utils/XContentParserUtils.java
- datasources/src/test/java/org/opensearch/sql/datasources/utils/XContentParserUtilsTest.java
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
- plugin/build.gradle
* Added description field to datasource metadata.
* Removed restriction on all fields with prefix auth. Now only username, password, access_key, secret_key are the only fields removed from GET datasource API.
> Datasource description

- build.gradle
* Temporarily changed ml-commons version to 2.10.0.0.
> Increment version to 2.11

- docs/user/interfaces/asyncqueryinterface.rst
- spark/build.gradle
- spark/src/main/antlr/FlintSparkSqlExtensions.g4
- spark/src/main/antlr/SparkSqlBase.g4
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryRequest.java
- spark/src/main/java/org/opensearch/sql/spark/rest/model/CreateAsyncQueryRequest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- spark/src/test/java/org/opensearch/sql/spark/transport/TransportCreateAsyncQueryRequestActionTest.java
* Added PPL lang to Async Query API.
* Added datasource to request model.
* Removed table and schema tags in non Index Queries.
* Updated Spark Grammar For Indices.
> Enable PPL lang and add datasource to async query API

- datasources/src/main/java/org/opensearch/sql/datasources/auth/AuthenticationType.java
- datasources/src/main/java/org/opensearch/sql/datasources/glue/GlueDataSourceFactory.java
- datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
- datasources/src/test/java/org/opensearch/sql/datasources/glue/GlueDataSourceFactoryTest.java
- docs/user/ppl/admin/connectors/s3glue_connector.rst
- prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/S3GlueSparkSubmitParameters.java
- spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
* false is replaced with `noauth` for `glue.indexstore.opensearch.auth` property.
* Fixed few more bugs in indexstore parameters.
> Refactor Flint Auth

- datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
1. Using name.keyword == datasource.name when search. which is case sensitive.
#2196
> Bug fix, datasource API should be case sensitive

- spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexDetails.java
- spark/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
- spark/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
* Submit long running job only when auto_refresh = false
https://github.com/opensearch-project/sql/issues/2206
> Submit long running job only when auto_refresh = false

- spark/src/main/java/org/opensearch/sql/spark/functions/response/DefaultSparkSqlFunctionResponseHandle.java
- spark/src/test/java/org/opensearch/sql/spark/functions/SparkSqlFunctionTableScanOperatorTest.java
- spark/src/test/resources/issue2210.json
handle DESC TABLE response
https://github.com/opensearch-project/sql/issues/2210
> Bug Fix, handle DESC TABLE response

- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
- spark/build.gradle
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryResponse.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexDetails.java
- spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReader.java
- spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImpl.java
- spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexType.java
- spark/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/OpensearchAsyncQueryAsyncQueryJobMetadataStorageServiceTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- spark/src/test/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImplTest.java
- spark/src/test/resources/flint-index-mappings/flint_my_glue_default_http_logs_size_year_covering_index.json
* Add capabilities for drop Index Query.
> Drop Index Implementation

- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
- spark/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClient.java
- spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
- spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImpl.java
- spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexType.java
- spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
* Refactoring EMRServerlessClientImpl classname.
* Fixed CoveringIndex Drop Issue.
> Minor fix in dropping covering index

- docs/user/ppl/admin/connectors/s3glue_connector.rst
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/response/JobExecutionResponseReader.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- spark/src/test/java/org/opensearch/sql/spark/response/AsyncQueryExecutionResponseReaderTest.java
Previously, the query status was set to SUCCESS only when the EMR-S job status was 'SUCCESS'. However, for index queries, even when the EMR Job Run State is 'RUNNING', the result should indicate success. This PR addresses and resolves this inconsistency.
Tests done:
* Manual verification: Created a skipping index and confirmed the async query result is marked 'successful' instead of 'running'.
* Updated relevant unit tests.
https://github.com/opensearch-project/sql/issues/2214
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-ce …
> Correctly Set query status

- docs/user/interfaces/asyncqueryinterface.rst
- docs/user/ppl/admin/connectors/s3glue_connector.rst
* Added and modified documentation for s3 Glue Connector and  spark execution engine settings.
* Documentation Links: 
* S3 Connector: https://github.com/vamsi-amazon/sql/blob/main/docs/user/ppl/admin/connectors/s3glue_connector.rst
* Async APIs: https://github.com/vamsi-amazon/sql/blob/main/docs/user/interfaces/asyncqueryinterface.rst
> Add documentation for S3GlueConnector.

- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
- spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfig.java
- spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSetting.java
- spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigSupplier.java
- spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigSupplierImpl.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSettingTest.java
- spark/src/test/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigSupplierImplTest.java
* Refactoring for Spark Execution Engine Config Reading.
* `SparkExecutionEngineConfigClusterSetting` is the POJO class for reading `plugins.query.executionengine.spark.config` cluster setting.
*  `SparkExecutionEngineConfigSupplier` is the new interface responsible for providing the configuration to  `AsyncQueryExecutorService`.
* `SparkExecutionEngineConfig` is the Interface between AsyncQueryExecutorService and SparkExecutionEngineConfigSupplier.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#d …
> Spark Execution Engine Config Refactor

- datasources/src/main/java/org/opensearch/sql/datasources/service/DataSourceServiceImpl.java
- datasources/src/test/java/org/opensearch/sql/datasources/service/DataSourceServiceImplTest.java
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
* Allow all auth parameters except for `auth.username`, `auth.password`, `auth.access_key` and `auth.secret_key` in datasource GET API results.
> Provide auth.type and auth.role_arn paramters in GET Datasource API response.

- spark/build.gradle
- spark/src/main/java/org/opensearch/sql/spark/execution/session/CreateSessionRequest.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/Session.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionId.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionModel.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionState.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionType.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/SessionStateStore.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionStateTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionTypeTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/statestore/SessionStateStoreTest.java
1. add InteractiveSession and SessionManager
Phase 3. https://github.com/opensearch-project/sql/issues/2089
> add InteractiveSession and SessionManager

- legacy/build.gradle
- opensearch/build.gradle
- ppl/build.gradle
- prometheus/build.gradle
- spark/build.gradle
- sql/build.gradle
Upgrade JSON to 20231013 to fix CVE-2023-5072
> Upgrade JSON to 20231013 to fix CVE-2023-5072

- spark/src/main/antlr/SqlBaseParser.g4
- spark/src/main/java/org/opensearch/sql/spark/client/StartJobRequest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
* Currently unit tests are not validating the startJobRequest object.
* Added new changes from grammar in opensearch-spark.
> Refactoring in Unit Tests

- spark/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
- spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
> Bug Fix, support cancel query in running state

- spark/src/main/antlr/FlintSparkSqlExtensions.g4
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexQueryActionType.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexQueryDetails.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
- spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReader.java
- spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImpl.java
- spark/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
- spark/src/test/java/org/opensearch/sql/spark/flint/FlintIndexMetadataReaderImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/flint/IndexQueryDetailsTest.java
- spark/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
* Changed job_type tag to type.
* Added `sid`  emr tag in interactive session query.
* Handled describe, refresh, show queries properly.
https://github.com/opensearch-project/sql/pull/2336
> Handle Describe,Refresh and Show Queries Properly

- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/Session.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
https://github.com/opensearch-project/sql/issues/2360
https://github.com/opensearch-project/sql/issues/2360
> create new session if current session not ready

- docs/user/admin/settings.rst
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
1.  enable session support by default. update setting doc.
2. bug fix - lowercase datasource name when create request indices.
3. disable flaky test.
n/a
> Enable session by default

- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
* Refactored tags usage.
* Change cluster tag name to `domain_ident`.
* Explicitly set deny list settings in AsyncQueryExecutorServiceImplSpecTest to empty.
> Refactoring for tags usage in test files.

- common/src/main/java/org/opensearch/sql/common/setting/Settings.java
- core/src/main/java/org/opensearch/sql/datasource/model/DataSourceMetadata.java
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
- core/src/test/java/org/opensearch/sql/planner/physical/datasource/DataSourceTableScanTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/service/DataSourceServiceImplTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/utils/XContentParserUtilsTest.java
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/ShowDataSourcesCommandIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
- spark/build.gradle
- spark/src/main/java/org/opensearch/sql/spark/client/EmrClientImpl.java
- spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
- spark/src/main/java/org/opensearch/sql/spark/cluster/ClusterManagerEventListener.java
- spark/src/main/java/org/opensearch/sql/spark/cluster/FlintIndexRetention.java
- spark/src/main/java/org/opensearch/sql/spark/cluster/IndexCleanup.java
- spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
- spark/src/main/java/org/opensearch/sql/spark/response/JobExecutionResponseReader.java
- spark/src/main/java/org/opensearch/sql/spark/response/SparkResponse.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/response/AsyncQueryExecutionResponseReaderTest.java
- spark/src/test/java/org/opensearch/sql/spark/response/SparkResponseTest.java
- Introduce dynamic settings for enabling/disabling purging and controlling index TTL.
- Reuse default result index name as a common prefix for all result indices.
- Change result index to a non-hidden index for better user experience.
- Allow custom result index specification in the data source.
- Move default result index name from spark to core package to avoid cross-package references.
- Add validation for provided result index name in the data source.
- Use pattern prefix + data source name for default result index naming.
Testing:
- Verified old documents are purged in a cluster setup.
- Checked result index naming with and without custom names, ensuring validation is applied.
Note: Tests will be added in a subsequent PR.
https://github.com/opensearch-project/sql/issues/2331
By …
> Add Flint Index Purging Logic

- common/src/main/java/org/opensearch/sql/common/setting/Settings.java
- datasources/build.gradle
- datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceAction.java
- datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceActionTest.java
- docs/user/admin/settings.rst
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/AsyncQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/DispatchQueryContext.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
- spark/src/main/java/org/opensearch/sql/spark/leasemanager/ConcurrencyLimitExceededException.java
- spark/src/main/java/org/opensearch/sql/spark/leasemanager/DefaultLeaseManager.java
- spark/src/main/java/org/opensearch/sql/spark/leasemanager/LeaseManager.java
- spark/src/main/java/org/opensearch/sql/spark/leasemanager/model/LeaseRequest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- spark/src/test/java/org/opensearch/sql/spark/leasemanager/DefaultLeaseManagerTest.java
1. add cluster level datasource limit.
2. add cluster level session limit.
3. move query process to handler based on query type. Todo, will add drop index will be address in https://github.com/opensearch-project/sql/pull/2386.
4. add LeaseManager, currently, it only limit the concurrent session in cluster.
https://github.com/opensearch-project/sql/issues/2379
> add concurrent limit on datasource and sessions

- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementModel.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Backport https://github.com/opensearch-project/sql/pull/2368
* Create new session if session is invalid
* fix code style
* fix UT
* fix error response
---------
(cherry picked from commit e16da37e167298a251a4cbd7750612b8792f0129) …
> [Backport 2.x] Create new session if client provided session is invalid (#2368)

- datasources/build.gradle
- datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
- datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceAction.java
- datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportDeleteDataSourceAction.java
- datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportGetDataSourceAction.java
- datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportPatchDataSourceAction.java
- datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportUpdateDataSourceAction.java
- datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceActionTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportDeleteDataSourceActionTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportGetDataSourceActionTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportPatchDataSourceActionTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportUpdateDataSourceActionTest.java
- legacy/src/main/java/org/opensearch/sql/legacy/metrics/MetricFactory.java
- legacy/src/main/java/org/opensearch/sql/legacy/metrics/MetricName.java
- legacy/src/main/java/org/opensearch/sql/legacy/utils/MetricUtils.java
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
- spark/build.gradle
- spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
Added new metrics to stats API.
Below are the list of new metrics.
```
DATASOURCE_CREATION_REQ_COUNT("datasource_create_request_count"),
DATASOURCE_GET_REQ_COUNT("datasource_get_request_count"),
DATASOURCE_PUT_REQ_COUNT("datasource_put_request_count"),
DATASOURCE_PATCH_REQ_COUNT("datasource_patch_request_count"),
DATASOURCE_DELETE_REQ_COUNT("datasource_delete_request_count"),
DATASOURCE_FAILED_REQ_COUNT_SYS("datasource_failed_request_count_syserr"),
DATASOURCE_FAILED_REQ_COUNT_CUS("datasource_failed_request_count_cuserr"),
EMR_START_JOB_REQUEST_FAILURE_COUNT("emr_start_job_request_failure_count"),
EMR_GET_JOB_RESULT_FAILURE_COUNT("emr_get_job_request_failure_count"),
EMR_CANCEL_JOB_REQUEST_FAILURE_COUNT("emr_cancel_job_request_failure_count"), …
```
> Added session, statement, emrjob metrics to sql stats api

- docs/user/admin/settings.rst
- plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java
- spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/constants/TestConstants.java
Currently SQL Query Settings API acts as a backdoor for changing cluster settings specific to sql engine. We no longer require this for the new settings introduced for spark execution engine.  
New Settings Introduced.
```
plugins.query.datasources.encryption.masterkey
plugins.query.datasources.uri.hosts.denylist
plugins.query.executionengine.spark.config
plugins.query.executionengine.spark.session.limit
plugins.query.executionengine.spark.refresh_job.limit
plugins.query.executionengine.spark.session.index.ttl
plugins.query.executionengine.spark.result.index.ttl
plugins.query.executionengine.spark.auto_index_management.enabled
```
We also need to rethink the use cases of this API and deprecate if not required.[https://github.com/opensearch-project/sql/issues/2409]
This PR covers blocking …
> Block execution engine settings in sql query settings API and add more unit tests

- datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
- datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportCreateDataSourceAction.java
- datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportDeleteDataSourceAction.java
- datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportGetDataSourceAction.java
- datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportPatchDataSourceAction.java
- datasources/src/main/java/org/opensearch/sql/datasources/transport/TransportUpdateDataSourceAction.java
- legacy/src/main/java/org/opensearch/sql/legacy/metrics/MetricName.java
- spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
- spark/src/main/java/org/opensearch/sql/spark/rest/RestAsyncQueryManagementAction.java
- spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
* Added below metrics.
```
ASYNC_QUERY_CREATE_API_REQUEST_COUNT("async_query_create_api_request_count"),
ASYNC_QUERY_GET_API_REQUEST_COUNT("async_query_get_api_request_count"),
ASYNC_QUERY_CANCEL_API_REQUEST_COUNT("async_query_cancel_api_request_count"),
ASYNC_QUERY_GET_API_FAILED_REQ_COUNT_SYS("async_query_get_api_failed_request_count_syserr"),
ASYNC_QUERY_GET_API_FAILED_REQ_COUNT_CUS("async_query_get_api_failed_request_count_cuserr"),
ASYNC_QUERY_CREATE_API_FAILED_REQ_COUNT_SYS("async_query_create_api_failed_request_count_syserr"),
ASYNC_QUERY_CREATE_API_FAILED_REQ_COUNT_CUS("async_query_create_api_failed_request_count_cuserr"),
ASYNC_QUERY_CANCEL_API_FAILED_REQ_COUNT_SYS("async_query_cancel_api_failed_request_count_syserr"),
ASYNC_QUERY_CANCEL_API_FAILED_REQ_COUNT_CUS("async_query_cance …
```
> Add more metrics and handle emr exception message

- datasources/src/main/java/org/opensearch/sql/datasources/exceptions/ErrorMessage.java
- datasources/src/test/java/org/opensearch/sql/datasources/exceptions/ErrorMessageTest.java
- spark/src/main/java/org/opensearch/sql/spark/rest/RestAsyncQueryManagementAction.java
Return 429 for ConcurrencyLimitExceededException
n/a
> Return 429 for ConcurrencyLimitExceededException

- plugin/src/main/java/org/opensearch/sql/plugin/transport/TransportPPLQueryResponse.java
- plugin/src/test/java/org/opensearch/sql/plugin/transport/TransportPPLQueryResponseTest.java
Add seder to TransportPPLQueryResponse
Add seder to TransportPPLQueryResponse
> Add seder to TransportPPLQueryResponse

- scripts/build.sh
Add publishToMavenLocal to publish plugins in this script
Add publishToMavenLocal to publish plugins in this script
> Add publishToMavenLocal to publish plugins in this script

- legacy/src/main/java/org/opensearch/sql/legacy/plugin/RestSqlStatsAction.java
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
- plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLStatsAction.java
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
- spark/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactory.java
- spark/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImpl.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
- spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/constants/TestConstants.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
- spark/src/test/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModuleTest.java
* Restructured the instantiation of AsyncQueryExecutorService using the Guice framework.
* Substituted the usage of EMRServerlessClient with EMRServerlessClientFactory. This modification helps prevent unnecessary errors and warnings during the plugin bootstrapping phase, particularly when constructing EMRServerlessClient using SparkExecutionEngineConfig.
* Previously, updating the Spark execution engine cluster configuration necessitated a system restart. With the current implementation, the recreation of EMRServerlessClient upon any cluster setting update eliminates the need for a restart.
* statement count and session count metrics are blocking operations as they make calls to opensearch index. So, we are moving stats operations to thread pool instead of processing on Transport thread. …
> Async Executor Service Depedencies Refactor

- build.gradle
- common/build.gradle
- integ-test/build.gradle
- spark/build.gradle
Bump aws-java-sdk-core version to 1.12.651
https://github.com/opensearch-project/sql/issues/2473
> Bump aws-java-sdk-core version to 1.12.651

- docs/user/interfaces/asyncqueryinterface.rst
> [DOC] Configure the Spark metrics properties while creating a s3 Glue Connector

- .github/workflows/integ-tests-with-security.yml
- .github/workflows/sql-test-and-build-workflow.yml
- docs/user/dql/functions.rst
- docs/user/ppl/functions/relevance.rst
Add JDK-21 to GA worklflows
Part of https://github.com/opensearch-project/OpenSearch/issues/10334
> Add JDK-21 to GA worklflows

- common/src/main/java/org/opensearch/sql/common/setting/Settings.java
- docs/user/admin/settings.rst
- integ-test/src/test/java/org/opensearch/sql/asyncquery/AsyncQueryIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
- spark/src/main/java/org/opensearch/sql/spark/rest/RestAsyncQueryManagementAction.java
- spark/src/main/java/org/opensearch/sql/spark/transport/TransportCreateAsyncQueryRequestAction.java
- spark/src/test/java/org/opensearch/sql/spark/transport/TransportCreateAsyncQueryRequestActionTest.java
* add new settings plugins.query.executionengine.async_query.enabled which disable submit async query to reject all coming requests.
https://github.com/opensearch-project/sql/issues/2507
> Add setting plugins.query.executionengine.async_query.enabled

- integ-test/src/test/java/org/opensearch/sql/ppl/PrometheusDataSourceCommandsIT.java
Switched to LocalDateTime for better handling of timezone and locale.
It uses system timezone irrespective of timezone set in JVM using `-Dtests.locale=hi-IN -Dtests.timezone=America/Atka`. 
Error before fix.
```
timestamp:२०२४-०२-१६ १०:१७:४७ in unsupported format
```
Following commands worked without error.
```
./gradlew ':integ-test:integTest' --tests "org.opensearch.sql.ppl.PrometheusDataSourceCommandsIT.testSourceMetricCommandWithTimestamp" -Dtests.seed=1574D2ADC54025EE -Dtests.security.manager=false -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP -Dtests.timezone=VST
```
```
./gradlew ':integ-test:integTest' --tests "org.opensearch.sql.ppl.PrometheusDataSourceCommandsIT.testSourceMetricCommandWithTimestamp" -Dtests.seed=EE70DA8B4C47EEC …
```
> Fix issue in testSourceMetricCommandWithTimestamp integ test with different timezones and locales.

- spark/src/main/antlr/SqlBaseParser.g4
- spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/CreateSessionRequest.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
- spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandlerTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
- spark/src/test/java/org/opensearch/sql/spark/rest/model/CreateAsyncQueryRequestTest.java
* Change EMR job names to following.
* Batch Query: `clustername:batch`
* Interactive Query: `clustername:interactive:sessionId`
* Index Streaming Query: `clustername:streaming:flint_my_glue_default_http_logs_elb_and_requesturi_index`
* Truncating jobname if length of it is greater than 255 characters.
* SparkQueryDispatcherTest.java and CreateAsyncQueryRequestTest.java refactoring.
> Change emr job names based on the query type

- spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
- spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
- spark/src/main/java/org/opensearch/sql/spark/client/StartJobRequest.java
- spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/CreateSessionRequest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParametersTest.java
- spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/client/StartJobRequestTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
1. Refactor SparkSubmitParameters
2. Move query param from `spark/src/main/java/org/opensearch/sql/spark/client/StartJobRequest.java` into `spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java` to avoid input limitation from EMRS
https://github.com/opensearch-project/sql/issues/2376
> Refactor query param

- docs/user/admin/settings.rst
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
* plugins.query.executionengine.spark.session.limit, 100 to 10
* plugins.query.executionengine.spark.refresh_job.limit, 20 to 5
* plugins.query.executionengine.spark.session.index.ttl, 14 day to 30 day
https://github.com/opensearch-project/sql/issues/2471
> Change async query default setting

- spark/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexQueryDetails.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
- spark/src/test/java/org/opensearch/sql/spark/flint/IndexQueryDetailsTest.java
- spark/src/test/resources/flint-index-mappings/0.1.1/flint_special_character_index.json
- spark/src/test/resources/flint-index-mappings/flint_special_character_index.json
Handle special characters when generating Flint index name by percent-encoding the invalid OpenSearch index name characters, since in some cases, sql queries (DROP, ALTER) are handled over here rather than forwarded to spark.
Same fix in opensearch-spark repo: https://github.com/opensearch-project/opensearch-spark/pull/215
* https://github.com/opensearch-project/opensearch-spark/issues/192
> Percent encode opensearch index name

- common/src/main/java/org/opensearch/sql/common/setting/Settings.java
- datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
- docs/user/admin/settings.rst
- legacy/src/main/java/org/opensearch/sql/legacy/metrics/MetricName.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
- spark/src/main/java/org/opensearch/sql/spark/cluster/ClusterManagerEventListener.java
- spark/src/main/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTask.java
- spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadata.java
- spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataServiceImpl.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
- spark/src/test/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTaskTest.java
- spark/src/test/resources/flint-index-mappings/flint_my_glue_mydb_http_logs_covering_error_index_mapping.json
- spark/src/test/resources/flint-index-mappings/flint_skipping_index.json
* This PR is to address running streaming jobs when a datasource is deleted/disabled. The idea is to run a cron for every 15 minutes(debatable) and check for hanging streaming jobs.
* When a datasource is deleted, we drop all the auto refresh indices.
* When a datasource is disabled, we alter the auto refresh indices to manual ones.
Documentation: https://github.com/vamsi-amazon/sql/blob/ss-jobs/docs/user/admin/settings.rst#pluginsqueryexecutionenginesparkstreamingjobshousekeeperinterval
```
PUT {{baseUrl}}/_cluster/settings
content-type: application/json
{
"transient" :{
"plugins.query.executionengine.spark.streamingjobs.housekeeper.interval":"2m"
}
}
```
```
{
"acknowledged": true,
"persistent": {},
"transient": {
"plugins": {
"query": {
"executionengine": {
"spark": {
"streamingjobs": …
```
> Stop Streaming Jobs When datasource is disabled/deleted.

- spark/src/main/java/org/opensearch/sql/spark/cluster/ClusterManagerEventListener.java
> FlintStreamingJobCleanerTask missing event listener

- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
Deleting created datasources to not conflict with other integration test classes. Still unsure why the issue is not caught in local plugin CI.
https://github.com/opensearch-project/sql/issues/2573
> Fix for dataSources Integ test issue.

- common/build.gradle
- core/build.gradle
- legacy/build.gradle
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParametersTest.java
Fix EMR spark submit parameter for batch FlintJob parsing issue when query contains quotes.
Ideally would like to test start job run in https://github.com/opensearch-project/sql/blob/main/spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java as well, but the AWSEMRServerless is mocked.
Manually ran end to end test connecting to a real EMR-S application for queries with nested quotes.
Example query:
```
CREATE INDEX test_cv
ON mys3.default.http_logs (`status`, `day`, `size`, `request` )
WITH (index_settings = '{"number_of_shards": 1 ,"number_of_replicas":1}', auto_refresh = true, checkpoint_location = 's3://test/')
```
This creates the index successfully.
The following tests special characters in a string get passed correctly.
```
CREATE INDEX test_special
ON …
```
> Bug Fix: Escape query in spark submit parameter

- docs/user/admin/settings.rst
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
- spark/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClient.java
- spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
- spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOp.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecAlterTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/MockFlintIndex.java
- spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
This PR handles different kinds of exception from EMRServerless when cancelling a job. There are frequent scenarios where the streaming job is already in cancelled state and resulting in error of ALTER INDEX command. This PR catches scenarios where the job is already in cancelled state and proceeds with the command execution.
* ResourceNotFoundException: When JobId is not present.
* ValidationException: When JobRun is not in a cancellable state.
* OtherExceptions.
* Fixed Datasources IT.
* Fixed Settings documentation: https://github.com/vamsi-amazon/sql/blob/emr-exception/docs/user/admin/settings.rst#pluginsqueryexecutionengineasync_queryenabled
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Handle EMR Exceptions in FlintCancelJob Operation

- common/build.gradle
- core/build.gradle
- legacy/build.gradle
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParametersTest.java
Backport 2bcf0b8b3371558a60200c8b994ee6de64ddcf6e from #2587
> [Backport 2.x] Bug Fix: Escape query in spark submit parameter (#2587)

- datasources/src/test/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorageTest.java
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
Removing old datasources model test as it is causing issues when running with security plugin. Load documents into system index requires superAdmin permissions and are not available while running integ tests against a rest cluster.
So introduced a unit test case which covers this usecase.
https://github.com/opensearch-project/sql/issues/2573
> Removing old datasources model integ test and added unit test.

- spark/src/main/antlr/SqlBaseLexer.g4
- spark/src/main/antlr/SqlBaseParser.g4
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
* Removed unnecessary DataSourceUserAuthorizationHelperImpl in SparkQueryDispatcher.
* Updated spark sql lib from upstream.
> Refactoring of SparkQueryDispatcher 

- spark/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
- spark/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
Handle EMRS exception as 400
https://github.com/opensearch-project/sql/issues/2611
> Handle EMRS exception as 400

- datasources/src/main/java/org/opensearch/sql/datasources/glue/GlueDataSourceFactory.java
- docs/user/ppl/admin/connectors/s3glue_connector.rst
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java
- spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Enables OpenSearch users to use LakeFormation option when querying the S3Glue data source.
This is important because some Glue tables are managed by LakeFormation. The customer will need to pass in a property for LakeFormation in order to not break backwards compataibility.
Note that this feature is launching in EMR serverless next month, so an error is thrown. Adding it in now so it's in the next release which is in line with the launch of this feature on EMR serverless.
Built locally with 2.13 as version and then copied over to cluster running 2.13.
__Validating that property is read and correct configuration is added to Spark config__
```shell
curl --request POST  --url http://localhost:9200/_plugins/_query/_datasources   --header 'content-type: application/x-ndjson'   --data '{"name": …
```
> Add option to use LakeFormation in S3Glue data source.

- spark/src/main/java/org/opensearch/sql/spark/dispatcher/QueryHandlerFactory.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Refactor SparkQueryDispatcher to reduce the direct dependency (pure refactoring).
* Extracted QueryHandlerFactory to remove constructor dependency to query hander classes and direct dependent classes.
* Reduced redundancy of code and improved readability.
N/A
> Refactor SparkQueryDispatcher

- .github/CODEOWNERS
- MAINTAINERS.md
Add new maintainer @ykmr1224 according to nominating voting from @vamsi-amazon @rupal-bq @ps48 @mengweieric @seankao-az following [becoming a maintainer](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#becoming-a-maintainer)
Welcome!
> Update maintainers list

- spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchStateStoreUtil.java
- spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexStateModelService.java
- spark/src/main/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexStateModelService.java
- spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOp.java
- spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpAlter.java
- spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpCancel.java
- spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpDrop.java
- spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpFactory.java
- spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuum.java
- spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecAlterTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/MockFlintSparkJob.java
- spark/src/test/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTaskTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/statestore/OpenSearchStateStoreUtilTest.java
- spark/src/test/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexStateModelServiceTest.java
- spark/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpTest.java
Introduce FlintIndexStateModelService to abstract the data storage.
N/A
> Introduce FlintIndexStateModelService

- spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/flint/IndexDMLResultStorageService.java
Added comments to async query handlers to make the responsibility of each handler clearer.
N/A
> Add comments to async query handlers

- spark/src/main/java/org/opensearch/sql/spark/dispatcher/QueryHandlerFactory.java
- spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
* Backport #2636 
* Automatic backport failed because of unit test failure due to change to the same class in different PR (#2624)
* For main branch, the same issue was solved in #2645
N/A
> [Backport 2.x] Refactor SparkQueryDispatcher (#2636)

- .github/workflows/integ-tests-with-security.yml
- .github/workflows/sql-test-and-build-workflow.yml
- integ-test/build.gradle
Bumps BWC version. Stops running CI checks on mac because artifacts are not available and those tests will always fail.
CI not being green 
> Bump bwc version to 2.15

- spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchSessionStorageService.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchStatementStorageService.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/SessionStorageService.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StatementStorageService.java
- spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionTestUtil.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/TestEMRServerlessClient.java
- spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
Extract SessionStorageService and StatementStorageService so that it can be used with other storage.
N/A
> Extract SessionStorageService and StatementStorageService

- spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchSessionStorageService.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchStatementStorageService.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/SessionStorageService.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statestore/StatementStorageService.java
- spark/src/main/java/org/opensearch/sql/spark/flint/FlintIndexStateModelService.java
- spark/src/main/java/org/opensearch/sql/spark/flint/IndexDMLResultStorageService.java
- spark/src/main/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexStateModelService.java
- spark/src/main/java/org/opensearch/sql/spark/flint/OpenSearchIndexDMLResultStorageService.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/model/MockFlintSparkJob.java
- spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
- spark/src/test/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexStateModelServiceTest.java
- Remove unneeded datasourceName parameters from accessor interfaces
- redundant parameters
> Remove unneeded datasourceName parameters

- spark/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- spark/src/main/java/org/opensearch/sql/spark/response/JobExecutionResponseReader.java
- spark/src/main/java/org/opensearch/sql/spark/response/OpenSearchJobExecutionResponseReader.java
- spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
- spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- spark/src/test/java/org/opensearch/sql/spark/response/OpenSearchJobExecutionResponseReaderTest.java
- Change JobExecutionResponseReader to an interface so that it can be replaced with another implementation.
n/a
> Change JobExecutionResponseReader to an interface

- spark/src/main/java/org/opensearch/sql/spark/execution/session/OpenSearchSessionConfigSupplier.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionConfigSupplier.java
- spark/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
- spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
- spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/session/SessionManagerTest.java
- spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
- Introduce SessionConfigSupplier to abstract settings (remove direct dependency on OpenSearch settings)
n/a
> Introduce SessionConfigSupplier to abstract settings

- legacy/src/main/java/org/opensearch/sql/legacy/esdomain/LocalClusterState.java
- legacy/src/test/java/org/opensearch/sql/legacy/unittest/LocalClusterStateTest.java
- legacy/src/test/java/org/opensearch/sql/legacy/util/CheckScriptContents.java
- legacy/src/test/java/org/opensearch/sql/legacy/util/MultipleIndexClusterUtils.java
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
This commit refactors the LocalClusterState singleton to instead access cluster state through the `org.opensearch.client.Client` abstract interface. 
- https://github.com/opensearch-project/OpenSearch/issues/13274
> Remove direct ClusterState access in LocalClusterState

- core/build.gradle
- core/src/main/java/org/opensearch/sql/expression/DSL.java
- core/src/main/java/org/opensearch/sql/expression/aggregation/AggregatorFunction.java
- core/src/main/java/org/opensearch/sql/expression/aggregation/PercentileApproximateAggregator.java
- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/test/java/org/opensearch/sql/expression/aggregation/PercentileApproxAggregatorTest.java
- core/src/test/java/org/opensearch/sql/planner/optimizer/LogicalPlanOptimizerTest.java
- docs/user/dql/aggregations.rst
- docs/user/ppl/cmd/stats.rst
- integ-test/src/test/java/org/opensearch/sql/ppl/StatsCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/AggregationIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/WindowFunctionIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/PercentilesParser.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/SinglePercentileParser.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/MetricAggregationBuilder.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilderTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/response/AggregationResponseUtils.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/response/OpenSearchAggregationResponseParserTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/MetricAggregationBuilderTest.java
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
- sql/src/main/antlr/OpenSearchSQLLexer.g4
- sql/src/main/antlr/OpenSearchSQLParser.g4
- sql/src/main/java/org/opensearch/sql/sql/parser/AstExpressionBuilder.java
- sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java
Backport https://github.com/opensearch-project/sql/pull/2688 manually and fix corresponding unit tests since the t-digest version in OpenSearch Core 2.x branch is 3.2. See https://github.com/opensearch-project/OpenSearch/blob/2.x/server/build.gradle#L99.
> [Backport 2.x] Support Percentile in PPL

- spark/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
- spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementState.java
- spark/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
- Add timeout StatementState
n/a
> Add timeout StatementState

- async-query-core/.gitignore
- async-query-core/build.gradle
- async-query-core/src/main/java/org/opensearch/sql/asyncquery/Dummy.java
- async-query-core/src/test/java/org/opensearch/sql/asyncquery/DummyTest.java
- async-query/.gitignore
- async-query/build.gradle
- async-query/src/main/java/org/opensearch/sql/asyncquery/DummyConsumer.java
- async-query/src/test/java/org/opensearch/sql/asyncquery/DummyConsumerTest.java
- settings.gradle
- Scaffold async-query-core and async-query module.
- async-query-core will include the core logic async-query without OpenSearch specific implementations
- async-query will include OpenSearch specific part such as data accessor using OpenSearch index.
- There are dummy classes and its tests to verify the dependency/build works. Those will be deleted when actual classes are moved from `spark` module in the next PR. (separated it to reduce the size of PR)
n/a
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin …
> Scaffold async-query-core and async-query module

- core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
- core/src/main/java/org/opensearch/sql/utils/SerializeUtils.java
- core/src/test/java/org/opensearch/sql/datasource/model/DataSourceTypeTest.java
- core/src/test/java/org/opensearch/sql/utils/SerializeUtilsTest.java
- datasources/src/main/java/org/opensearch/sql/datasources/exceptions/ErrorMessage.java
- datasources/src/test/java/org/opensearch/sql/datasources/exceptions/ErrorMessageTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorageTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportGetDataSourceActionTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/utils/XContentParserUtilsTest.java
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/ErrorFormatter.java
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
- spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSetting.java
- Change DataSourceType from enum to class, so that new type can be defined outside.
- Fixed serialization logics since the class was serialized like `{"name": "S3GLUE"}`. The custom Gson object serialize/deserialize it to/from `S3GLUE`.
n/a
- [] New functionality has javadoc added
- [] New functionality has user manual doc added
> Change DataSourceType from enum to class

- core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
- core/src/main/java/org/opensearch/sql/utils/SerializeUtils.java
- core/src/test/java/org/opensearch/sql/datasource/model/DataSourceTypeTest.java
- core/src/test/java/org/opensearch/sql/utils/SerializeUtilsTest.java
- datasources/src/main/java/org/opensearch/sql/datasources/exceptions/ErrorMessage.java
- datasources/src/test/java/org/opensearch/sql/datasources/exceptions/ErrorMessageTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorageTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/transport/TransportGetDataSourceActionTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/utils/XContentParserUtilsTest.java
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/ErrorFormatter.java
- spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryJobMetadata.java
- spark/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSetting.java
* [Backport 2.x] Change DataSourceType from enum to class
* Original auto backport had issue and this includes the revision for the code style fix.
n/a
> [Backport 2.x] Change DataSourceType from enum to class

- async-query-core/.gitignore
- async-query-core/build.gradle
- async-query-core/src/main/java/org/opensearch/sql/asyncquery/Dummy.java
- async-query-core/src/test/java/org/opensearch/sql/asyncquery/DummyTest.java
- async-query/.gitignore
- async-query/build.gradle
- async-query/src/main/java/org/opensearch/sql/asyncquery/DummyConsumer.java
- async-query/src/test/java/org/opensearch/sql/asyncquery/DummyConsumerTest.java
- settings.gradle
Signed-off-by: Tomoyuki Morita <moritato@amazon.com>
(cherry picked from commit 46015d41b5f6c83037534c8ba7deb3f6e332532d)
* Backport of #2733
> [Backport 2.x] Scaffold async-query-core and async-query module (#2733)

- core/src/main/java/org/opensearch/sql/datasource/model/DataSourceMetadata.java
- core/src/test/java/org/opensearch/sql/datasource/model/DataSourceMetadataTest.java
- datasources/src/main/java/org/opensearch/sql/datasources/service/DataSourceServiceImpl.java
- datasources/src/main/java/org/opensearch/sql/datasources/utils/XContentParserUtils.java
* Separate build and validateAndBuild method in DataSourceMetadata to let internally build special DataSourceMetadata.
* The validation doesn't allow datasource name starting from `_`(underscore) 
n/a
> Separate build and validateAndBuild method in DataSourceMetadata

- async-query-core/build.gradle
- settings.gradle
- Exclude integ-test, doctest and download task when built offline
- This is to make `async-query-core` module buildable in offline environment (it still requires Gradle cache)
- When built with `--offline` option, `integ-test` and `doctest` will be excluded, and also download of .g4 files are skipped. Even if we specify target such as `:async-query-core:shadowJar`, some downloads were done during preparation, and build failed even though `async-query-core` module does not depend on `integ-test`.
n/a
- [n/a] New functionality includes testing.
- [n/a] New functionality has javadoc added
For more information on following …
> Exclude integ-test and download task when built offline

- async-query-core/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImpl.java
- async-query-core/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/QueryHandlerFactory.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/metrics/EmrMetrics.java
- async-query-core/src/main/java/org/opensearch/sql/spark/metrics/MetricsService.java
- async-query-core/src/test/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImplTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- async-query/src/main/java/org/opensearch/sql/spark/metrics/OpenSearchMetricsService.java
- async-query/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- Abstract metrics to reduce dependency to legacy
n/a
> Abstract metrics to reduce dependency to legacy

- async-query-core/README.md
Add README to async-query-core
n/a
- [n/a] New functionality includes testing.
- [n/a] All tests pass, including unit test, integration test and doctest
- [n/a] New functionality has javadoc added
> Add README to async-query-core

- async-query-core/src/main/java/org/opensearch/sql/spark/flint/FlintIndexClient.java
- async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpFactory.java
- async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuum.java
- async-query-core/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpFactoryTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuumTest.java
- async-query/src/main/java/org/opensearch/sql/spark/flint/OpenSearchFlintIndexClient.java
- async-query/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- Abstract FlintIndex client to reduce the dependency from async-query-core to legacy
n/a
> Abstract FlintIndex client

- async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
- async-query-core/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
- async-query/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchSessionStorageService.java
- async-query/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchStatementStorageService.java
- Push down OpenSearch specific exception handling to reduce the dependency from `async-query-core` to `legacy`
n/a
> Push down OpenSearch specific exception handling

- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- Implement integration test for async-query-core
- This integration test intends to verify the end-to-end behavior at `async-query-core` library level, and that's why abstracted interfaces are mocked. The behavior with OpenSearch index is tested in `async-query` module.
- The integration test only covers major happy path and won't cover error handling, etc. Those would be covered by unit tests.
n/a
> Implement integration test for async-query-core

- async-query-core/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
- async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
- Fix SQLQueryUtils to extract multiple tables
- Originally had some issue where alias was also extracted as part of table name, and this change fixes it.
- This method will be used to identify datasources from the query.
n/a
> Fix SQLQueryUtils to extract multiple tables

- async-query-core/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactory.java
- async-query-core/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImpl.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/QueryHandlerFactory.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
- async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOp.java
- async-query-core/src/test/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImplTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecAlterTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
- async-query/src/test/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTaskTest.java
- async-query/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
- async-query/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
- Pass accountId to EMRServerlessClientFactory.getClient so that implementation of EMRServerlessClientFactory can decide the EMR cluster based on that.
n/a
> Pass accountId to EMRServerlessClientFactory.getClient

- .github/workflows/integ-tests-with-security.yml
- .github/workflows/sql-test-and-build-workflow.yml
CI is failing with 
```
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```
Added `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true` variable to use Node16
https://github.com/actions/checkout/issues/1809
> Fix checkout action failure

- docs/user/ppl/cmd/stats.rst
- integ-test/src/test/java/org/opensearch/sql/ppl/StatsCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/util/MatcherUtils.java
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
Below PPL query fails with `SyntaxCheckException`
```
source=opensearch_dashboards_sample_data_logs | stats COUNT() as cnt by response, span(timestamp, 1d)
```
This PR still keep the current behavior of `span` as the first grouping key. But allow the `span` being specified after fields in `statsByClause`. This fixing also could help on some LLM scenarios.
https://github.com/opensearch-project/sql/issues/2719
> Span in PPL statsByClause could be specified after fields

- async-query/src/main/java/org/opensearch/sql/spark/rest/RestAsyncQueryManagementAction.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- async-query/src/test/java/org/opensearch/sql/spark/rest/RestAsyncQueryManagementActionTest.java
- common/src/main/java/org/opensearch/sql/common/setting/Settings.java
- datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
- datasources/src/main/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorage.java
- datasources/src/test/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryActionTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/storage/OpenSearchDataSourceMetadataStorageTest.java
- docs/user/admin/settings.rst
- integ-test/src/test/java/org/opensearch/sql/asyncquery/AsyncQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceAPIsIT.java
- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceEnabledIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/util/RestRequestUtil.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/util/RestRequestUtilTest.java
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
This commit adds a setting that toggles data source management code paths.
It will disable explicit APIs and internal code paths that implicitly create data sources.
https://github.com/opensearch-project/OpenSearch/issues/13274
> Added Setting to Toggle Data Source Management Code Paths

- .github/workflows/integ-tests-with-security.yml
- .github/workflows/sql-pitest.yml
- .github/workflows/sql-test-and-build-workflow.yml
- .github/workflows/sql-test-workflow.yml
As we are using the AL2 image for OS plugin for linux now.
We need to fall back with older nodejs versions until AL2 deprecation next year.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
https://github.com/opensearch-project/opensearch-build/issues/4834
> Temp use of older nodejs version before moving to Almalinux8

- .github/workflows/integ-tests-with-security.yml
- .github/workflows/sql-test-and-build-workflow.yml
[Backport 2.x] Temp use of older nodejs version before moving to Almalinux8
Backport https://github.com/opensearch-project/sql/pull/2815
Closes https://github.com/opensearch-project/opensearch-build/issues/4834
> [Backport 2.x] Temp use of older nodejs version before moving to Almalinux8

- .github/workflows/integ-tests-with-security.yml
- .github/workflows/sql-test-and-build-workflow.yml
Due to https://github.com/opensearch-project/sql/pull/2815, some duplicate env variables were added, causing some yaml to be invalid and checks not to be run. This PR removes duplicates so that the actions run as expected. 
> Fix yaml errors causing checks not to be run

- async-query-core/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactory.java
- async-query-core/src/main/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImpl.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/QueryHandlerFactory.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/SessionManager.java
- async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOp.java
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/client/EMRServerlessClientFactoryImplTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecAlterTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
- async-query/src/test/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTaskTest.java
- async-query/src/test/java/org/opensearch/sql/spark/execution/session/InteractiveSessionTest.java
- async-query/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
Backport https://github.com/opensearch-project/sql/commit/e24b51fd392985bee4224f4c2a60d0dbe2a5e1b4 from https://github.com/opensearch-project/sql/pull/2783
As the original revision caused build error, this PR include fix for the error (in main branch, it was fixed in https://github.com/opensearch-project/sql/pull/2794)
> [Backport 2.x] Pass accountId to EMRServerlessClientFactory.getClient 

- .github/workflows/integ-tests-with-security.yml
- .github/workflows/sql-test-and-build-workflow.yml
MacOS build workflows were removed in https://github.com/opensearch-project/sql/pull/2662 because we don't have the M series artifacts. This PR addresses the artifact not found problem via replace `macos-latest` by `macos-13`.
`macos-13` is the MacOS version used in workflows of OpenSearch Core:
workflow failure
- [-] New functionality includes testing.
- [-] All tests pass, including unit test, integration test and doctest …
> Add MacOS workflows back and fix the artifact not found issue

- async-query-core/src/main/java/org/opensearch/sql/spark/parameter/SparkSubmitParametersBuilder.java
- async-query-core/src/test/java/org/opensearch/sql/spark/parameter/SparkSubmitParametersBuilderTest.java
* Fix SparkSubmitParameterModifier issue.
* It was causing null pointer exception when SparkSubmitParameterModifier was not set.
n/a
> Fix SparkSubmitParameterModifier issue

- docs/user/general/datatypes.rst
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataType.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchDateType.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilder.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LuceneQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/RangeQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/TermQuery.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataTypeTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/type/OpenSearchDateTypeTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilderTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LuceneQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/TermQueryTest.java
This change adds support for OpenSearch Date formats and custom date formats to be part of SQL Lucene queries. 
Without this change, we are supporting only list of selected formats which always gets formatted to ISO local string or epoch before submitting to opensearch dsl query. 
* Refactors `ExprType` to be `OpenSearchDateType` object instead of `ExprCoretype` enums  passed as a param to the Lucene QueryBuilder. 
* Extract `OpenSearchDateNamedFormatters` and `OpenSearchDateCustomFormatters` from the `OpenSearchDateType` object which is set during IndexMapping field parsing for a field type.
* Format information is passed to the `ExprValue` implementation constructor to parse the date string using the field specific formatters.
* Adds unit tests for all the different formats use cases. …
> Add support for custom date formats and OpenSearch date formats for date fields as part of Lucene query

- docs/user/general/datatypes.rst
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataType.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchDateType.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilder.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LuceneQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/RangeQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/TermQuery.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataTypeTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/type/OpenSearchDateTypeTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/OpenSearchIndexTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/aggregation/dsl/BucketAggregationBuilderTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/FilterQueryBuilderTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LuceneQueryTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/TermQueryTest.java
Backport of https://github.com/opensearch-project/sql/pull/2762
> [Backport 2.x] Add support for custom date formats and OpenSearch date formats for date fields as part of Lucene query

- async-query/src/main/java/org/opensearch/sql/spark/config/SparkExecutionEngineConfigClusterSetting.java
- Fix SparkExecutionEngineConfigClusterSetting deserialize issue
- GSON could use NoArgsConstructor / AllArgsConstructor when TypeAdapter is used to build GSON instance. 
- Fixed this back to default GSON since this class does not require custom handling.
n/a
- [n/a] New functionality includes testing.
- [n/a] New functionality has been documented.
- [n/a] New functionality has javadoc added
> Fix SparkExecutionEngineConfigClusterSetting deserialize issue

- release-notes/opensearch-sql.release-notes-2.16.0.0.md
Add release notes for OpenSearch 2.16.0 release.
https://github.com/opensearch-project/sql/issues/2748
> Add release notes for v2.16.0

- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceEnabledIT.java
The current check for .ql-datasources index creation is not feasible when security plugin is enabled due to restrictions on system index. Since there are other checks in place, I am removing the datasource index checks.
https://github.com/opensearch-project/sql/issues/2848
> Fix Integ test for datasource enabled setting with security plugin

- async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/model/AsyncQueryRequestContext.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- core/src/main/java/org/opensearch/sql/datasource/DataSourceService.java
- core/src/main/java/org/opensearch/sql/datasource/RequestContext.java
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTestBase.java
- datasources/src/main/java/org/opensearch/sql/datasources/service/DataSourceServiceImpl.java
- datasources/src/test/java/org/opensearch/sql/datasources/service/DataSourceServiceImplTest.java
- Add RequestContext parameter to verifyDataSourceAccessAndGetRawMetada method to allow async-query-core library user can use request context information when accessing data source data storage
n/a
> Add RequestContext parameter to verifyDataSourceAccessAndGetRawMetada method

- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceEnabledIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java
(cherry picked from commit 103c4160ae2a129284ff5be70bac40951e0c6a18)
> Fixed 2.16 integ test failures (#2871)

- docs/user/admin/settings.rst
- docs/user/optimization/optimization.rst
- docs/user/ppl/admin/settings.rst
- docs/user/ppl/interfaces/endpoint.rst
- integ-test/src/test/java/org/opensearch/sql/legacy/ExplainIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/setting/OpenSearchSettingsTest.java
The `plugins.query.size_limit` configure the maximum amount of rows returned by query. The default value is 200 which inherited from the legacy settings `opendistro.query.size_limit`. `200` is insufficient for many use cases which results incorrect outcomes. Check https://github.com/opensearch-project/sql/issues/2859 for more details.
This PR changes the default value of `plugins.query.size_limit` to the default value of `index.max_result_window` (10000 by default)
Resolves https://github.com/opensearch-project/sql/issues/2859
- [-] New functionality includes testing.
For more information on following Developer Certificate of Origin …
> Change the default value of plugins.query.size_limit to MAX_RESULT_WINDOW (10000)

- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/DatasourceEmbeddedQueryIdProvider.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/QueryIdProvider.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/DatasourceEmbeddedQueryIdProviderTest.java
- Add AsyncQueryRequestContext to QueryIdProvider parameter so implementation can utilize it to generate queryId
n/a
- [n/a] New functionality has been documented.
- [n/a] New functionality has a user manual doc added.
- [n/a] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [n/a] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#dev …
> Add AsyncQueryRequestContext to QueryIdProvider parameter

- integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceEnabledIT.java
Fixed integ tests issues with datasourceEnabledITs.
https://github.com/opensearch-project/sql/issues/2848
Tested using remote test cluster with docker.
```
docker pull opensearchstaging/opensearch:2.16.0.10131 && docker run -it -p 9200:9200 -e "discovery.type=single-node" -e 'OPENSEARCH_INITIAL_ADMIN_PASSWORD=myStrongPassword123!' opensearchstaging/opensearch:2.16.0.10131  -e "plugins.query.datasources.encryption.masterkey:99c6daa59300876ffbb6191f"
```
```
./gradlew integTestRemote -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername="docker-cluster" -Duser=admin -Dpassword=myStrongPassword123! -Dhttps=true
```
By submitting this pull request, I confirm that my contribution is made under the …
> Fixed integ test delete myindex issue and wipe All indices with security plugin.

- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
- integ-test/src/test/java/org/opensearch/sql/sql/GeopointFormatsIT.java
- integ-test/src/test/resources/geopoints.json
- integ-test/src/test/resources/indexDefinitions/geopoint_index_mapping.json
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/OpenSearchJsonContent.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/utils/OpenSearchJsonContentTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
Currently, we only support geo point in the format of an object with a latitude and longitude, this PR aims to expand our support to all common formats that are described in [OpenSearch doc](https://opensearch.org/docs/latest/field-types/supported-field-types/geo-point/).
#1432 
> Support common format geo point

- async-query-core/src/main/antlr/SqlBaseParser.g4
- Update SqlBaseParser.g4 file to solve build issue.
- The file was not valid and caused build issue in network disconnected environment.
- This change will align the file to `main` branch.
n/a
> [2.x] Update SqlBaseParser

- core/src/main/java/org/opensearch/sql/executor/Explain.java
- core/src/main/java/org/opensearch/sql/planner/DefaultImplementor.java
- core/src/main/java/org/opensearch/sql/planner/physical/PhysicalPlanDSL.java
- core/src/main/java/org/opensearch/sql/planner/physical/PhysicalPlanNodeVisitor.java
- core/src/main/java/org/opensearch/sql/planner/physical/SortHelper.java
- core/src/main/java/org/opensearch/sql/planner/physical/SortOperator.java
- core/src/main/java/org/opensearch/sql/planner/physical/TakeOrderedOperator.java
- core/src/test/java/org/opensearch/sql/executor/ExplainTest.java
- core/src/test/java/org/opensearch/sql/planner/DefaultImplementorTest.java
- core/src/test/java/org/opensearch/sql/planner/physical/PhysicalPlanNodeVisitorTest.java
- core/src/test/java/org/opensearch/sql/planner/physical/TakeOrderedOperatorTest.java
- docs/user/optimization/optimization.rst
- opensearch/src/main/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtector.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtectorTest.java
add TakeOrderedOperator 
https://github.com/opensearch-project/sql/issues/2857
> add TakeOrderedOperator

- integ-test/src/test/java/org/opensearch/sql/sql/AggregationIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/ScoreQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/util/MatcherUtils.java
- integ-test/src/test/java/org/opensearch/sql/util/TestUtils.java
1. Rounding difference between test results when run with different sources - added 2 digit precision round of for the failing tests. Sample test failure - 
```java.lang.AssertionError: 
Expected: (a collection containing [-6.12])
but: a collection containing [-6.12] mismatches were: [was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>, was <[-6.119999999999999]>]
at …
```
> [Tests] Test utils update to fix IT tests for serverless

- common/src/main/java/org/opensearch/sql/common/grok/GrokCompiler.java
- common/src/main/java/org/opensearch/sql/common/grok/GrokUtils.java
Regular expression `[A-z]` also matches the characters: `` [ \ ] ^ _ ` ``. It may have overly permissive range risk. Correct it with `[a-zA-Z_]`.
Resolves https://github.com/opensearch-project/sql/security/code-scanning/8
- [-] New functionality includes testing.
> Correct regular expression range

- core/src/main/java/org/opensearch/sql/planner/optimizer/LogicalPlanOptimizer.java
- core/src/main/java/org/opensearch/sql/planner/optimizer/pattern/Patterns.java
- core/src/main/java/org/opensearch/sql/planner/optimizer/rule/EvalPushDown.java
- core/src/test/java/org/opensearch/sql/planner/optimizer/LogicalPlanOptimizerTest.java
- integ-test/src/test/java/org/opensearch/sql/ppl/ExplainIT.java
- integ-test/src/test/resources/expectedOutput/ppl/explain_limit_push.json
Add a rule EvalPushDown.PUSH_DOWN_LIMIT, this rule will push down limit under eval. Thus, limit has chance to be pushed down into TableScanBuilder later.
e.g.
```
POST _plugins/_ppl/_explain
{
"query": """
source=opensearch_dashboards_sample_data_flights |  eval FlightMin = FlightTimeMin | head 5 | fields  FlightMin
"""
}
{
"root": {
"name": "ProjectOperator",
"description": {
"fields": "[FlightMin]"
},
"children": [
{
"name": "LimitOperator",
"description": {
"limit": 5,
"offset": 0
},
"children": [
{
"name": "EvalOperator",
"description": {
"expressions": {
"FlightMin": "FlightTimeMin"
}
},
"children": [
{
"name": "OpenSearchIndexScan",
"description": {
"request": """OpenSearchQueryRequest(indexName=opensearch_dashboards_sample_data_flights, …
```
> Push down limit through eval

- integ-test/src/test/java/org/opensearch/sql/legacy/CsvFormatResponseIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/CsvFormatIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/DedupCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/ParseCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/SortCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/ConditionalIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/CsvFormatIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/NestedIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/RawFormatIT.java
- integ-test/src/test/java/org/opensearch/sql/util/TestUtils.java
Some of the IT tests are failing in serverless even though data exist and functionality working as expected. RCA for such failures are sharding differences between data sources Leading to different ranking and different order in the schema fields in the response. 
1. So instead of hardcoding the expected schema order in the assertions, in this change I'm dynamically checking the schema names with its values during assertion to make sure if schema order is different in the responses due to different sharding difference, we are still able to check the correctness of the tests.
2. Sorting the data rows before assertion to make sure different data sources can have data in any order if sort is not applied and still have the correct data init.
Resolves #[Issue number to be closed when this PR …
> [Tests] IT tests and test utils update to fix failing tests for serverless

- async-query-core/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
- async-query-core/src/main/java/org/opensearch/sql/spark/parameter/SparkSubmitParameters.java
- async-query-core/src/main/java/org/opensearch/sql/spark/parameter/SparkSubmitParametersBuilder.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/parameter/SparkSubmitParametersBuilderTest.java
- async-query/src/main/java/org/opensearch/sql/spark/parameter/S3GlueDataSourceSparkParameterComposer.java
- async-query/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java
- async-query/src/test/java/org/opensearch/sql/spark/parameter/S3GlueDataSourceSparkParameterComposerTest.java
- core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
- datasources/src/main/java/org/opensearch/sql/datasources/glue/GlueDataSourceFactory.java
- datasources/src/main/java/org/opensearch/sql/datasources/glue/SecurityLakeDataSourceFactory.java
- datasources/src/test/java/org/opensearch/sql/datasources/glue/GlueDataSourceFactoryTest.java
- datasources/src/test/java/org/opensearch/sql/datasources/glue/SecurityLakeSourceFactoryTest.java
- docs/user/ppl/admin/connectors/s3glue_connector.rst
- docs/user/ppl/admin/connectors/security_lake_connector.rst
- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
Previously, Iceberg catalog was set as the default catalog. This poses problems as the behavior to fall back to default Spark catalog is only correct in some versions of Iceberg. Rather than always opt into Iceberg, Iceberg should be an option.
Additionally, the Lake Formation flag enabled Lake Formation for the EMR Serverless job, but this did not work as expected. Setting Lake Formation enabled for the entire EMR Serverless job result in EMR Serverless system space being used. This system space does not work with Flint. The full limitations are documented in https://docs.aws.amazon.com/emr/latest/EMR-Serverless-UserGuide/emr-serverless-lf-enable-considerations.html. Instead Lake Formation can be enabled using the Iceberg catalog implementation.
Built and deployed to cluster and then …
> Add flags for Iceberg and Lake Formation and Security Lake as a data source type.

- common/src/main/java/org/opensearch/sql/common/setting/Settings.java
- docs/dev/opensearch-pagination.md
- docs/user/admin/settings.rst
- integ-test/src/test/java/org/opensearch/sql/legacy/JoinIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/ElasticHitsExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/join/ElasticJoinExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/join/HashJoinElasticExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/join/NestedLoopsElasticExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/join/QueryPlanElasticExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/multi/MinusExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/multi/UnionExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/pit/PointInTimeHandler.java
- legacy/src/main/java/org/opensearch/sql/legacy/pit/PointInTimeHandlerImpl.java
- legacy/src/test/java/org/opensearch/sql/legacy/pit/PointInTimeHandlerImplTest.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
> Merge feature/pit branch to main

- legacy/src/main/java/org/opensearch/sql/legacy/cursor/DefaultCursor.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/cursor/CursorCloseExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/cursor/CursorResultExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/format/PrettyFormatRestExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/format/SelectResultSet.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/join/ElasticJoinExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/multi/MinusExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/pit/PointInTimeHandler.java
- legacy/src/main/java/org/opensearch/sql/legacy/pit/PointInTimeHandlerImpl.java
- legacy/src/main/java/org/opensearch/sql/legacy/query/DefaultQueryAction.java
- legacy/src/test/java/org/opensearch/sql/legacy/pit/PointInTimeHandlerImplTest.java
- legacy/src/test/java/org/opensearch/sql/legacy/unittest/cursor/DefaultCursorTest.java
- legacy/src/test/java/org/opensearch/sql/legacy/unittest/query/DefaultQueryActionTest.java
Added option to use search after with pit instead of scroll api for pagination query
https://github.com/opensearch-project/sql/issues/2603
Manual test on sample queries - https://github.com/opensearch-project/sql/issues/2941
> Add pit for pagination query

- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexQueryDetails.java
- async-query-core/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
- async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
- Add mvQuery attribute in IndexQueryDetails
- This is needed to extract fullyQualifiedTableName from CREATE MATERIALIZED VIEW query. (first extract the query then extract tableNames from the extracted query)
> Add mvQuery attribute in IndexQueryDetails

- async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorService.java
- async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/AsyncQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
- async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/Session.java
- async-query-core/src/main/java/org/opensearch/sql/spark/execution/statement/Statement.java
- async-query-core/src/main/java/org/opensearch/sql/spark/execution/statestore/StatementStorageService.java
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandlerTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- async-query/src/main/java/org/opensearch/sql/spark/execution/statestore/OpenSearchStatementStorageService.java
- async-query/src/main/java/org/opensearch/sql/spark/transport/TransportGetAsyncQueryResultAction.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecAlterTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecTest.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/IndexQuerySpecVacuumTest.java
- async-query/src/test/java/org/opensearch/sql/spark/execution/statement/StatementTest.java
- async-query/src/test/java/org/opensearch/sql/spark/transport/TransportGetAsyncQueryResultActionTest.java
- Add AsyncQueryRequestContext to update/get in StatementStorageService
- Passing through the AsyncQueryRequestContext from AsyncQueryExecutorService to Statement. Other changes are to pass down the parameter.
- [n/a] New functionality has been documented.
- [n/a] New functionality has a user manual doc added.
- [n/a] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [n/a] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
For more information on …
> Add AsyncQueryRequestContext to update/get in StatementStorageService

- async-query-core/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataValidator.java
- async-query-core/src/test/java/org/opensearch/sql/spark/flint/FlintIndexMetadataValidatorTest.java
- async-query/src/main/java/org/opensearch/sql/spark/flint/FlintIndexMetadataServiceImpl.java
- Extract validation logic from FlintIndexMetadataServiceImpl
- This is to make the validation logic usable for async-query-core library user
- [n/a] New functionality has been documented.
- [n/a] New functionality has a user manual doc added.
- [n/a] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [n/a] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
For more information on following Developer Certificate of Origin and signing off your commits, …
> Extract validation logic from FlintIndexMetadataServiceImpl

- async-query-core/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/StreamingQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/parameter/SparkSubmitParametersBuilder.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- Add queryId Spark parameter to batch query
- Spark will use this queryId to update the query status
https://github.com/opensearch-project/opensearch-spark/issues/602
> Add queryId Spark parameter to batch query

- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- async-query-core/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
- async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
- core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
Adds validation to allow only flint queries and sql select queries to security lake type datasource
Resolves #2907
> Adds validation to allow only flint queries and sql SELECT queries to security lake type datasource

- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/model/JobType.java
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- Fix handler for existing query
- We changed handler for CREATE INDEX with manual refresh to batch, but did not update the logic for get/cancel query. This lead to manual refresh job to be handled by RefreshQueryHandler
n/a
> Fix handler for existing query

- async-query-core/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- async-query/src/main/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposer.java
- async-query/src/main/java/org/opensearch/sql/spark/scheduler/parser/IntervalScheduleParser.java
- async-query/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- async-query/src/test/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposerTest.java
- async-query/src/test/java/org/opensearch/sql/spark/scheduler/parser/IntervalScheduleParserTest.java
- common/src/main/java/org/opensearch/sql/common/setting/Settings.java
- docs/user/admin/settings.rst
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/setting/OpenSearchSettingsTest.java
Add feature flag for async query scheduler, which will be passed to Flint to adjust scheduler mode 
Also fixed `:async-query:jacocoTestCoverageVerification` 
```
> Task :async-query:jacocoTestReport
> Task :async-query:jacocoTestCoverageVerification
```
https://github.com/opensearch-project/opensearch-spark/issues/622
> Add feature flag for async query scheduler

- async-query-core/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- async-query/src/main/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposer.java
- async-query/src/main/java/org/opensearch/sql/spark/scheduler/parser/IntervalScheduleParser.java
- async-query/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java
- async-query/src/test/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposerTest.java
- async-query/src/test/java/org/opensearch/sql/spark/scheduler/parser/IntervalScheduleParserTest.java
- common/src/main/java/org/opensearch/sql/common/setting/Settings.java
- docs/user/admin/settings.rst
- opensearch/src/main/java/org/opensearch/sql/opensearch/setting/OpenSearchSettings.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/setting/OpenSearchSettingsTest.java
1. Manual Backport https://github.com/opensearch-project/sql/commit/da622ebd6206b5215f0eceffbbe10218853d6d6d from https://github.com/opensearch-project/sql/pull/2973.
2. Fix type mismatch in [22ee2b3](https://github.com/opensearch-project/sql/pull/2989/commits/22ee2b390fbc0a5481bfda1c6595da47e84a9219)
> [Manual Backport 2.17] Add feature flag for async query scheduler

- integ-test/build.gradle
Fix `:integ-test:sqlBwcCluster#fullRestartClusterTask` on 2.x
Root cause:
Checked with build team, there's no 1.1.0 artifacts on S3 for all plugins (https://ci.opensearch.org/ci/dbc/distribution-build-opensearch). Hense use a different endpoint to fetch them `https://ci.opensearch.org/ci/dbc/bundle-build`
https://github.com/opensearch-project/sql/issues/2899
> Fix :integ-test:sqlBwcCluster#fullRestartClusterTask on 2.x

- release-notes/opensearch-sql.release-notes-2.17.0.0.md
Add release notes for OpenSearch 2.17.0 release.
* #2895 
> Add release notes for v2.17.0

- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/model/IndexQueryActionType.java
- async-query-core/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
- Throw exception for RECOVER INDEX JOB query
- RECOVER INDEX JOB query is intended to be executed directly to spark to recover aborted streaming job, and does not expect execution from SQL plugin/async-query-core.
n/a
> Throw exception for RECOVER INDEX JOB query

- async-query-core/src/main/java/org/opensearch/sql/spark/client/EmrServerlessClientImpl.java
- async-query-core/src/test/java/org/opensearch/sql/spark/client/EmrServerlessClientImplTest.java
- Throw IllegalArgumentException when cancelJob failed with ValidationException
- It is caused when the Job is not cancellable state such as FAILED or COMPLETED 
- This is to distinguish the error for 4xx and 5xx
n/a
> Throw IllegalArgumentException when cancelJob failed with ValidationException

- .github/workflows/integ-tests-with-security.yml
- .github/workflows/sql-test-and-build-workflow.yml
- async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpAlter.java
- async-query-core/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpDrop.java
- async-query-core/src/main/java/org/opensearch/sql/spark/scheduler/AsyncQueryScheduler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/scheduler/model/AsyncQuerySchedulerRequest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- async-query/src/main/java/org/opensearch/sql/spark/scheduler/OpenSearchAsyncQueryScheduler.java
- async-query/src/main/java/org/opensearch/sql/spark/scheduler/model/ScheduledAsyncQueryJobRequest.java
- async-query/src/main/java/org/opensearch/sql/spark/scheduler/parser/OpenSearchScheduleQueryJobRequestParser.java
- async-query/src/test/java/org/opensearch/sql/spark/scheduler/OpenSearchAsyncQuerySchedulerTest.java
- async-query/src/test/java/org/opensearch/sql/spark/scheduler/job/ScheduledAsyncQueryJobRunnerTest.java
- async-query/src/test/java/org/opensearch/sql/spark/scheduler/model/ScheduledAsyncQueryJobRequestTest.java
Backport/backport #3014 to 2.x
N/A
> [Manual Backport 2.x] Extend scheduler interface for multitenancy

- legacy/src/main/java/org/opensearch/sql/legacy/executor/format/PrettyFormatRestExecutor.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/join/ElasticJoinExecutor.java
- legacy/src/test/java/org/opensearch/sql/legacy/executor/format/PrettyFormatRestExecutorTest.java
Issue found during E2E testing:
1. If join queries fail to pull results due to internal errors in the service. The API fails with a Null Pointer Exception
Reproducible if you force the OpenSearch client to throw an exception while executing a join.
```
Before:
curl -X POST "http://localhost:9200/_plugins/_sql" -H 'Content-Type: application/json' -d'
> {
>   "query": "SELECT t1.field_1, t2.field_3 FROM testpit t1 INNER JOIN testjoin t2 ON t1.field_2 = t2.field_4"
> }
> '
{
"error": {
"reason": "There was internal problem at backend",
"details": "Cannot invoke \"java.util.List.size()\" because \"this.results\" is null",
"type": "NullPointerException"
},
"status": 500
}
After fix:
curl -X POST "http://localhost:9200/_plugins/_sql" -H 'Content-Type: application/json' -d'
{
"query": "SELECT …
```
> Bug Fixes for minor issues with SQL PIT refactor

- .github/CODEOWNERS
- MAINTAINERS.md
Welcoming new maintianer @noCharger 
> Adding new maintainer @noCharger

- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/sql/PaginationIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/format/SelectResultSet.java
Alias query in legacy SQL  which had filters to it didn't work . This diff addresses that issue. This diff derives index name from alias, for  legacy sql queries having filters to it. 
Before the change
```
curl -X POST "localhost:9200/_plugins/_sql" -H 'Content-Type: application/json' -d '{
"query": "SELECT * FROM my-alias",
"fetch_size": 1,
"filter" : {
"term" : {
"field2" : "Sample keyword2"
}
}
}'
{
"error": {
"reason": "There was internal problem at backend",
"details": "Index type [my-alias] does not exist",
"type": "IllegalArgumentException"
},
"status": 500
}
```
After the change: 
```
curl -X POST "localhost:9200/_plugins/_sql" -H 'Content-Type: application/json' -d '{
"query": "SELECT * FROM my-alias",
"fetch_size": 1,
"filter" : {
"term" : {
"another_field" : "hello"
}
}
}'
{ …
```
> Resolve Alias Issues in Legacy SQL with Filters

- integ-test/src/test/java/org/opensearch/sql/legacy/CursorIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/PaginationIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/cursor/CursorResultExecutor.java
Malformed cursors currently return a 500 status with exception messages -- this PR updates it to a tidier message with a 400 status.
N/A
> Improve error handling for malformed query cursors

- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/InteractiveQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/response/JobExecutionResponseReader.java
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- async-query/src/main/java/org/opensearch/sql/spark/response/OpenSearchJobExecutionResponseReader.java
- async-query/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryGetResultSpecTest.java
- async-query/src/test/java/org/opensearch/sql/spark/response/OpenSearchJobExecutionResponseReaderTest.java
1. updating the signature of JobExecutionResponseReader interface
2. updating signature from `JSONObject getResultWithJobId(String jobId, String resultLocation)` to `getResultFromResultIndex(
AsyncQueryJobMetadata asyncQueryJobMetadata,
AsyncQueryRequestContext asyncQueryRequestContext)`
3. adding in AsyncQueryRequestContext in getResultWithQueryId method
na
> Updating JobExecutionResponseReader interface to add RequestContext

- integ-test/src/test/java/org/opensearch/sql/ppl/ResourceMonitorIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/executor/protector/ResourceMonitorPlan.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/monitor/OpenSearchMemoryHealthy.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/executor/ResourceMonitorPlanTest.java
I am running into this circuit breaker in https://github.com/opensearch-project/opensearch-api-specification/issues/468 and the logs contain some difficult to understand text. 
> Fix grammar in log warnings.

- .github/workflows/sql-test-and-build-workflow.yml
- integ-test/src/test/java/org/opensearch/sql/legacy/CursorIT.java
Makes linux test failures more visible by splitting out the failing BWC tests to their own action. I'm not sure how to fix the BWC tests, I've been told they start failing semi-regularly due to external factors so it seems like it's a wise decision to keep it separate from more reliable tests.
N/A
> Refactor test workflow to separate bwc tests

- async-query/build.gradle
- datasources/build.gradle
- spark/build.gradle
bump commons-io to 2.14.0
Resolves #3055 
CVE-2024-47554
> bump commons-io to 2.14.0

- plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java
Remove scheduler index from SystemIndexDescriptor
> Remove scheduler index from SystemIndexDescriptor

- integ-test/src/test/java/org/opensearch/sql/legacy/MalformedQueryIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/query/OpenSearchActionFactory.java
- legacy/src/main/java/org/opensearch/sql/legacy/rewriter/matchtoterm/TermFieldRewriter.java
Improves error handling for some types of malformed SQL queries.
N/A
> Improve error handling for some more edge cases

- integ-test/src/test/java/org/opensearch/sql/legacy/MalformedQueryIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/query/OpenSearchActionFactory.java
- legacy/src/main/java/org/opensearch/sql/legacy/rewriter/matchtoterm/TermFieldRewriter.java
Need to manually backport #3080 because the h5 library isn't available on 2.x (but is on main), so the tests don't compile when doing a trivial copy.
N/A
> [Manual Backport] Improve error handling for some more edge cases (#3080)

- release-notes/opensearch-sql.release-notes-2.18.0.0.md
Add release notes for OpenSearch 2.18.0 release.
https://github.com/opensearch-project/sql/issues/3000
> Add release notes for v2.18.0

- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java
- async-query-core/src/main/java/org/opensearch/sql/spark/validator/SQLQueryValidator.java
- async-query-core/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/validator/SQLQueryValidatorTest.java
Adds a new method to validate a Flint extension query in the SQLQueryValidator. The method is a no-op currently. Wire this call into the dispatcher.
> Add validation method for Flint extension queries and wire it into the dispatcher

- async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImpl.java
- async-query-core/src/main/java/org/opensearch/sql/spark/asyncquery/AsyncQueryJobMetadataStorageService.java
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplTest.java
- async-query/src/main/java/org/opensearch/sql/spark/asyncquery/OpenSearchAsyncQueryJobMetadataStorageService.java
- Call updateState when query is cancelled
- This change is for async-query-core library consumer to update cancel status
- This does not affect the async-query behavior since AsyncQueryJobMetadata record does not store status yet. (#3140 is an issue for unifying the model to single one, and we need to handle the update status within the fix)
#3140 (This PR does not solve this issue)
> Call updateState when query is cancelled

- docs/user/admin/settings.rst
- docs/user/limitations/limitations.rst
- doctest/test_data/multi_value_long.json
Add documentation for the `plugins.query.field_type_tolerance` setting.
Resolves #1300
> Added documentation for the plugins.query.field_type_tolerance setting (#1300)

- core/src/main/java/org/opensearch/sql/planner/physical/collector/Rounding.java
- core/src/test/java/org/opensearch/sql/planner/physical/collector/RoundingTest.java
- integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeImplementationIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFormatsIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
This seems a regression issue from https://github.com/opensearch-project/sql/pull/2762. Query of StatsBy with Span on a custom formatted date type will fail.
Here is the reproduce:
```
PUT /ltjin-test1
{
"mappings":{
"Time1": {
"type": "date",
"format": "yyyy-MM-dd"
},
"Time2": {
"type": "date",
"format": "epoch_millis"
}
}
}
}
POST _bulk
{ "index" : { "_index" : "ltjin-test1", "_id" : "1" } }
{ "Time1": "2005-12-05", "Time2": 1133654400000 }
POST /_plugins/_ppl/
{
"query": """
source=ltjin-test1 | eval a = 1 | stats Count(a) as a by span(Time1, 1d)
"""
}
POST /_plugins/_ppl/
{
"query": """
source=ltjin-test1 | eval a = 1 | stats Count(a) as a by span(Time2, 1d)
"""
}
```
Throws NPE.
Resolves #3078 
By submitting this pull request, I confirm that my contribution is made …
> Fix a regression issue of parsing datetime string with custom time format in Span

- core/src/main/java/org/opensearch/sql/planner/physical/collector/Rounding.java
- core/src/test/java/org/opensearch/sql/planner/physical/collector/RoundingTest.java
- integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeImplementationIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
(cherry picked from commit 4ff1fe3cb48a17ff17b0cf134131283fc0282205)
> [Backport 2.x] Fix a regression issue of parsing datetime string with custom time format in Span (#3079)

- protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseBase.java
- Fix coverage issue for #3063
- `cell` parameter in `quoteIfRequired` won't be `null` since:
- getOriginalData method convert `null` value to `""`
- getOriginalHeaders method does not accept `null` column value when adding to ImmutableList
n/a
> Fix coverage issue for #3063

- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java
- async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- async-query/src/main/java/org/opensearch/sql/spark/execution/statestore/StateStore.java
- async-query/src/main/java/org/opensearch/sql/spark/leasemanager/DefaultLeaseManager.java
- async-query/src/test/java/org/opensearch/sql/spark/leasemanager/DefaultLeaseManagerTest.java
- Call LeaseManager for BatchQuery
- Currently, LeaseManager.borrow is not called for BatchQuery
n/a
> Call LeaseManager for BatchQuery

- async-query-core/src/main/java/org/opensearch/sql/spark/validator/GrammarElement.java
- async-query-core/src/main/java/org/opensearch/sql/spark/validator/S3GlueGrammarElementValidator.java
- async-query-core/src/main/java/org/opensearch/sql/spark/validator/SQLQueryValidationVisitor.java
- async-query-core/src/test/java/org/opensearch/sql/spark/validator/SQLQueryValidatorTest.java
- Update grammar validation settings
- Deny-list bitwise function for S3Glue
- Generator function enum is added for other datasource.
n/a
> Update grammar validation settings

- integ-test/src/test/java/org/opensearch/sql/legacy/CursorIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/executor/format/DateFieldFormatter.java
- legacy/src/test/java/org/opensearch/sql/legacy/executor/format/DateFieldFormatterTest.java
This is a MR, which aim to fix the issue described over https://github.com/opensearch-project/sql/issues/1545 to align the representation of `date` field between the legacy engine and the v2 engine. 
Code changes highlight:
- Remove the `break` identifier from `DateFieldFormatter`, the current behaviour will only parse the first `date` field from the resultSet, which is not a valid assumption, because OpenSearch as platform allow multiple `date` fields co-exist on an index, also this is not an uncommon use-case for enterprise. Hence all `date` fields present on any given index should be formatted regardless of the order.
- To detect and attempt parse any unix timestamp (second || milisecond) on best-effort basis, OpenSearch as platform allow unix timestamp value to be inserted despite …
> Fix: Date field format parsing for legacy query engine 

- .github/workflows/integ-tests-with-security.yml
- .github/workflows/sql-pitest.yml
- .github/workflows/sql-test-and-build-workflow.yml
- .github/workflows/sql-test-workflow.yml
To introduce additional start command for all CI build which rely on the OpnSearch Docker image, as Github rollout the deprecation of the Node 16 on all it's CI-runner, as the result all existing Github which rely on the old version of Node.JS (Ex: actions/checkout@v3) failed due to the following errors:
```
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```
The issue has been discovered over https://github.com/opensearch-project/opensearch-build/issues/5178 and fix has been verified and  applied on multiple OpenSearch plugin, such as: 
- https://github.com/opensearch-project/ml-commons/pull/3223
- …
> Fix: CI Github Action 

- core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
- core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
- core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java
- core/src/main/java/org/opensearch/sql/ast/tree/FillNull.java
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
- docs/category.json
- docs/user/ppl/cmd/fillnull.rst
- integ-test/src/test/java/org/opensearch/sql/ppl/ExplainIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/FillNullCommandIT.java
- integ-test/src/test/resources/expectedOutput/ppl/explain_fillnull_push.json
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
- ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
- ppl/src/test/java/org/opensearch/sql/ppl/antlr/PPLSyntaxParserTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
Adds the FILLNULL command for PPL. FILLNULL will replace NULL values in specified fields.
Resolves #3032
Based on this PR for Spark: https://github.com/opensearch-project/opensearch-spark/pull/723
- [Y] New functionality includes testing.
- [Y] New functionality has been documented.
- [Y] New functionality has javadoc added.
- [Y] New functionality has a user manual doc added.
- [N/A] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [Y] Commits are signed per the DCO using `--signoff`.
- [Y] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
By submitting this pull request, I confirm that my contribution is made under the …
> Add FILLNULL command in PPL (#3032)

- .github/workflows/bi-connectors.yml
- .github/workflows/sql-cli-test-and-build-workflow.yml
- .github/workflows/sql-jdbc-test-and-build-workflow.yml
- .github/workflows/sql-odbc-main.yml
- .github/workflows/sql-test-and-build-workflow.yml
- .github/workflows/sql-test-workflow.yml
- build.gradle
Update Spring to latest patch to quiet CVE scanners.
N/A
> chore: Update Spring to 5.3.39

- build.gradle
Backport #3187 to 1.3
I realize in hindsight that I probably should have gone to 1.3 directly instead of trying to go through 1.x, this branch is much more up-to-date.
N/A
> Backport #3187 to 1.3

- core/src/main/java/org/opensearch/sql/planner/physical/FilterOperator.java
- core/src/test/java/org/opensearch/sql/planner/physical/FilterOperatorTest.java
- integ-test/src/test/resources/correctness/bugfixes/3121.txt
This PR addresses a bug in FilterOperator where repeated calls to hasNext() would incorrectly consume input elements. The change includes
* Updated FilterOperator to cache the next matching element, ensuring that repeated hasNext() calls return true without advancing the input.
* Unit Tests: Added a test case to confirm that inputPlan.next() is called only once across multiple hasNext() calls, preventing unintended input consumption.
* IT, `SELECT Origin, Dest FROM (SELECT * FROM opensearch_dashboards_sample_data_flights WHERE AvgTicketPrice > 100 GROUP BY Origin, Dest, AvgTicketPrice) AS flights WHERE AvgTicketPrice < 1000 ORDER BY AvgTicketPrice LIMIT 30`
https://github.com/opensearch-project/sql/issues/3121
By submitting this pull request, I confirm that my contribution is made under …
> Fix FilterOperator to cache next element and avoid repeated consumption on hasNext() calls

- async-query-core/src/main/java/org/opensearch/sql/spark/validator/SQLQueryValidationVisitor.java
- async-query-core/src/test/java/org/opensearch/sql/spark/validator/SQLQueryValidatorTest.java
- Add validation for unsupported type/identifier/commands
- Those grammars are defined but considered unsupported
https://github.com/opensearch-project/sql/issues/3185
> Add validation for unsupported type/identifier/commands

- .github/workflows/stalled.yml
Copies the stalled PR workflow from OS core: https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/stalled.yml
N/A
> Add stalled PRs workflow

- .github/ISSUE_TEMPLATE/request_of_comments.md
Aim to provide a handy Github issue template for RFC, in order to standardize the existing feature intake process, to encourage contributors to submit a RFC when doing any major feature to get the consent / alignment from the community, in order to lower the risk / complexity of the implementation. 
Existing Github template:
N/A
> Doc: Proposed RFC Github issue template

- .github/workflows/sql-test-and-build-workflow.yml
Not all subprojects need to be executed sequentially. We can build subprojects in parallel to speed up the CI workflow.
Resolves https://github.com/opensearch-project/sql/issues/3226
> Build subprojects in parallel

- core/src/test/java/org/opensearch/sql/expression/datetime/ExtractTest.java
- docs/user/dql/functions.rst
Flaky test:
```
ExtractTest > testExtractDatePartWithTimeType() FAILED
org.opentest4j.AssertionFailedError: expected: <53> but was: <1>
at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:635)
at app//org.opensearch.sql.expression.datetime.ExtractTest.datePartWithTimeArgQuery(ExtractTest.java:90)
at …
```
> Fix the flaky test testExtractDatePartWithTimeType()

- .github/workflows/codeql-analysis.yml
- .github/workflows/integ-tests-with-security.yml
- .github/workflows/sql-test-and-build-workflow.yml
Backport PR raised by `opensearch-trigger-bot` (e.g. https://github.com/opensearch-project/sql/pull/2842) will trigger duplicated workflows which wastes CI resources.
n/a
- [-] New functionality includes testing.
- [-] All tests pass, including unit test, integration test and doctest
- [-] Commits are signed per the DCO using --signoff 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certific …
> Dedup running workflows on push action with auto-backport

- .github/workflows/sql-test-and-build-workflow.yml
Reverts opensearch-project/sql#3223 because the async-query module compiling could fail sometimes.
```
> Task :async-query:compileJava FAILED
> Task :async-query-core:compileTestJava FAILED
```
> Revert "Build subprojects in parallel"

- core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java
- docs/user/ppl/general/identifiers.rst
- integ-test/src/test/java/org/opensearch/sql/ppl/FieldsCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/WhereCommandIT.java
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
OpenSearch reserved fields (_id, _index, _sort, _score, _max_score) are not allowed to be used in PPL clauses because the field format starting with underscore _ is not allowed.
- This ticket adds specific identifiers to the language, and opens up support for OpenSearch reserved identifiers.
- As an aside, identifiers with double underscore at the start (such as __myCoolField) is acceptable as an identifier.
https://github.com/opensearch-project/sql/pull/1456 had fixed the same problem for SQL query, but the issue still existed in PPL.
Resolves https://github.com/opensearch-project/sql/issues/2788
For more information on following Developer Certificate of Origin and signing …
> Allow metadata fields in PPL query

- .github/workflows/sql-test-and-build-workflow.yml
Adding java version to the name of artifact to avoid conflicts in CI workflow. (Align with main branch)
Resolves #3238 
> [2.x] Artifacts to upload should include the java version in its name to avoid conflicts

- docs/user/ppl/general/identifiers.rst
Followup of https://github.com/opensearch-project/sql/pull/2789. Fix the doctest failure which was success in the previous doctest some time ago.
(No need to backport to 2.x)
Resolves https://github.com/opensearch-project/sql/issues/2788
> [Followup] Fix the doctest failure

- release-notes/opendistro-for-elasticsearch-sql.release-notes-1.6.0.0.md
URL  `https://github.com/opendistro-for-elasticsearch/sql-jdbc/issues/57` no longer return a proper HTTP redirect response, but return 404 instead.
At this stage we suspect there are some internal || JS level redirect happen, as if user enter the same url on browser, redirect continues to happen correctly to `https://github.com/amazon-archives/sql-jdbc/issues/57`
Hence this PR is to propose the url change in order to fix the build.
> CI: Fix broken url for link-checker CI build

- integ-test/build.gradle
As per the discussion from https://github.com/opensearch-project/OpenSearch/issues/3615, the next major version (3.0.0-SNAPSHOT) is only API compat w/ the last minor of the previous major, hence bumping variable `baseversion` to make sure the test-cases for mixed cluster (`mixedClusterTask` and `rollingUpgradeClusterTask`) pass.
Partially resolve: https://github.com/opensearch-project/sql/issues/3168, https://github.com/opensearch-project/sql/issues/3184
> CI: BWC testsuite

- docs/dev/datasource-prometheus.md
Missing close curly brace on `datasource-prmetheus.md` which result in Jeykll build fail at the moment on main branch.
https://github.com/opensearch-project/sql/actions/runs/12890965970/job/35941801363
Partial resolves: https://github.com/opensearch-project/sql/issues/3168
> CI: Syntax fix for Jekyll build

- core/src/main/java/org/opensearch/sql/data/type/ExprType.java
- core/src/main/java/org/opensearch/sql/expression/ReferenceExpression.java
- core/src/test/java/org/opensearch/sql/data/type/ExprTypeTest.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
- integ-test/src/test/java/org/opensearch/sql/ppl/DataTypeIT.java
- integ-test/src/test/resources/alias.json
- integ-test/src/test/resources/indexDefinitions/alias_index_mapping.json
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchAliasType.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataType.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataTypeTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilderTest.java
- opensearch/src/test/resources/mappings/accounts.json
Add Support for OpenSearch alias type, so PPL can query fields of alias type correctly. 
Implementation:
- Add a new ExprType named `OpenSearchAliasType`
- Add special parsing logic for alias type in `OpenSearchDataType::parseMapping`
- Use original path and type when constructing `ReferenceExpression`. For now, only alias type will have different original path and type.
- When constructing `_source` in `OpenSearchRequestBuilder::pushDownProjects`, use path instead of attr since they are different for alias type. The former one is more accurate since OpenSearch don't accept fields of alias type in `_source`.
e.g. After this PR:
```
PUT /try
{
"mappings":{
"time1": {
"type": "date"
},
"time2": {
"type": "alias",
"path": "time1"
}
}
}
}
POST try/_doc
{
"time1": 1736911491131 …
```
> Support for OpenSearch alias type 

- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFormatterUtil.java
- core/src/test/java/org/opensearch/sql/expression/datetime/StrToDateTest.java
- integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/DateTimeFunctionIT.java
Signed-off-by: Lantao Jin <ltjin@amazon.com>
(cherry picked from commit 4224f318871d4bf8cb35764fb7f589530449a0de from #2841 )
> [Backport 2.x] Function `str_to_date` should work with two-digits year

- integ-test/build.gradle
To eliminate redundant casting for `RegularFile` usage, which the aim to enhance the readability of Gradle build file. 
Related to: https://github.com/opensearch-project/sql/issues/3257
Both integTestWithSecurity and bwcTestSuite should continue to work after the refactor.
> CI: Eliminate redundant file wrapper 

- docs/user/ppl/cmd/parse.rst
Update PPL documentation to clarify the missing field issue below in `Limitations` section.
https://github.com/opensearch-project/sql/issues/3265
> Update PPL parse command doc with limitation

- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunctions.java
- core/src/test/java/org/opensearch/sql/expression/datetime/ExtractTest.java
Updated `w` formatting for dates to use ISO-8601 behaviour.
Issue:  `extract(week from <date>)` returns the number of weeks in the year based on the DateTimeFormatter which uses 'en' locale.  
Expected: `extract(week from <date>)` returns the number of weeks in the year based on the ISO-1868 week-of-week-based-year.  
Resolves #2477 
> Fixed week of week based year handling

- release-notes/opensearch-sql.release-notes-2.19.0.0.md
[Release 2.19] Add release notes for 2.19
* Relate https://github.com/opensearch-project/sql/issues/3134
> [Release 2.19] Add release notes for 2.19

- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunction.java
- core/src/test/java/org/opensearch/sql/expression/datetime/ExtractTest.java
Signed-off-by: Norman Jordan <norman.jordan@improving.com>
(cherry picked from commit 7d9f6bdeb8e74832065b2db03e5ded98585241eb)
Fix the backport of 7d9f6bdeb8e74832065b2db03e5ded98585241eb
Relates to #2477
> [Backport 2.x] Fixed week of week based year handling (#3299)

- core/src/main/java/org/opensearch/sql/data/type/ExprType.java
- core/src/main/java/org/opensearch/sql/expression/ReferenceExpression.java
- core/src/test/java/org/opensearch/sql/data/type/ExprTypeTest.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
- integ-test/src/test/java/org/opensearch/sql/ppl/DataTypeIT.java
- integ-test/src/test/resources/alias.json
- integ-test/src/test/resources/indexDefinitions/alias_index_mapping.json
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchAliasType.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataType.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/type/OpenSearchDataTypeTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilderTest.java
- opensearch/src/test/resources/mappings/accounts.json
Backport [PR3246](https://github.com/opensearch-project/sql/pull/3246) to 2.x
> [Backport 2.x]Support for OpenSearch alias type

- async-query/build.gradle
- build.gradle
- common/build.gradle
- core/build.gradle
- datasources/build.gradle
- integ-test/build.gradle
- legacy/build.gradle
- opensearch/build.gradle
- plugin/build.gradle
- ppl/build.gradle
- prometheus/build.gradle
- protocol/build.gradle
- spark/build.gradle
- sql/build.gradle
This PR aims to centralise certain dependencies which are commonly used across the project, and also **serve as a perquisites to eventually migrate all versions declaration to Gradle version catalog**, in order to avoid version conflict in the future, as the project codebase grows. 
NO breaking change would be expected, as there is NO version upgrade || downgrade happen on any of the dependencies at this point. 
Related to: https://github.com/opensearch-project/sql/issues/3257
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certifica …
> Build: Centralise dependencies version - Pt1

- core/src/main/java/org/opensearch/sql/calcite/CalcitePlanContext.java
- core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
- core/src/main/java/org/opensearch/sql/calcite/OpenSearchSchema.java
- core/src/main/java/org/opensearch/sql/calcite/plan/OpenSearchTable.java
- core/src/main/java/org/opensearch/sql/executor/QueryService.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/executor/OpenSearchExecutionEngine.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexEnumerator.java
Before this PR, PPL plan will fail executing on calcite engine and fallback to the original v2 engine. This PR aims to make the plan execute successfully on calcite engine. 
The changes includes:
- Replace RelRunners with CalciteConnection to do execution
- Add OpenSearchSchema to the rootSchema of above connection
- Change ExprValue to Object in OpenSearchTable
> [POC] Make PPL execute successfully on Calcite engine

- async-query-core/src/main/java/org/opensearch/sql/spark/validator/FunctionType.java
- async-query-core/src/main/java/org/opensearch/sql/spark/validator/SQLGrammarElement.java
- async-query-core/src/main/java/org/opensearch/sql/spark/validator/SQLQueryValidationVisitor.java
- async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/validator/FunctionTypeTest.java
- async-query-core/src/test/java/org/opensearch/sql/spark/validator/SQLQueryValidatorTest.java
- Add other(uncategorized) functions to SQL query validator
- Those functions were originally not covered since it was not listed in [categorized list](https://spark.apache.org/docs/3.5.3/sql-ref-functions.html) , but actually documented in [full list](https://spark.apache.org/docs/3.5.3/api/sql/).
Resolves #3237
> Add other functions to SQL query validator

- async-query-core/build.gradle
- async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- Remove dependency from async-query-core to datasources
n/a
> Remove dependency from async-query-core to datasources

- core/src/main/java/org/opensearch/sql/calcite/CalcitePlanContext.java
- core/src/main/java/org/opensearch/sql/calcite/plan/OpenSearchTable.java
- core/src/main/java/org/opensearch/sql/calcite/plan/OpenSearchTableScan.java
- core/src/main/java/org/opensearch/sql/executor/QueryService.java
- opensearch/build.gradle
- opensearch/src/main/java/org/opensearch/sql/opensearch/executor/OpenSearchExecutionEngine.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchFilterIndexScanRule.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchIndexRules.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/OpenSearchProjectIndexScanRule.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilder.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteOpenSearchIndexScan.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexEnumerator.java
Push down project and filter operator into index scan. This PR includes change:
1. `OpenSearchIndex` change to use its specific scan operator, `CalciteOpenSearchIndexScan`
2. Simplify to use `RelRunners` to do execution since the current implementation of `CalciteOpenSearchIndexScan` does not require a "schema" as context.
3. Add `OpenSearchFilterIndexScanRule` and `OpenSearchProjectIndexScanRule` to do filter/project operator push down.
4. Add `PredicateAnalyzer` to build `QueryBuilder` for filter condition.
Part Resolves https://github.com/opensearch-project/sql/issues/3331
For more information on following Developer Certificate of Origin and signing off your commits, …
> [Calcite Engine] Push down project and filter operator into index scan

- core/src/main/java/org/opensearch/sql/calcite/utils/OpenSearchTypeFactory.java
- core/src/main/java/org/opensearch/sql/executor/OpenSearchTypeSystem.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLSortIT.java
Followup of https://github.com/opensearch-project/sql/pull/3342 : Register OpenSearchTypeSystem to OpenSearchTypeFactory
> Followup: Register OpenSearchTypeSystem to OpenSearchTypeFactory

- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLJoinIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
- integ-test/src/test/resources/hobbies.json
- integ-test/src/test/resources/indexDefinitions/hobbies_index_mapping.json
- integ-test/src/test/resources/indexDefinitions/occupation_index_mapping.json
- integ-test/src/test/resources/indexDefinitions/state_country_index_mapping.json
- integ-test/src/test/resources/occupation.json
- integ-test/src/test/resources/state_country.json
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLJoinTest.java
Core Syntax: Implement ppl join command with Calcite
`./gradlew :integ-test:integTest --tests '*Calcite*IT'` succeed in local
Resolves https://github.com/opensearch-project/sql/issues/3356
> Implement ppl join command with Calcite

- integ-test/src/test/resources/indexDefinitions/occupation_index_mapping.json
- integ-test/src/test/resources/indexDefinitions/state_country_index_mapping.json
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
This PR includes 2 changes:
1. Fix PredicateAnalyzer for in and notIn, it build the DSL query with redundant brackets because of calling wrong API.
2. For the tables used in this IT, change some fields from text type to keyword type as we don't support text push down for now. Issue https://github.com/opensearch-project/sql/issues/3334 will fix it.
`./gradlew :integ-test:integTest --tests '*Calcite*IT'` succeed locally except below 3 tests. They failed because of inconsistent order on the final results while it should not promise that order. Need another PR to fix the test themself.
- CalcitePPLJoinIT.testJoinTwoColumnsAndDisjointFilters
- CalcitePPLJoinIT.testJoinWithCondition
- CalcitePPLJoinIT.testJoinWithTwoJoinConditions
Resolves https://github.com/opensearch-project/sql/issues/3368 …
> Fix CalcitePPLJoinIT

- core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
- core/src/main/java/org/opensearch/sql/ast/expression/subquery/InSubquery.java
- core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
- core/src/main/java/org/opensearch/sql/calcite/CalciteRexNodeVisitor.java
- core/src/main/java/org/opensearch/sql/calcite/utils/OpenSearchTypeFactory.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLAggregationIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLBasicIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLInSubqueryIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLJoinIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLSortIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
- integ-test/src/test/java/org/opensearch/sql/ppl/PPLIntegTestCase.java
- integ-test/src/test/resources/indexDefinitions/work_information_index_mapping.json
- integ-test/src/test/resources/indexDefinitions/worker_index_mapping.json
- integ-test/src/test/resources/work_information.json
- integ-test/src/test/resources/worker.json
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexEnumerator.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/util/JdbcOpenSearchDataTypeConvertor.java
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLInSubqueryTest.java
Core Syntax: Implement ppl `IN` subquery command with Calcite
`./gradlew :integ-test:integTest --tests '*Calcite*IT'` succeed in local
Excepts
> CalcitePPLInSubqueryIT. testInSubqueryWithTableAlias
> CalcitePPLInSubqueryIT. testSelfInSubquery
Those IT failed due to enable pushdown after merged https://github.com/opensearch-project/sql/pull/3366
Resolves #3359
> Implement ppl `IN` subquery command with Calcite

- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteSortCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLBasicIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLInSubqueryIT.java
- integ-test/src/test/resources/indexDefinitions/occupation_index_mapping.json
- integ-test/src/test/resources/indexDefinitions/state_country_index_mapping.json
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteOpenSearchIndexScan.java
When pushing filter with text field, I should construct QueryBuilder by using its subfield of keyword type; Otherwise, we cannot push down this field.
This PR includes change:
1. In PredicateAnalyzer, using keyword subfield as the reference for NamedFieldExpression if it's type is text type. It will return null if no such keyword subfield and throw PredicateAnalyzerException, and then scan won't really do filter push down later.
2. remove the @Ignore annotation for `CalciteSortCommandIT` since we already addressed the issue of order perseverance for PPL in this PR: https://github.com/opensearch-project/sql/pull/3350.
`./gradlew :integ-test:integTest --tests '*Calcite*IT'` succeed locally.
Resolves https://github.com/opensearch-project/sql/issues/3334, …
> [BugFix] support push down text field correctly.

- core/src/main/java/org/opensearch/sql/calcite/CalcitePlanContext.java
- core/src/main/java/org/opensearch/sql/calcite/CalciteRexNodeVisitor.java
Fix the join condition resolving bug introduced by IN subquery implementation
`CalcitePPLJoinTest.testJoinConditionWithoutTableName()` failed after merged #3371 
> [BugFix] Fix the join condition resolving bug introduced by IN subquery implementation

- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteSortCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLJoinIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLSortIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteOpenSearchIndexScan.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/util/JdbcOpenSearchDataTypeConvertor.java
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLBasicTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLJoinTest.java
Core Syntax: Implement ppl relation subquery command with Calcite
`./gradlew :integ-test:integTest --tests '*Calcite*IT' succeed in local`
Resolves https://github.com/opensearch-project/sql/issues/3362 and https://github.com/opensearch-project/sql/issues/3375
> Implement ppl relation subquery command with Calcite

- core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
- core/src/main/java/org/opensearch/sql/ast/expression/subquery/ExistsSubquery.java
- core/src/main/java/org/opensearch/sql/calcite/CalcitePlanContext.java
- core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
- core/src/main/java/org/opensearch/sql/calcite/CalciteRexNodeVisitor.java
- core/src/main/java/org/opensearch/sql/calcite/utils/OpenSearchTypeFactory.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLExistsSubqueryIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLInSubqueryIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLJoinIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLSortIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/util/MatcherUtils.java
- integ-test/src/test/resources/worker.json
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
- ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAbstractTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLEvalTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLExistsSubqueryTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLMathFunctionTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
Core Syntax: Implement ppl `Exists` subquery command with Calcite
`./gradlew :integ-test:integTest --tests '*Calcite*IT'` succeed in local
Changes include:
1. Support Exists Subquery, the syntax check https://github.com/opensearch-project/opensearch-spark/blob/main/docs/ppl-lang/ppl-subquery-command.md
2. Fix the overriding field name issue, `eval a = a +1` won't create `a0` anymore.
3. Replace `verifyDataRowsInOrder` to `verifyDataRows` in some ITs if the tests contain `sort` command.
4. Add anonymizer logical for all new commands.
Resolves #3360  …
> Implement ppl `exists` subquery command with Calcite

- core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLBasicIT.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLBasicTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLStringFunctionTest.java
This PR change to use table qualified name instead of qualified name list. By that, one table scan will support scanning multiple tables and index pattern itself, thus we no need to leverage on union to do multiple table scanning.
`./gradlew :integ-test:integTest --tests '*Calcite*IT'` succeed locally.
`../../../ppl/src/test/java/org/opensearch/sql/ppl/calcite/*` UT succeed locally.
Resolves https://github.com/opensearch-project/sql/issues/3347
> Support multiple table and index pattern

- release-notes/opensearch-sql.release-notes-3.0.0.0-alpha1.md
Add release notes on version 3.0.0.0-alpha1
* https://github.com/opensearch-project/sql/issues/3365
* https://github.com/opensearch-project/sql/issues/3248
* https://github.com/opensearch-project/sql/issues/1880
> Add release notes on version 3.0.0.0-alpha1

- core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLAggregationIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLJoinIT.java
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAbstractTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAggregationTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLEvalTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLJoinTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLScalarSubqueryTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
1. Revert aggregation result ordering of stats-by introduced by https://github.com/opensearch-project/sql/pull/3405.
2. Fix the CR-LF issue
Resolves https://github.com/opensearch-project/sql/issues/3426 and https://github.com/opensearch-project/sql/issues/3425
> Revert result ordering of `stats-by`

- core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
- core/src/main/java/org/opensearch/sql/calcite/CalciteRexNodeVisitor.java
- core/src/main/java/org/opensearch/sql/calcite/ExtendedRexBuilder.java
- core/src/main/java/org/opensearch/sql/calcite/utils/BuiltinFunctionUtils.java
- core/src/main/java/org/opensearch/sql/exception/CalciteUnsupportedException.java
- core/src/main/java/org/opensearch/sql/executor/QueryService.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteOperatorIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLBasicIT.java
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
- ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLBasicTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
1. Support ppl `BETWEEN` operator within Calcite
2. Add all unsupported visit callings in code (PPL only)
3. Support `REGEXP` function
4. Fix `xor` operator issue.
Resolves https://github.com/opensearch-project/sql/issues/3432
> Support ppl BETWEEN operator within Calcite

- core/src/main/java/org/opensearch/sql/calcite/CalciteRexNodeVisitor.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteWhereCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/WhereCommandIT.java
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
- ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLBasicTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
Support In expression, also add data anonymizer for it.
`./gradlew :integ-test:integTest --tests '*Calcite*IT` succeed locally.
`../../../ppl/src/test/java/org/opensearch/sql/ppl/calcite/*` UT succeed locally.
Resolves https://github.com/opensearch-project/sql/issues/3420
> [Calcite Engine] Support In expression

- datasources/build.gradle
`bouncycastle` was removed from the gradle version catalog in https://github.com/opensearch-project/OpenSearch/pull/17507/files#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87df.
This PR sets the same version inline in sql's build.gradle file
> Set bouncycastle version inline

- core/src/main/java/org/opensearch/sql/calcite/udf/textUDF/LocateFunction.java
- core/src/main/java/org/opensearch/sql/calcite/utils/BuiltinFunctionUtils.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/nonfallback/NonFallbackCalciteTextFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLStringBuiltinFunctionIT.java
fix text function IT for locate and strcmp, also, enable nonfallback IT.
All calcite IT pass: 
`./gradlew :integ-test:integTest --tests '*Calcite*IT'`
Resolves https://github.com/opensearch-project/sql/issues/3481
> [Followup] fix text function IT for locate and strcmp

- core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
- core/src/main/java/org/opensearch/sql/calcite/CalciteRexNodeVisitor.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/nonfallback/NonFallbackCalciteParseCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLDedupIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLDedupPushdownIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLParseIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLParsePushdownIT.java
- ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLDedupTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLParseTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
Support `parse` command with Calcite
**Limitation:** 
Multiple capturing groups are not allowed in Calcite REGEXP_EXTRACT function.
`| parse address '(?<streetNumber>\d+) (?<street>.+)'` will fallback to V2.
Resolves #3463 
> Support `parse` command with Calcite

- core/build.gradle
Vulnerable Library - json-smart-2.5.0.jar
Found in base branch: main
https://advisories.opensearch.org/advisories/CVE-2024-57699
Resolves https://github.com/opensearch-project/sql/issues/3485
> CVE-2024-57699 High: Fix json-smart vulnerability

- .github/CODEOWNERS
- MAINTAINERS.md
Welcoming new maintainer [Heng Qian](https://github.com/qianheng-aws)
> Adding new maintainer @qianheng-aws

- opensearch/src/main/java/org/opensearch/sql/opensearch/executor/OpenSearchExecutionEngine.java
Execute Calcite PPL query in thread pool
Resolves #3507
> Execute Calcite PPL query in thread pool

- protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseBase.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/CsvResponseFormatterTest.java
- protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java
According to RFC 4180 for the CSV file format,
section 2, item 6, if a CSV cell contains a
carriage return ('\r') or line feed ('\n') it
must be quoted.
Resolves #3514
- [x ] New functionality includes testing.
- [x ] Commits are signed per the DCO using `--signoff`.
> Fix: CSV handling of embedded crlf

- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunctions.java
Previously, we use getID() and it will return some three-letter time zone IDs like "PLT" which is already deprecated (see [here](https://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html)). But toZoneId().toString() will return the full name like 'Asia/Karachi'.
#3516 
> use correct timezone name

- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
1. Fix incorrect reserved words.
2. Fix lowercase antlr4 parser issue. (mentioned in https://github.com/opensearch-project/sql/issues/3391)
Resolves #3491 
> Fix antlr4 parser issues

- core/src/main/java/org/opensearch/sql/calcite/CalciteRexNodeVisitor.java
- core/src/main/java/org/opensearch/sql/calcite/utils/BuiltinFunctionUtils.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLDateTimeBuiltinFunctionIT.java
Previously we use CHAR in some return type of udf, which will hard truncate return value. Now change it to var char.
#3400 
#3520 
> fix varchar bug

- plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java
1. Enable update calcite setting through _plugins/_query/settings API
2. Add follow up task to enable DocTest on setting. https://github.com/opensearch-project/sql/issues/3533
* calcite default disabled
```
POST {{baseUrl}}/_plugins/_ppl/_explain
Content-Type: application/x-ndjson
{
"query": "source=test00001"
}
{
"root": {
"name": "ProjectOperator",
"description": {
"fields": "[]"
},
"children": [
{
"name": "OpenSearchIndexScan",
"description": {
"request": "OpenSearchQueryRequest(indexName=test00001, sourceBuilder={\"from\":0,\"size\":10000,\"timeout\":\"1m\",\"_source\":{\"includes\":[],\"excludes\":[]}}, needClean=true, searchDone=false, pitId=null, cursorKeepAlive=null, searchAfter=null, searchResponse=null)"
},
"children": []
}
]
}
}
```
* enable calcite
```
PUT …
```
> Enable update calcite setting through _plugins/_query/settings API

- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunctions.java
When locale is set using `-Dtests.locale=az-Cyrl`, `GET_FORMAT(TIME, [whatever])` and `GET_FORMAT(TIMESTAMP, [whatever])` will always return `NULL`.
At [`DateTimeFunctions.java:L1511`](https://github.com/opensearch-project/sql/blob/e23a61dcd9f15864a6bf4a5daa7ac4263a890716/core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunctions.java#L1511), when the local is set to Turkic languages (e.g. Turkish, Azerbaijani), `type.stringValue().toLowerCase` will return `tıme` for `TIME`, where ı is a dotless i, causing the key not existing in the predefined formats map.
Specify locale as `Locale.ROOT` when converting this string to lowercase.
For more information on …
> Fix GET_FORMAT UDF

- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLBasicIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/ppl/DataTypeIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteEnumerableIndexScan.java
Support alias type. 
Since Calcite's logical fields is strictly binding to an offset of its physical array, we have to use an approach different from v2(https://github.com/opensearch-project/sql/pull/3246) but more like the implementation in opensearch-spark(https://github.com/opensearch-project/opensearch-spark/pull/1032).
Resolves  https://github.com/opensearch-project/sql/issues/3397
> [Calcite Engine] Support alias type field

- core/src/main/java/org/opensearch/sql/calcite/udf/datetimeUDF/TimestampFunction.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLDateTimeBuiltinFunctionIT.java
This pr fix the timestamp bug when take time argument. It uses the current function properties. We now follow the same logic as https://github.com/opensearch-project/sql/blob/e23a61dcd9f15864a6bf4a5daa7ac4263a890716/core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunctions.java#L880 to firstly transfer it to timestamp.
https://github.com/opensearch-project/sql/issues/3545
> fix timestamp bug

- DEVELOPER_GUIDE.rst
- core/src/main/java/org/opensearch/sql/utils/DateTimeFormatters.java
- integ-test/build.gradle
- integ-test/src/yamlRestTest/java/org/opensearch/sql/rest/RestHandlerClientYamlTestSuiteIT.java
- integ-test/src/yamlRestTest/resources/rest-api-spec/api/ppl.json
- integ-test/src/yamlRestTest/resources/rest-api-spec/api/query.settings.json
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/2489.yml
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
* Use OpenSearch DateFieldMapper.getDefaultDateTimeFormatter as default format if format is missing.
* Integrate with yamlRestTest to framework to test OpenSearch specific cases. 
* YamlRestTest execut along with `./gradlew integ-test:build`. 
* YamlRestTest execut independenly. `./gradlew integ-test:yamlRestTest`.
* Remove "2015-01-01 12:10:30" related UT, it is not valid OpenSearch default date format.
```
PUT {{baseUrl}}/idx00003
Content-Type: application/x-ndjson
{
"mappings": {
"timestamp": {
"type":   "date"
}
}
}
}
POST {{baseUrl}}/idx00003/_doc
Content-Type: application/x-ndjson
{"timestamp": "2015-01-01 12:10:30"}
{
"error": {
"root_cause": [
{
"type": "mapper_parsing_exception",
"reason": "failed to parse field [timestamp] of type [date] in document with id …
```
> Fix issue 2489

- core/src/main/java/org/opensearch/sql/data/model/ExprTupleValue.java
- core/src/main/java/org/opensearch/sql/data/model/ExprValue.java
- core/src/test/java/org/opensearch/sql/data/model/ExprTupleValueTest.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFlattenDocValueIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
- integ-test/src/test/java/org/opensearch/sql/ppl/FlattenDocValueIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/PPLIntegTestCase.java
- integ-test/src/test/resources/flattened_value.json
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3477.yml
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/util/JdbcOpenSearchDataTypeConvertor.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
It supports parsing flattened document value by populating the ExprTupleValue recursively, so we can access the nested fields as well as the root fields as before.
Resolves  https://github.com/opensearch-project/sql/issues/3477
> Support parsing documents with flattened value

- opensearch/src/main/java/org/opensearch/sql/opensearch/request/AggregateAnalyzer.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/CompositeAggregationParser.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/MetricParserHelper.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/response/agg/NoBucketAggregationParser.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/request/AggregateAnalyzerTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/request/PredicateAnalyzerTest.java
Add UT for PredicateAnalyzer and AggregateAnalyzer
Resolves https://github.com/opensearch-project/sql/issues/3340
> Add UT for PredicateAnalyzer and AggregateAnalyzer

- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
- docs/user/ppl/functions/condition.rst
- docs/user/ppl/functions/cryptographic.rst
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLConditionBuiltinFunctionIT.java
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
Support functions `isempty`, `isblank` and `ispresent` with Calcite.
Function behaviors aligned with https://github.com/opensearch-project/opensearch-spark/pull/1170
Resolves #3609 
> Support functions `isempty`, `isblank` and `ispresent` with Calcite

- .github/workflows/link-checker.yml
- .github/workflows/maven-publish.yml
Overview
This workflow automates the process of building and publishing OpenSearch artifacts to a Maven repository. Specifically, it builds the async-query-core shadow JAR and publishes it to the Sonatype snapshots repository under the org.opensearch.direct-query-poc group ID.
Key Operations
Shadow JAR Building and Processing
Maven Repository Publishing
Employs the standard OpenSearch publish-snapshot.sh script to:
Upload the shadow JAR and associated files
Generate and upload Maven metadata files
Downloads the generated Maven metadata XML file
Adds the commit ID to the metadata for improved traceability
Re-uploads the enhanced metadata file
Also publishes the standard plugin ZIP package using the Gradle task: publishPluginZipPublicationToSnapshotsRepository
Output
The workflow publishes …
> create directory /direct-query to contain async-query-core shadow JAR to the repository with all the necessary Maven metadata including the commit ID.

- core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
- core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java
- core/src/main/java/org/opensearch/sql/ast/tree/FillNull.java
- core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
- core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
- core/src/test/java/org/opensearch/sql/analysis/AnalyzerTest.java
- docs/user/ppl/cmd/fillnull.rst
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteFillNullCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLFillnullIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/ExplainIT.java
- integ-test/src/test/resources/expectedOutput/calcite/explain_fillnull_push.json
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
- ppl/src/main/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizer.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLFillnullTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
- Migrate `fillnull` command implemented in https://github.com/opensearch-project/sql/pull/3075 to Calcite implementation.
- Keep the syntax consistency with the current existing.
- Support no specified field list (which is a missing feature in  https://github.com/opensearch-project/sql/pull/3075)
- if no field specified, the replacement is applied to all fields.
Resolves #3461 
> Support `fillnull` command with Calcite

- core/src/main/java/org/opensearch/sql/exception/NonFallbackCalciteException.java
- core/src/main/java/org/opensearch/sql/executor/QueryService.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteResourceMonitorIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/monitor/OpenSearchResourceMonitor.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/OpenSearchIndex.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteEnumerableIndexScan.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexEnumerator.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAppendcolTest.java
- Support ResourceMonitor with Calcite
- Currently, the `CalciteEnumerableIndexScan` is the only physical operator we implemented. The rests are all default implementations of Calcite. Resource monitor can only be added in scan operator. But for memory checker, it‘s fine.
- Fix the failed UTs related to #3673 
Resolves #3454 
> Support ResourceMonitor with Calcite

- core/src/main/java/org/opensearch/sql/ast/tree/Join.java
- core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
- core/src/main/java/org/opensearch/sql/calcite/CalciteRexNodeVisitor.java
- core/src/main/java/org/opensearch/sql/calcite/utils/PlanUtils.java
- docs/user/ppl/cmd/join.rst
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLJoinIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/tpch/CalcitePPLTpchIT.java
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLBasicTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLInSubqueryTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLJoinTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
```
source=table1 | join left=t1 right=t2 on t1.id=t2.id table2 | eval a = 1 | fields t1.id, t2.id
```
Fail with {alias=t2, fieldName=id} field not found
Join outputs could contain duplicated column name, typically the join criteria `ON t1.id = t2.id`. The `id` in output of join operator is ambiguous. Calcite will rename the ambiguous column name with numeric suffix, the output generates `id` and `id0` when a new project add to stack.
To avoid `id0`, this PR renames the `id0` to `<alias>.id`, or `<tableName>.id` if no alias existing.
table1:
| id   |
| --- |
| 1 |
| 2 |
table2
| id   |
| --- |
| 1 |
| 3 |
```
source=table1 | join left=t1 right=t2 on t1.id=t2.id table2 | eval a = 1
```
outputs `t1.id`, `t2.id` and `a`
```
source=table1 | join on table1.id=table2.id table2 | eval a = 1
``` …
> Fix field not found issue in join output when column names are ambiguous

- integ-test/build.gradle
As per the current design of Gradle test workflow, Gradle task `startPrometheus` is designed to execute upon every integration test and docTest.
However the current implementation of `startPrometheus` and `stopPrometheus` will force and trigger the re-download of `Prometheus` binary, no matter that is a first run or subsequent run.  (~100 Mb)
This result in waste of bandwidth and reduce on developer productivity, as integration test will be executed frequently during the typical development process. 
Hence this is a PR to introduce FileExistCheck to only download Prometheus binary when it's absent. 
- To execute multiple `integTest` and make sure `Prometheus File Already Exists` printed on console and no additional files being downloaded on subsequent IT test execution. 
Resolves …
> Build: Cache Prometheus binary 

- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3810.yml
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
https://github.com/opensearch-project/sql/pull/3673 introduced a decimal literal in plan, decimal literal in expression can not be pushed down since the decimal literal in Calcite is not converted to double in pushdown, and only double/float data type supported in DSL. This PR converts decimal type to double type in handling pushdown.
Note, this bug is only triggered when the field type in expression is integer + decimal literal.
For example, following query failed when `balance` is integer type in mapping, but success if `balance` is double.
```
source=%s | where balance > 40000.00 | stats avg(balance)
```
Resolves #3810 
For more information on following Developer …
> Decimal literal should convert to double in pushdown

- .github/workflows/maven-publish-modules.yml
- api/README.md
- api/build.gradle
- api/src/main/java/org/opensearch/sql/api/UnifiedQueryPlanner.java
- api/src/test/java/org/opensearch/sql/api/UnifiedQueryPlannerTest.java
- build.gradle
- settings.gradle
This PR backports the unified query API and related module publishing commits in `feature/unified-ppl` to PPL Calcite in 2.19 release line. This backport is a prerequisite for publishing the corresponding changes in the OpenSearch-Spark repository.
Instead of backporting directly to the final destination `2.19-dev` branch, we are targeting a temporary intermediate branch `feature/unified-ppl-2.19-dev` for the following reasons:
1. There are ongoing backports currently being merged into `2.19-dev`.
2. Further changes in `unified-query-api` may occur as development continues on the Spark side.
```
$ java -version
openjdk version "11.0.25" 2024-10-15 LTS
OpenJDK Runtime Environment Corretto-11.0.25.9.1 (build 11.0.25+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.25.9.1 (build 11.0.25+9-LTS, …
```
> [Backport] Unified query modules publishing to 2.19

- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLDateTimeBuiltinFunctionIT.java
This fixes flaky tests related to `YEARWEEK` function in certain locales.
This fix assumes that the existing implementation is correct, and only fixes tests.
The problem arises from https://github.com/opensearch-project/sql/blob/b610ce96f5a7772d7ebf15f0bea27d1103c63c92/core/src/main/java/org/opensearch/sql/expression/datetime/CalendarLookup.java#L62
When locale is in `ja-JP-u-ca-japanese-x-lvariant-JP`, the calendar implementation is `JapanImperialCalender`. Retrieving week of the year with this calendar on 1984-04-12 results in 14; while in `en-US` locale it returns 15.
Resolves #3814 
For more information on following Developer Certificate of Origin and signing off your …
> [BUG] Fix flaky tests related to WeekOfYear in CalcitePPLDateTimeBuiltinFunctionIT

- .github/CODEOWNERS
backport code owner from main to 2.19-dev to solve auto-merge does not work issue.
n/a
> Backport codeowner from main to 2.19-dev

- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3343.yml
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/Content.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/ObjectContent.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/OpenSearchJsonContent.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
- protocol/src/main/java/org/opensearch/sql/protocol/response/format/ErrorFormatter.java
Support struct field with dynamic disabled
If dynamic mapping disabled, although information of type missed for the new added fields, we can still parse value from the content by itself only.
Resolves https://github.com/opensearch-project/sql/issues/3343
> Support struct field with dynamic disabled

- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/2489.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3102.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3312.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3477.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3570.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3595.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3607.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3635.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3646.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3655.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3810.yml
Allow warning header for yaml test. Only see such failure for `3102.yml` and `3312.yml` so far.
OpenSearchQueryRequest relies on `_id` to preserve sort location for PIT search:
https://github.com/opensearch-project/sql/blob/74b4de067cefc821055076bd108249cef777c3f9/opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java#L195-L197
However, OpenSearch has deprecated the sort or aggregation behavior on `id`:
https://github.com/opensearch-project/OpenSearch/blob/36c2d5930ab3c036f19760942f95ea4bdb126137/server/src/main/java/org/opensearch/index/mapper/IdFieldMapper.java#L84-L87
So it will has warning message in the header of response, but the reason why it's flakey remains unclear. This PR make it workaround by allowing this warning header in yaml test.
For …
> Allow warning header for yaml test

- core/src/main/java/org/opensearch/sql/calcite/plan/Scannable.java
- core/src/main/java/org/opensearch/sql/calcite/utils/CalciteToolsHelper.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLExplainIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/planner/physical/EnumerableIndexScanRule.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteEnumerableIndexScan.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexEnumerator.java
Currently, when the Calcite engine is enabled, **​​all query plans**​​ -- regardless of their structure -- are converted to `EnumerableRel`. This means the plan is transformed into a `Linq4j` Expression, generates Java code, and undergoes just-in-time (JIT) compilation before execution.
For ​​simple or fully pushdown-compatible queries​​ (e.g., `source=t`, `source=t | where a=1`, `source=t | sort a`, or `source=t | where a=1 | sort b | head 10`), the optimized plans only contain node `EnumerableTableScan`. Despite their simplicity, these plans ​​unnecessarily undergo code generation and dynamic compilation​​, introducing overhead.
To ​​reduce codegen and compilation time​​, we propose converting such plans to `BindableRel` instead of `EnumerableRel`. This bypasses code generation and …
> Skipping codegen and compile for Scan only plan

- .github/get-sonatype-credentials.sh
- .github/workflows/link-checker.yml
- .github/workflows/maven-publish.yml
- .github/workflows/publish-async-query-core.yml
- .github/workflows/publish-grammar-files.yml
- integ-test/build.gradle
- plugin/build.gradle
Update the maven snapshot publish endpoint and credential
Previous description from #3806 :
> Update the Maven Snapshots publish URL in accordance with the recent Sonatype migration.
[central.sonatype.org/publish/publish-portal-snapshots](https://central.sonatype.org/publish/publish-portal-snapshots/)
We have stored the onepassword token in this repo secrets and new credentials for Sonatypes username & password have been stored in onepassword. These credentials will be exported as env variables which used by maven publish.
* Relate https://github.com/opensearch-project/opensearch-build/issues/5551
* Resolves #3856
* Resolves the conflict of #3806
For more information on …
> Update the maven snapshot publish endpoint and credential

- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3477.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3570.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3881.yml
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
Fix incorrect push down for Sarg with nullAs is TRUE
Before this PR, `PredicateAnalyzer` ignore the nullAs properties in Sarg and leads to incorrect results.
Resolves https://github.com/opensearch-project/sql/issues/3881
> [BugFix] Fix incorrect push down for Sarg with nullAs is TRUE

- build.gradle
- core/build.gradle
Fix [CVE-2025-48924](https://github.com/advisories/GHSA-j288-q9x7-2f5v)
https://github.com/opensearch-project/opensearch-build/issues/5637
- upgrade commons-lang3 to 3.18.0
- remove commons-lang (introduced by net.hydromatic:aggdesigner-algorithm:6.0 which is not used in our code. aggdesigner is used when the schema contains Lattice entities)
> CVE-2025-48924: upgrade commons-lang3 to 3.18.0

- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3477.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3570.yml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3881.yml
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
> [Backport 2.19-dev] [BugFix] Fix incorrect push down for Sarg with nullAs is TRUE (#3882)

- core/src/main/java/org/opensearch/sql/calcite/plan/Scannable.java
- core/src/main/java/org/opensearch/sql/calcite/utils/CalciteToolsHelper.java
- core/src/main/java/org/opensearch/sql/executor/QueryService.java
- integ-test/src/test/resources/expectedOutput/calcite/explain_limit_10from1_10from2_push.json
- integ-test/src/test/resources/expectedOutput/calcite/explain_limit_5_10_push.json
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/AbstractCalciteIndexScan.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteEnumerableIndexScan.java
* Push down QUERY_SIZE_LIMIT
* Fix compiling
* Use QUERY_SIZE_LIMIT in osIndex settings directly
* Revert code
* SpotlessApply after resolving conflict
---------
(cherry picked from commit 0bded2aa4d9c80e07929fdc91bac1f74d1e18f7c)
> [Backport 2.19-dev]Push down QUERY_SIZE_LIMIT (#3880)

- .github/workflows/link-checker.yml
- .github/workflows/maven-publish.yml
- integ-test/build.gradle
- plugin/build.gradle
Update the maven snapshot publish endpoint and credential
* Backport #3886 
> [Backport 2.19] Update the maven snapshot publish endpoint and credential

- common/src/main/java/org/opensearch/sql/common/grok/GrokCompiler.java
- common/src/test/java/org/opensearch/sql/common/grok/GrokTest.java
- core/src/main/java/org/opensearch/sql/calcite/utils/UserDefinedFunctionUtils.java
- core/src/main/java/org/opensearch/sql/expression/datetime/DateTimeFunctions.java
- core/src/main/java/org/opensearch/sql/expression/function/FunctionProperties.java
- core/src/main/java/org/opensearch/sql/expression/function/udf/datetime/DatetimeFunction.java
- core/src/main/java/org/opensearch/sql/expression/function/udf/datetime/SysdateFunction.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTest.java
- core/src/test/java/org/opensearch/sql/expression/datetime/ExtractTest.java
- core/src/test/java/org/opensearch/sql/expression/datetime/NowLikeFunctionTest.java
- core/src/test/java/org/opensearch/sql/expression/function/FunctionPropertiesTest.java
- core/src/test/java/org/opensearch/sql/utils/DateTimeUtilsTest.java
- docs/user/ppl/functions/datetime.rst
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteDateTimeFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLDateTimeBuiltinFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/DateTimeFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/NowLikeFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/NowLikeFunctionIT.java
Backport  #3854 to 2.19-dev
#3725
> [Backport 2.19-dev] Default to UTC for date/time functions across PPL and SQL

- build.gradle
- common/build.gradle
- core/build.gradle
- legacy/build.gradle
Manually backport https://github.com/opensearch-project/sql/pull/3895
> [Backport 2.x] CVE-2025-48924: upgrade commons-lang3 to 3.18.0 (#3895)

- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/Content.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/ObjectContent.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/OpenSearchJsonContent.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/CalciteScriptEngine.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/serde/RelJsonSerializer.java
` | eval a = abs(byte_number) | stats count() by a ` failed with
```
Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Byte (java.lang.Long and java.lang.Byte are in module java.base of loader 'bootstrap')
at Reducer.apply(Unknown Source) ~[?:?]
at Reducer.apply(Unknown Source) ~[?:?]
at org.opensearch.sql.opensearch.storage.script.core.CalciteScript.lambda$execute$0(CalciteScript.java:45) ~[?:?]
at java.base/java.security.AccessController.doPrivileged(AccessController.java:319) ~[?:?]
at org.opensearch.sql.opensearch.storage.script.core.CalciteScript.execute(CalciteScript.java:43) ~[?:?]
at org.opensearch.sql.opensearch.storage.script.aggregation.CalciteAggregationScript.execute(CalciteAggregationScript.java:50) ~[?:?]
```
Resolves #3927 
By …
> Byte number should treated as Long in doc values

- integ-test/build.gradle
- integ-test/src/test/java/org/opensearch/sql/security/PPLPermissionsIT.java
- legacy/src/main/java/org/opensearch/sql/legacy/pit/PointInTimeHandlerImpl.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchRestClient.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java
Currently there is a bug where PPL is asking for search permission across all indices even though the user has permissions to make a PPL query on a particular index.
Issue is more detailed here: https://github.com/opensearch-project/security/issues/5508
Also, fixed few other issues with wrong error status codes in case of authorization errors.
Added more PPL permissions IT which covers the above bug.
* Transport PIT search calls require index information for correct security authorization.
* Rest PIT search calls automatically handles this in Rest layer by decoding PIT information into indices before transport layer.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Fix create PIT permissions issue

- core/build.gradle
- ppl/build.gradle
`commons-lang` was excluded as part of the `calcite-core` import for the `core` config, but still was being pulled in via another transient dependency chain in `ppl`. This PR updates the exclude to remove `commons-lang` everywhere.
N/A
> Update commons-lang exclude rule to exclude it everywhere

- core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
- docs/user/ppl/functions/string.rst
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteLikeQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteWhereCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/ExplainIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/LikeQueryIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/WhereCommandIT.java
- integ-test/src/test/java/org/opensearch/sql/sql/LikeQueryIT.java
- integ-test/src/test/resources/expectedOutput/calcite/explain_keyword_like_function.json
- integ-test/src/test/resources/expectedOutput/calcite/explain_text_like_function.json
- integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_keyword_like_function.json
- integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_text_like_function.json
- integ-test/src/test/resources/expectedOutput/ppl/explain_keyword_like_function.json
- integ-test/src/test/resources/expectedOutput/ppl/explain_text_like_function.json
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/StringUtils.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LikeQuery.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/script/filter/lucene/LuceneQuery.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/request/PredicateAnalyzerTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/storage/script/StringUtilsTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLStringFunctionTest.java
Convert like function call to wildcard query for Calcite filter pushdown (#3915)
* Convert like function call to wildcard query for Calcite filter pushdown
* Fix V2 expression like function bug and match its behavior in Calcite
* Fix like default escape in Calcite
* Fix tests
* Fix spotless check
* Address comments
* Fix SQL IT correctness
* Remove test log
* Minor improve one CalciteLikeQueryIT
---------
(cherry picked from commit cd389833420aee5af31b850a6bbf6a309e861024) …
> [Backport 2.19-dev] Convert like function call to wildcard query for Calcite filter pushdown (#3915)

- build.gradle
Add `datasources` module 
**Local Publishing Test**
Example after running the local publish command:
```
./gradlew publishUnifiedQueryPublicationToMavenLocal
tree -d ~/.m2/repository/org/opensearch
└── query
├── unified-query-api
│   └── 3.1.0.0-SNAPSHOT
├── unified-query-common
│   └── 3.1.0.0-SNAPSHOT
├── unified-query-core
│   └── 3.1.0.0-SNAPSHOT
├── unified-query-datasources <- adding datasources 
│   └── 3.1.0.0-SNAPSHOT
├── unified-query-opensearch
│   └── 3.1.0.0-SNAPSHOT
├── unified-query-ppl
│   └── 3.1.0.0-SNAPSHOT
├── unified-query-protocol
│   └── 3.1.0.0-SNAPSHOT
└── unified-query-sql
└── 3.1.0.0-SNAPSHOT
```
[3763](https://github.com/opensearch-project/sql/pull/3763)
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Publish datasources module for downstream reuse in unified-ppl

- .github/ISSUE_TEMPLATE/ppl_bug_report.md
In order to make it easier for users to report any specific PPL issue, this template will ask for more details like PPL query used and it will assign PPL label automatically 
N/A
> Add issue template specific for PPL commands and queries

- .github/maven-publish-utils.sh
- .github/workflows/publish-async-query-core.yml
- .github/workflows/publish-grammar-files.yml
Update snapshot uploading
I changed the path to fetch the publish-snapshot.sh(https://github.com/opensearch-project/opensearch-build/blob/main/publish/publish-snapshot.sh) from opensearch-build-libraries to opensearch-build since this file no longer exists in opensearch-build-libraries
> fix snapshot uploading

- core/src/main/java/org/opensearch/sql/planner/physical/collector/Rounding.java
- core/src/main/java/org/opensearch/sql/utils/DateTimeUtils.java
- core/src/test/java/org/opensearch/sql/utils/DateTimeUtilsTest.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java
Fix span on negative timestamp
Resolves  https://github.com/opensearch-project/sql/issues/3827
> Fix span on negative timestamp

- async-query-core/src/main/java/org/opensearch/sql/spark/utils/SQLQueryUtils.java
- async-query-core/src/test/java/org/opensearch/sql/spark/utils/SQLQueryUtilsTest.java
adding capability in SQLQueryUtils to identify if SQL query is for creating a table or not.
NA
- [ Y] New functionality includes testing.
- [NA ] New functionality has been documented.
- [ NA] New functionality has javadoc added.
- [NA ] New functionality has a user manual doc added.
- [NA ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ Y] Commits are signed per the DCO using `--signoff`.
- [ NA] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
By submitting this pull request, I confirm that my contribution is made under …
> adding capability in SQLQueryUtils to identify if SQL query is for creating a table or not.

- .github/maven-publish-utils.sh
Disable commit-history file creation in snapshot publishing workflow to comply with Maven Central repository restrictions.
Maven Central Sonatype repository enforces strict rules about the types of files that can be uploaded to their snapshot repository. 
Our custom commit-history-*.json files are being rejected by Maven Central as they are non-standard artifacts
What still works
- Snapshot artifacts are published normally
- Commit IDs are still injected into maven-metadata.xml files for traceability
- All standard Maven repository operations continue to function
What is disabled
- Creation of commit-history JSON files in the artifact structure
- Upload of commit mapping files to the repository
Tested on #1265
> disable commit-history

- build.gradle
Adding `legacy` submodule because `datasources` depends on it.
```
./gradlew publishUnifiedQueryPublicationToMavenLocal   
tree -d ~/.m2/repository/org/opensearch/query/unified-query-legacy
└── 3.1.0.0-SNAPSHOT
```
[3935](https://github.com/opensearch-project/sql/pull/3935)
> Publish legacy module for downstream reuse in unified-ppl

- integ-test/src/test/java/org/opensearch/sql/calcite/tpch/CalcitePPLTpchIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/PPLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/util/Retry.java
- integ-test/src/test/java/org/opensearch/sql/util/RetryProcessor.java
CalcitePPLTpchIT.testQ7 failed with socket timeout sometimes on mac/windows instance.
q1 could be flaky when pushdown enabled since the precision of double sum depended on order of data.
> Add flaky retry on CalcitePPLTpchIT

- integ-test/src/test/java/org/opensearch/sql/calcite/clickbench/PPLClickBenchIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/ResourceMonitorIT.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/monitor/GCedMemoryUsage.java
https://github.com/opensearch-project/sql/pull/3983 enables `GCedMemoryUsage` for Calcite. But when the Java version is less than 21, there is no `ConcurrentMXBean` returned from `ManagementFactory.getGarbageCollectorMXBeans()`. Fallback it to `RuntimeMemoryUsage`.
> FollowUp: Disable GCedMemoryUsage if no concurrent GC MXBean

- core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLConditionBuiltinFunctionIT.java
- integ-test/src/test/resources/expectedOutput/calcite/explain_partial_filter_isnull.json
- integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_partial_filter_isnull.json
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
Backport #4044 to 2.19-dev
* Redefine type checkers of isnull, isnotnull, and ispresent to IGNORE
* Prevents filtering with isnull/isnotnull conditions on nested fields
* Prevents pushing down isnull(nested) in PredicateAnalyzer to correct pushdown of complex & partial filters containing isnull(nested)
* Test explaining partial pushdown filter with isnull
* Add interface registerOperator(BuiltinFunctionName, SqlOperator, PPLTypeChecker) to allow registering an operator with a designated type chekcer
---------
(cherry picked from commit 284ecc49f2a1a1428658a75d5ae4dc608476133b)
Resolves #4004
For more information on following Developer Certificate of Origin and signing off …
> [Backport 2.19-dev] Allow type checkering on nested & struct fields for isnull, isnotnull and ispresent (#4044)

- build.gradle
- integ-test/build.gradle
Old sonatype repo was finally deactivated, turns out we implicitly still depended on some artifacts from it because we had fallback repositories configured, and many artifacts from the old repo were missing in the new one.
Removes the (now fully deprecated) fallback, and updates our base version in `main` to the latest version available in the newer snapshot repos.
All CI broke from this
> [Hotpatch][Infra] Fix CI artifact sources

- build.gradle
(cherry picked from #4141 commit 80945963179d4dc24e77165ec928d64a4482d524)
> [Backport 2.19-dev] Migrate from sonatype snapshot to ci.opensearch.org snapshots (#4141)

- build.gradle
https://github.com/opensearch-project/sql/pull/4131 provided a hotfix that remove the old sonatype repo.
But https://github.com/opensearch-project/opensearch-build/issues/5360 suggested to migrate from sonatype repo to ci.opensearch.org repo.
Just removing the sonatype repo didn't work in 2.19-dev branch. This PR is to complete the migration in SQL plugin.
> Migrate from sonatype snapshot to ci.opensearch.org snapshots

- .github/workflows/link-checker.yml
- build.gradle
Got multiple service unavailable CI failures after #4141, reorder the repositories to resolve the problem.
> Could not HEAD 'https://ci.opensearch.org/ci/dbc/snapshots/org/apache/calcite/calcite-linq4j/1.38.0/calcite-linq4j-1.38.0.pom'. Received status code 503 from server: Service Unavailable
> 
> Could not HEAD 'https://ci.opensearch.org/ci/dbc/snapshots/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.pom'. Received status code 503 from server: Service Unavailable …
> Reorder the maven repositories to resolve the service unavailable issue

- plugin/build.gradle
This PR updates the Gradle build files to fix compatibility with Gradle 9.
The current syntax using `$System.env.VARIABLE_NAME` for accessing environment variables is not compatible with Gradle 9.
This format is used in this repository for Sonatype credentials for SNAPSHOT publication. This fails with under Gradle 9.
```gradle
credentials {
username = "$System.env.SONATYPE_USERNAME"
password = "$System.env.SONATYPE_PASSWORD"
}
```
See [example failed workflow here](https://github.com/opensearch-project/opensearch-remote-metadata-sdk/actions/runs/17023398832/job/48255946880#step:5:74).
Update to use the `System.getenv()` method instead:
```gradle
credentials {
username = System.getenv("SONATYPE_USERNAME")
password = System.getenv("SONATYPE_PASSWORD")
}
```
Example fix which restored …
> fix: Update System.env syntax for Gradle 9 compatibility

- core/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
- core/src/main/java/org/opensearch/sql/ast/dsl/AstDSL.java
- core/src/main/java/org/opensearch/sql/ast/expression/Literal.java
- core/src/main/java/org/opensearch/sql/ast/tree/SPath.java
- core/src/main/java/org/opensearch/sql/calcite/CalciteRelNodeVisitor.java
- core/src/main/java/org/opensearch/sql/expression/function/jsonUDF/JsonExtractFunctionImpl.java
- docs/user/ppl/cmd/spath.rst
- docs/user/ppl/index.rst
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLSpathCommandIT.java
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLSpathTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/SPathRewriteTest.java
For now, implementing `spath` (#4119) as a lightweight conversion directly into a `json_extract` eval. We'll add more specific semantics later, but this covers the most common usage for the command as-is.
For more path behavior, see: https://github.com/opensearch-project/sql/blob/b220be43b082929101ed0905e08eee44fe07c6c3/integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLJsonBuiltinFunctionIT.java#L107
Related to #4119 
> Starter implementation for `spath` command

- core/src/main/java/org/opensearch/sql/calcite/udf/udaf/PercentileApproxFunction.java
- docs/user/dql/aggregations.rst
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java
- integ-test/src/test/java/org/opensearch/sql/security/CrossClusterSearchIT.java
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAggregationTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java
Backport https://github.com/opensearch-project/sql/commit/aecca57878d9ddee5036c31dc9288cff7e818598 from https://github.com/opensearch-project/sql/pull/4085.
> [Backport 2.19-dev] PPL percentile function shortcut `perc()` and `p()` support

- core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
- docs/user/ppl/cmd/stats.rst
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/StatsCommandIT.java
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAggregationTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
Add count alias to count()
Supports count syntax without parentheses in stats PPL function.
N/A
> Add count alias to count()

- async-query/build.gradle
- doctest/requirements.txt
- legacy/build.gradle
We already install setuptools as part of bootstrap, reinstalling a new version causes breakage with some python setups (particularly when the newer version is unavailable). On the other hand, doctest depends on click, which is unspecified.
Fixes some setups being unable to run doctest locally (I don't know how this has been passing in CI).
Also, async-query unit tests are independent. Enabling forking for it makes `./gradlew build --parallel -x doctest -x integTest` run 5x as fast locally. (Most of it is `IndexQuerySpecTest` and `IndexQuerySpecAlterTest`, we could split these classes into smaller chunks)
Also, don't run spotless on generated antlr output.
N/A
For more …
> Fix doctest requirements install

- docs/user/ppl/cmd/sort.rst
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLSortIT.java
- integ-test/src/test/java/org/opensearch/sql/ppl/SortCommandIT.java
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
- Adds asc/a keyword as option in sort command, Specifying asc does not change behavior, sort direction of each field remains as specified (ascending as default)
- Adds missing tests to ```CaclitePPlSortIT``` for desc keyword, count, and type casting enhancements
- Added `ASC` and `A` tokens to PPL lexer and parser grammar
- Updated sort command to accept `asc`/`a` keywords alongside existing `desc`/`d` …
> Add asc keyword to sort command

- core/src/main/java/org/opensearch/sql/analysis/Analyzer.java
- Fix issue caused by merge in Analyzer.java
- Caused by this PR: https://github.com/opensearch-project/sql/pull/4150
n/a
> Fix issue caused by merge in Analyzer.java

- doctest/build.gradle
- doctest/test_docs.py
Since I've been working on build timing lately: the vast majority of our time in doctest is spent repeatedly creating and destroying test indices with `refresh=wait_for`.
Originally I just wanted to rewrite this to run all the indexing in parallel, but it turns out: our doctests don't do any index modifications. There's no real reason to be repeatedly destroying and reindexing all this data. Disabling this behavior (in addition to parallel index creation) makes doctest run in ~13 seconds locally:
```
/workplace/sawiddis/sql/doctest/../docs/user/dql/expressions.rst
Doctest: expressions.rst ... ok
/workplace/sawiddis/sql/doctest/../docs/user/general/comments.rst
Doctest: comments.rst ... ok
...
/workplace/sawiddis/sql/doctest/../docs/user/ppl/cmd/stats.rst
Doctest: stats.rst ... ok …
```
> Don't recreate indices on every doctest

- build.gradle
Add `datasources` module 
**Local Publishing Test**
Example after running the local publish command:
```
./gradlew publishUnifiedQueryPublicationToMavenLocal
tree -d ~/.m2/repository/org/opensearch
└── query
├── unified-query-api
│   └── 2.19.0.0-SNAPSHOT
├── unified-query-common
│   └── 2.19.0.0-SNAPSHOT
├── unified-query-core
│   └── 2.19.0.0-SNAPSHOT
├── unified-query-datasources <- adding datasources 
│   └── 2.19.0.0-SNAPSHOT
├── unified-query-opensearch
│   └── 2.19.0.0-SNAPSHOT
├── unified-query-ppl
│   └── 2.19.0.0-SNAPSHOT
├── unified-query-protocol
│   └── 2.19.0.0-SNAPSHOT
└── unified-query-sql
└── 2.19.0.0-SNAPSHOT
```
[3763](https://github.com/opensearch-project/sql/pull/3763)
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> Publish datasources module for downstream reuse in unified-ppl-2.19-dev

- .gitignore
- Previous commit was working for directory, but not working for symbolic link to directory.
> Fix gitignore to ignore symbolic link

- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
- docs/user/ppl/functions/collection.rst
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteArrayFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
- integ-test/src/test/resources/expectedOutput/calcite/explain_mvjoin.json
- integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_mvjoin.json
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLArrayFunctionTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLFunctionTypeTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
This PR adds support for the mvjoin function in PPL with Apache Calcite integration. The mvjoin function concatenates the elements of a multi-value field into a single string using a specified delimiter.  This is useful for converting multi-value fields into a readable string format.
Syntax: `mvjoin(multivalue_field, delimiter)`
Example:
```
source=logs | eval joined_values = mvjoin(array('apple', 'banana', 'cherry'), ', ')
// Result: "apple, banana, cherry"
```
Resolves #4146 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certific …
> `mvjoin` support in PPL Caclite

- core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
- core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java
- docs/user/ppl/functions/collection.rst
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteArrayFunctionIT.java
- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
- integ-test/src/test/resources/expectedOutput/calcite/explain_mvjoin.json
- integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_mvjoin.json
- ppl/src/main/antlr/OpenSearchPPLLexer.g4
- ppl/src/main/antlr/OpenSearchPPLParser.g4
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLArrayFunctionTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLFunctionTypeTest.java
- ppl/src/test/java/org/opensearch/sql/ppl/utils/PPLQueryDataAnonymizerTest.java
This PR adds support for the mvjoin function in PPL with Apache Calcite integration. The mvjoin function concatenates the elements of a multi-value field into a single string using a specified delimiter.  This is useful for converting multi-value fields into a readable string format.
Syntax: `mvjoin(multivalue_field, delimiter)`
Example:
```
source=logs | eval joined_values = mvjoin(array('apple', 'banana', 'cherry'), ', ')
// Result: "apple, banana, cherry"
```
Original PR to main: https://github.com/opensearch-project/sql/pull/4217 …
> [Backport 2.19-dev] `mvjoin` support in PPL Caclite

- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteGeoPointFormatsIT.java
- integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java
- integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java
- integ-test/src/test/java/org/opensearch/sql/ppl/GeoPointFormatsIT.java
- integ-test/src/test/resources/complex_geo.json
- integ-test/src/test/resources/indexDefinitions/complex_geo_index_mapping.json
- opensearch/src/main/java/org/opensearch/sql/opensearch/util/JdbcOpenSearchDataTypeConvertor.java
Partially Resolves #4324
Also, removed CalciteGeoPointFormatsIT.testReadingGeoHash as we have resolved the https://github.com/opensearch-project/sql/pull/3445
Currently, it handles only map case and we need to follow up with array and other complex scenarios.
> Fix geopoint issue in complex data types

- docs/user/ppl/cmd/rex.rst
Correct the comparision table for rex doc
- Correct the wrong comparison result between `rex` and `parse` in `rex.rst`
- Both `rex` and `parse` should only behave extraction instead of filtering.
- Add highlighted diff to mention `rex` supports multiple name group extractions
* Relate #4109 
> [Doc] Correct the comparision table for rex doc

- docs/user/ppl/reference/splunk_to_ppl_cheat_sheet.md
Add [Splunk to PPL cheat sheet doc](https://github.com/penghuo/os-sql/blob/dcca680b0980f28406987fe6fb49a51e2c185889/docs/user/ppl/reference/splunk_to_ppl_cheat_sheet.md)
n/a
> Add splunk to ppl cheat sheet

- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/4342.yml
- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClient.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/client/OpenSearchRestClient.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
No index found with given index pattern should throw IndexNotFoundException
Resolves #4342 
> No index found with given index pattern should throw IndexNotFoundException

- core/src/test/java/org/opensearch/sql/data/model/ExprValueCompareTest.java
- core/src/test/java/org/opensearch/sql/expression/ExpressionTestBase.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateDiffTest.java
- core/src/test/java/org/opensearch/sql/expression/datetime/DateTimeTestBase.java
- core/src/test/java/org/opensearch/sql/expression/datetime/StrToDateTest.java
- core/src/test/java/org/opensearch/sql/expression/datetime/TimeStampAddTest.java
- core/src/test/java/org/opensearch/sql/expression/datetime/TimeStampDiffTest.java
- core/src/test/java/org/opensearch/sql/expression/datetime/TimestampTest.java
- Fix timezone dependent test failures.
- Those tests were failing while local date is different between UTC and local timezone. 
n/a
> Fix timezone dependent test failures

- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
- integ-test/src/test/resources/expectedOutput/calcite/explain_prevent_limit_push.yaml
- integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3102.yml
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/AbstractCalciteIndexScan.java
- opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteLogicalIndexScan.java
https://github.com/opensearch-project/sql/pull/3713 tried to prevent push down limit with offset reach maxResultWindow in action being executing (applying) which didn't work in v3.
Fixing: Prevent limit pushdown before action building instead of in action executing
Resolves #4376 
> Prevent limit pushdown before action building instead of in action executing

- integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java
- integ-test/src/test/resources/expectedOutput/calcite/explain_filter_with_search.yaml
- opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
Fix bug of missed analyzed node when pushdown filter for Search call
Resolves #4387 
> Fix bug of missed analyzed node when pushdown filter for Search call

- opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequestTest.java
- opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchRequestBuilderTest.java
Reverting the sort key back to _doc + _id
#4378
> reverting to _doc + _id
