.github/draft-release-notes-config.yml, .github/workflows/draft-release-notes-workflow.yml, release-notes/opensearch-sql.release-notes-1.0.0.0-beta1.md
Change title and version in release note drafter workflow.
N/A
=> Add release notes for OpenSearch 1.0.0.0-beta1

.github/workflows/sql-test-and-build-workflow.yml, build.gradle, doctest/build.gradle, sql-jdbc/build.gradle
1. Build SQL/PPL plugin against OpenSearch 1.0.0-beta1
2. Rename JDBC jar file name with 1.0.0.0-beta1 suffix
N/A
=> Build SQL/PPL against OpenSearch 1.0.0-beta1

.github/workflows/sql-workbench-release-workflow.yml, .github/workflows/sql-workbench-test-and-build-workflow.yml, workbench/opensearch_dashboards.json, workbench/package.json
Bump to beta1 for OpenSearch beta release
=> Bump Workbench Version to Beta1 for OpenSearch Release

.github/draft-release-notes-config.yml, release-notes/opensearch-sql.release-notes-1.0.0.0-beta1.md
Update release notes with most recent PR links for 1.0.0.0 beta1 release.
N/A
=> Update 1.0.0.0-beta1 release notes with new PRs

workbench/public/plugin.ts
changing nav bar category id to opensearch to be consistent with other plugins
=> Update workbench nav category to opensearch

sql-cli/src/opensearch_sql_cli/opensearch_connection.py, sql-cli/tests/test_opensearch_connection.py
- Fix some functions and var that still contains `opendistro`
=> fix opendistro related renaming for sql-cli

.github/ISSUE_TEMPLATE/bug_template.md, workbench/public/components/Main/main.tsx
Signed-off-by: Vacha Shah <vachshah@amazon.com>
This PR intends to add multiple labels for the issue template to better categorize the issues.
=> Update issue template with multiple labels

sql-cli/README.md, sql-cli/development_guide.md, sql-cli/setup.py, sql-cli/tests/test_plan.md
Signed-off-by: David Cui <davidcui@amazon.com>
* Update documentation links to OpenSearch
=> Update sqli-cli documentation links to OpenSearch

integ-test/src/test/java/org/opensearch/sql/legacy/MethodQueryIT.java, integ-test/src/test/java/org/opensearch/sql/legacy/QueryIT.java, legacy/src/main/java/org/opensearch/sql/legacy/domain/Condition.java, legacy/src/main/java/org/opensearch/sql/legacy/query/maker/Maker.java
Original PR: https://github.com/opendistro-for-elasticsearch/sql/pull/1097
Author: @FreCap 
NA
=> Migrate #1097: Adding support to NOT REGEXP_QUERY

release-notes/opensearch-sql.release-notes-1.0.0.0-rc1.md
Add release notes for OpenSearch RC1 release
https://github.com/opensearch-project/sql/issues/86
=> Add release notes for OpenSearch RC1 release

README.md
Refactor README markdown and consistent with others: https://github.com/opensearch-project/common-utils/blob/main/README.md
The new README after rework: https://github.com/dai-chen/sql-1/tree/level-up-readme-markdown
https://github.com/opensearch-project/sql/issues/147
=> Level up README markdown

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/sql-test-and-build-workflow.yml, .github/workflows/sql-workbench-release-workflow.yml, .github/workflows/sql-workbench-test-and-build-workflow.yml, README.md, build.gradle, integtest.sh, release-notes/opensearch-sql.release-notes-1.0.0.0.md, sql-cli/src/opensearch_sql_cli/__init__.py, sql-jdbc/build.gradle, sql/src/main/antlr/OpenSearchSQLParser.g4, sql/src/test/java/org/opensearch/sql/sql/antlr/SQLSyntaxParserTest.java, workbench/opensearch_dashboards.json, workbench/package.json
Merge latest changes in main branch to 1.0 branch
N/A
=> Merge latest changes in main branch to 1.0 branch

.github/workflows/link-checker.yml, .github/workflows/sql-cli-release-workflow.yml, .github/workflows/sql-cli-test-and-build-workflow.yml, .github/workflows/sql-jdbc-push-jdbc-maven.yml, .github/workflows/sql-release-workflow.yml, .github/workflows/sql-test-and-build-workflow.yml, README.md, docs/dev/NewSQLEngine.md, release-notes/opensearch-sql.release-notes-1.1.0.0.md, sql-cli/CONTRIBUTING.md, sql-cli/README.md, sql-jdbc/CONTRIBUTING.md, sql-odbc/CONTRIBUTING.md, workbench/README.md, workbench/release-notes/sql-workbench.release-notes-1.7.0.0.md
=> [1.1] Bump opensearch ref to 1.1 in CI

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/sql-odbc-release-workflow.yml, .github/workflows/sql-odbc-rename-and-release-workflow.yml, .github/workflows/sql-test-and-build-workflow.yml, .github/workflows/sql-workbench-release-workflow.yml, .github/workflows/sql-workbench-test-and-build-workflow.yml, CONTRIBUTING.md, build.gradle, integ-test/src/test/java/org/opensearch/sql/correctness/tests/ComparisonTestTest.java, sql-cli/src/opensearch_sql_cli/__init__.py, sql-jdbc/build.gradle, sql-odbc/src/CMakeLists.txt, sql-odbc/src/TableauConnector/opensearch_sql_odbc/manifest.xml, sql-odbc/src/TableauConnector/opensearch_sql_odbc_dev/manifest.xml, workbench/opensearch_dashboards.json, workbench/package.json
Signed-off-by: Tengda He <tengh@amazon.com>
Updates dashbquery-workbench-dashboardsoards version to 1.2. Changes the package jsons, as well as the github action workflows.
#214 
=> Bumps version to 1.2

release-notes/opensearch-sql.release-notes-1.2.0.0.md
=> Create 1.2 release notes

NOTICE, README.md, sql-cli/NOTICE, sql-cli/README.md, sql-jdbc/NOTICE, sql-jdbc/README.md, sql-odbc/NOTICE, sql-odbc/README.md, workbench/NOTICE, workbench/README.md
Update notice files and readmes
#175 
=> Update notice files

release-notes/opensearch-sql.release-notes-1.2.0.0.md
Update release notes for 1.2 release
=> Update release notes for 1.2 release

sql-cli/src/opensearch_sql_cli/formatter.py
- catch and re-throw errors
#295 
=> [sql-cli]wrap error response into exception

README.md
Added code summary table with badges.
1. Deleted old badges
2. Updated badges for code cov
3. Updated documentation link
=> Code Summary Table

.github/workflows/sql-test-and-build-workflow.yml, build.gradle
Coming from https://github.com/opensearch-project/opensearch-build/issues/1365.
=> Incremented version to 1.2.3.

.github/workflows/sql-test-and-build-workflow.yml, build.gradle, common/build.gradle, integ-test/build.gradle, ppl/build.gradle, release-notes/opensearch-sql.release-notes-1.2.3.0.md
Update release bump and log4j changes from 1.2.3
updated workflow, gradle and release notes
=> backporting log4j to main

.github/workflows/sql-test-and-build-workflow.yml, build.gradle
=> Bump sql main to 1.3.0

workbench/README.md, workbench/public/components/Main/__snapshots__/main.test.tsx.snap, workbench/public/components/Main/main.tsx
fixes https://github.com/opensearch-project/sql/issues/350
=> Update docs links for workbench

.github/workflows/sql-test-and-build-workflow.yml, build.gradle, common/build.gradle, integ-test/build.gradle, ppl/build.gradle, release-notes/opensearch-sql.release-notes-1.2.4.0.md
Incremented version to 1.2.4, upgraded log4j, added release notes.
=> Incremented version to 1.2.4, upgraded log4j, added release notes.

release-notes/opensearch-sql.release-notes-1.2.4.0.md
Update release notes 1.2.4 with latest commits
=> Update release notes 1.2.4

release-notes/opensearch-sql.release-notes-1.2.4.0.md
Backport release notes 1.2.4 with latest commits
=> [1.2] Update release notes 1.2.4

build.gradle, sql-jdbc/build.gradle
=> Remove jcenter in sql and jdbc

build.gradle, sql-jdbc/build.gradle
=> [1.2] Remove jcenter in sql and jdbc

sql-odbc/README.md
- add a link to the iODBC Driver Manager so it is easier to navigate and install the driver manger
add a link to the iODBC Driver Manager so it is easier to navigate and install the driver manger
only clarify the documentation, no code changes or new functionality
not applicable
not applicable
not applicable
not applicable
not applicable
not applicable
Signed-off-by: Alina (Xi) Li <alinal@bitquilltech.com>
=> Update the README file and and a link to the iODBC

.github/workflows/link-checker.yml, .github/workflows/sql-cli-test-and-build-workflow.yml, sql-cli/README.md, sql-cli/development_guide.md, sql-cli/setup.py
Rename the package
https://github.com/opensearch-project/sql/issues/387
=> Rename `opensearch-sql-cli` to `opensearch-sqlcli` to unblock release

build.gradle, common/build.gradle, core/build.gradle, integ-test/build.gradle, legacy/build.gradle, plugin/build.gradle, ppl/build.gradle, protocol/build.gradle, sql/build.gradle
Updating guava Package to the latest version
updated all the gradle files
=> Guava package update

.github/workflows/link-checker.yml, .github/workflows/sql-cli-test-and-build-workflow.yml, sql-cli/README.md, sql-cli/development_guide.md, sql-cli/setup.py
=> rename package name of sql-cli from `opensearch-sqlcli` to `opensearchsql`

.github/workflows/link-checker.yml, .github/workflows/sql-cli-test-and-build-workflow.yml, sql-cli/README.md, sql-cli/development_guide.md, sql-cli/setup.py
=> [sql-cli-1.0] rename package name of sql-cli from `opensearch-sqlcli` to `opensearchsql`

.github/workflows/link-checker.yml, docs/user/ppl/functions/conversion.rst, docs/user/ppl/index.rst, ppl/src/main/antlr/OpenSearchPPLLexer.g4, ppl/src/main/antlr/OpenSearchPPLParser.g4, ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java, ppl/src/test/java/org/opensearch/sql/ppl/parser/AstExpressionBuilderTest.java, sql-odbc/CONTRIBUTING.md, sql-odbc/README.md, sql-odbc/docs/user/power_bi_support.md
Add type conversion function to PPL
Add docs
=> Add cast function to PPL

integ-test/src/test/java/org/opensearch/sql/legacy/JdbcTestIT.java
Disable flaky test in JdbcTestIT.
#453 
=> Disable flaky test in JdbcTestIT.

opensearch/build.gradle
Signed-off-by: jackieyanghan <jkhanjob@gmail.com>
Update dependency ml-client group name based on this change - https://github.com/opensearch-project/ml-commons/commit/e89540516a3f92e0e016f079f63e6bd3452eb08f
=> Update dependency opensearch-ml-client group name

opensearch/build.gradle
Signed-off-by: jackieyanghan <jkhanjob@gmail.com>
Update dependency ml-client group name based on this change - https://github.com/opensearch-project/ml-commons/commit/e89540516a3f92e0e016f079f63e6bd3452eb08f
=> [Backport to 1.x] Update dependency opensearch-ml-client group name

docs/user/ppl/index.rst
=> Add parse docs to PPL commands index

release-notes/opensearch-sql.release-notes-1.3.0.0.md
=> Add 1.3 release notes

release-notes/opensearch-sql.release-notes-1.3.0.0.md
Backport #490 
Signed-off-by: Eugene Lee <eugenesk@amazon.com>
(cherry picked from commit fff24aaca82fba99b54fb14f9bc2a623d1a3e566)
=> [Backport 1.x]  Add 1.3.0 release notes #490

workbench/opensearch_dashboards.json, workbench/package.json
=> Add alpha1 qualifiers for dashboards plugin

core/build.gradle, plugin/build.gradle, ppl/build.gradle, sql/build.gradle
* https://github.com/opensearch-project/sql/issues/525
* Related to https://github.com/opensearch-project/OpenSearch/issues/2699
=> Version Bump: spring-beans-5.2.19 -> spring-beans-5.2.20

release-notes/opensearch-sql.release-notes-2.0.0.0-rc1.md
=> 2.0.0.0-rc1 release notes

.github/workflows/sql-workbench-test-and-build-workflow.yml, build.gradle, doctest/build.gradle, sql-jdbc/build.gradle, workbench/opensearch_dashboards.json, workbench/package.json
Increment version to 2.0.1
Part of https://github.com/opensearch-project/opensearch-build/issues/2165
=> Incremented version to 2.0.1

.github/workflows/sql-test-and-build-workflow.yml, .gitignore, plugin/build.gradle, scripts/build.sh, scripts/bwctest.sh
=> Uses custom plugin to publish zips to maven 

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/sql-odbc-release-workflow.yml, .github/workflows/sql-workbench-release-workflow.yml, .github/workflows/sql-workbench-test-and-build-workflow.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties, sql-jdbc/build.gradle, workbench/opensearch_dashboards.json, workbench/package.json
Signed-off-by: Kavitha Conjeevaram Mohan <mohakavi@amazon.com>
version bump to 2.1.0 and gradle version bump to 7.4.2
=> version bump to 2.1.0 and gradle version bump

release-notes/opensearch-sql.release-notes-2.1.0.0.md
Signed-off-by: Kavitha Conjeevaram Mohan [mohakavi@amazon.com](mailto:mohakavi@amazon.com)
Add 2.1.0 release notes
=> 2.1 release notes

release-notes/opensearch-sql.release-notes-2.1.0.0.md
Signed-off-by: Kavitha Conjeevaram Mohan <mohakavi@amazon.com>
change 2.1 version bump PR under maintenance 
=> change version bump under maintenance

.github/workflows/sql-test-and-build-workflow.yml, .github/workflows/sql-workbench-test-and-build-workflow.yml, build.gradle, doctest/build.gradle, integ-test/build.gradle, opensearch/build.gradle, plugin/build.gradle, protocol/build.gradle, workbench/opensearch_dashboards.json, workbench/package.json
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Increment version to 1.3.4
Part of https://github.com/opensearch-project/opensearch-build/issues/2205
=> Incremented version to 1.3.4.

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/sql-odbc-release-workflow.yml, .github/workflows/sql-workbench-release-workflow.yml, .github/workflows/sql-workbench-test-and-build-workflow.yml, build.gradle, core/build.gradle, integ-test/build.gradle, opensearch/build.gradle, plugin/build.gradle, ppl/build.gradle, sql-jdbc/build.gradle, sql/build.gradle, workbench/opensearch_dashboards.json, workbench/package.json
- [] New functionality includes testing.
=> Bump version to 2.2.0

release-notes/opensearch-sql.release-notes-2.2.0.0.md
=> Add release notes for 2.2.0.0

workbench/opensearch_dashboards.json
=> Bump workbench version to 2.2.0.0

workbench/public/components/Main/__snapshots__/main.test.tsx.snap, workbench/public/components/QueryResults/__snapshots__/QueryResults.test.tsx.snap, workbench/public/components/QueryResults/__snapshots__/QueryResultsBody.test.tsx.snap
=> Update snapshots for jest tests on workbench

docs/user/beyond/fulltext.rst
Call out distinction between original and current SQL engines.
Signed-off-by: MaxKsyunz <maxk@bitquilltech.com>
=> Minor documentation update

workbench/yarn.lock
=> Upgrade yarn dependencies for workbench

MAINTAINERS.md
Following https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#addition to update maintainer list with nominees. The maintainers have voted and agreed to this nomination and the nominee confirmed their interest in becoming co-maintainer.
N/A
=> Update maintainer list

release-notes/opensearch-sql.release-notes-2.3.0.0.md
=> add 2.3 release notes

.github/workflows/draft-release-notes-workflow.yml, .github/workflows/sql-odbc-release-workflow.yml, .github/workflows/sql-workbench-release-workflow.yml, .github/workflows/sql-workbench-test-and-build-workflow.yml, build.gradle, workbench/opensearch_dashboards.json, workbench/package.json
=> Bump version to 2.4

docs/user/ppl/cmd/patterns.rst
=> Fix indentation of patterns example

.github/workflows/sql-test-and-build-workflow.yml, .github/workflows/sql-workbench-test-and-build-workflow.yml, build.gradle, doctest/build.gradle, workbench/opensearch_dashboards.json, workbench/package.json
https://github.com/opensearch-project/sql/pull/812 won't let me amend PR, sending one manually
closes #812 
=> [1.3] Increment version to 1.3.6-SNAPSHOT

.github/workflows/sql-workbench-release-workflow.yml, .github/workflows/sql-workbench-test-and-build-workflow.yml, build.gradle, workbench/opensearch_dashboards.json, workbench/package.json
Signed-off-by: MaxKsyunz <maxk@bitquilltech.com>
https://github.com/opensearch-project/sql/pull/836
=> Bump to 2.3.1

plugin/build.gradle
Change group to groupId
https://github.com/opensearch-project/sql/pull/906
=> Update group to groupId

release-notes/opendistro-for-elasticsearch-sql.release-notes-1.3.0.0.md, release-notes/opensearch-sql.release-notes-1.2.0.0.md
Backport #911 to `main`.
See #911
=> [Backport `main`] Fix broken links #911

release-notes/opendistro-for-elasticsearch-sql.release-notes-1.3.0.0.md, release-notes/opensearch-sql.release-notes-1.2.0.0.md
=> [Backport 1.x] Fix broken links #911

.github/workflows/sql-workbench-test-and-build-workflow.yml
Signed-off-by: Derek Ho <dxho@amazon.com>
=> change condition to always upload coverage for linux workbench

build.gradle, core/build.gradle, integ-test/build.gradle, opensearch/build.gradle, plugin/build.gradle, prometheus/build.gradle, protocol/build.gradle
Signed-off-by: Margarit Hakobyan <margarith@bitquilltech.com>
=> Update Jackson Databind version to 2.13.4.2

sql-cli/src/opensearch_sql_cli/__init__.py
* Bump the version to 1.1.0. 
* Enhancement https://github.com/opensearch-project/sql/pull/918
=> Bump sql-cli version to 1.1.0

prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClientImpl.java
* Improved messaging from prometheus response.
=> Fix error messaging from prometheus.

build.gradle
* https://github.com/opensearch-project/sql/issues/1123
=> Bump jackson version to 2.14.1

.github/workflows/sql-workbench-test-and-build-workflow.yml, workbench/opensearch_dashboards.json, workbench/package.json, workbench/yarn.lock
Signed-off-by: YANG-DB <yang-db-dev@gmail.com>
Bump node libraries
CVE fixes 
=> Bump node library versions for 1.3

.github/workflows/sql-workbench-test-and-build-workflow.yml, workbench/opensearch_dashboards.json, workbench/package.json
- sql-cli
- sql-odbc
- sql-jdbc
- dashboards-query-workbench
Signed-off-by: YANG-DB <yang-db-dev@gmail.com>
=> revert minor version change as not compatible with last version

build.gradle
=> Upgrade jackson to 2.14.1

release-notes/opensearch-sql.release-notes-1.3.7.0.md
Add release notes for OpenSearch 1.3.7 release.
N/A
=> Add release notes for 1.3.7 release

release-notes/opensearch-sql.release-notes-2.4.1.0.md
Add release note for OpenSearch 2.4.1 release.
N/A
=> Add release note for 2.4.1 release

prometheus/src/main/java/org/opensearch/sql/prometheus/storage/querybuilder/SeriesSelectionQueryBuilder.java, prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusMetricTableTest.java
Fix Below Bug: https://github.com/opensearch-project/sql/issues/1243
https://github.com/opensearch-project/sql/issues/1243
=> Fixed error with single timestamp filter query on prometheus datasource

README.md
Update README after repo split.
N/A
=> Remove obsolete links from README.

.github/workflows/link-checker.yml
Fix link checker CI workflow.
Link checker was failing without any error produced.
=> Update link checker CI workflow.

integ-test/build.gradle, plugin/src/test/java/org/opensearch/sql/plugin/datasource/DataSourceMetaDataTest.java
Related to mockito version bump in OpenSearch Core. https://github.com/opensearch-project/OpenSearch/pull/6076
=> Fix ArgumentCaptor can't capture varargs

.github/workflows/sql-test-and-build-workflow.yml, .gitignore, build-tools/sqlplugin-coverage.gradle, buildSrc/src/main/groovy/com/wiredforcode/spawn/KillProcessTask.groovy, buildSrc/src/main/groovy/com/wiredforcode/spawn/SpawnProcessTask.groovy, doctest/build.gradle, integ-test/build.gradle, integ-test/src/test/java/org/opensearch/sql/ppl/CsvFormatIT.java, integ-test/src/test/java/org/opensearch/sql/ppl/DescribeCommandIT.java, integ-test/src/test/java/org/opensearch/sql/ppl/InformationSchemaCommandIT.java, integ-test/src/test/java/org/opensearch/sql/sql/CsvFormatIT.java, integ-test/src/test/java/org/opensearch/sql/sql/RawFormatIT.java, scripts/integtest.sh
* Integ Test Refactoring
(cherry picked from commit 8f6793ba63cb8c0301447276ae65a3e3f46563bd)
=> [Backport PR main]Integ Test Refactoring (#1383)

core/src/main/java/org/opensearch/sql/expression/DSL.java, core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java, core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java, core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java, docs/user/dql/functions.rst, integ-test/src/test/java/org/opensearch/sql/sql/MathematicalFunctionIT.java, sql/src/main/antlr/OpenSearchSQLParser.g4
Added COSH to V2 engine, updated documentation, added unit/IT tests
=> Added COSH to V2 engine

integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java
Backport https://github.com/opensearch-project/sql/commit/71d860410efa00a44290be030a9e148b29cd4fe9 from https://github.com/opensearch-project/sql/pull/1380.
1. Backport to main because main was broken and this was urgent request for 2.6 release
2. Backport manually because Bot PR failed due to code conflicts
=> [Backport main] Exclude OpenSearch system index when IT cleanup

release-notes/opensearch-sql.release-notes-2.7.0.0.md
=> Release Notes for 2.7.0

release-notes/opensearch-sql.release-notes-2.7.0.0.md
=> release notes for 2.7.0 PATCH

release-notes/opensearch-sql.release-notes-2.7.0.0.md
Updated release notes for fix in https://github.com/opensearch-project/sql/pull/1561
N/A
=> updating release notes 2.7.0.0

.github/workflows/flint-test-and-build-workflow.yml, flint/.scalafmt.conf, flint/DEVELOPER_GUIDE.md, flint/build.sbt, flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkExtensions.scala, flint/project/plugins.sbt
* add scalafmt in developer guide, https://github.com/penghuo/os-sql/blob/feature/flint-codeformat/flint/DEVELOPER_GUIDE.md
* add flint ci. https://github.com/opensearch-project/sql/actions/runs/4865527681/jobs/8675946878?pr=1601
N/A
=> add flint CI workflow add scalafmt

flint/.scalafmt.conf, flint/DEVELOPER_GUIDE.md, flint/build.sbt, flint/dev/.scalafmt.conf, flint/project/plugins.sbt, flint/scalastyle-config.xml
1. align with spark scalastyle.
2. enhance scalafmt.
3. change the developer_guide doc. https://github.com/penghuo/os-sql/blob/feature/flint-codeformat/flint/DEVELOPER_GUIDE.md
N/A
=> align with Spark scalastyle

docs/user/ppl/admin/cross_cluster_search.rst
Update usage example doc for PPL cross-cluster search
#789 
=> Update usage example doc for PPL cross-cluster search

flint/DEVELOPER_GUIDE.md, flint/build.sbt, flint/flint-spark-integration/src/main/java/org/opensearch/io/OpenSearchOptions.java, flint/flint-spark-integration/src/main/java/org/opensearch/io/OpenSearchReader.java, flint/flint-spark-integration/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/v2/OpenSearchJsonDataSourceV2.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/v2/OpenSearchPartitionReader.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/v2/OpenSearchPartitionReaderFactory.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/v2/OpenSearchScan.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/v2/OpenSearchScanBuilder.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/v2/OpenSearchTable.scala, flint/flint-spark-integration/src/test/java/org/opensearch/testcontainers/OpenSearchContainer.java, flint/flint-spark-integration/src/test/scala/org/apache/spark/FirstITSuit.scala, flint/flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala, flint/flint-spark-integration/src/test/scala/org/apache/spark/OpenSearchIndex.scala, flint/flint-spark-integration/src/test/scala/org/apache/spark/OpenSearchSuite.scala, flint/flint-spark-integration/src/test/scala/org/opensearch/io/OpenSearchOptionsTest.scala, flint/integ-test/src/test/scala/org/apache/spark/OpenSearchITSuite.scala, flint/project/Dependencies.scala, flint/project/plugins.sbt
1. Update developer guide. https://github.com/penghuo/os-sql/blob/feature/flint-datasourcev2/flint/DEVELOPER_GUIDE.md.
2. Please ignore review code in `org.opensearch.io.*` which is only for making IT running.
n/a
=> Init OpenSearch DataSourceV2 and IT

build.gradle
Cover CVE-2023-20863 https://www.mend.io/vulnerability-database/CVE-2023-20863
=> Update Spring to 5.3.25 to cover CVE-2023-20863 "spring-expression DDOS"

docs/user/ppl/admin/cross_cluster_search.rst, docs/user/ppl/admin/security.rst, docs/user/ppl/cmd/search.rst, docs/user/ppl/general/identifiers.rst, docs/user/ppl/index.rst, integ-test/build.gradle, integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java, integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java, integ-test/src/test/java/org/opensearch/sql/ppl/CrossClusterSearchIT.java, opensearch/src/main/java/org/opensearch/sql/opensearch/request/OpenSearchScrollRequest.java, opensearch/src/main/java/org/opensearch/sql/opensearch/request/system/OpenSearchDescribeIndexRequest.java, opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequestTest.java, opensearch/src/test/java/org/opensearch/sql/opensearch/request/system/OpenSearchDescribeIndexRequestTest.java, ppl/src/main/antlr/OpenSearchPPLLexer.g4, ppl/src/main/antlr/OpenSearchPPLParser.g4, ppl/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java, ppl/src/test/java/org/opensearch/sql/ppl/antlr/PPLSyntaxParserTest.java, ppl/src/test/java/org/opensearch/sql/ppl/parser/AstBuilderTest.java
Backport 1bda5fe73312017b3bc6029e2eaf378c2e72306c from #1512 
=> [Backport 2.x] Cross cluster search in PPL (#1512)

flint/flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintDataSourceV2.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionReaderFactory.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionWriter.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionWriterFactory.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintScan.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintScanBuilder.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintTable.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintWrite.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintConfig.scala, flint/flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala, flint/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala, flint/flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala, flint/integ-test/src/test/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala, flint/integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala, flint/integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSuite.scala
add flint spark configuration in central class.
n/a
=> add flint spark configuration

release-notes/opensearch-sql.release-notes-2.8.0.0.md
Release notes for release 2.8.0.0
=> Release Notes for 2.8.0

integ-test/build.gradle
=> Bump bwc opensearch version to 2.9

doctest/build.gradle, plugin/build.gradle
https://github.com/opensearch-project/sql/pull/1747
=> [2.x manual backport] Stop prometheus in doctest build.gradle now runs upon project failure in startOpenSearch

docs/user/dql/expressions.rst, docs/user/general/datatypes.rst
Update docs for #1821, #1196 and #1206.
Add missing doc updates.
=> Update docs to reflect recent changes. (#285)

datasources/src/main/java/org/opensearch/sql/datasources/exceptions/ErrorMessage.java, datasources/src/main/java/org/opensearch/sql/datasources/rest/RestDataSourceQueryAction.java
Backport https://github.com/opensearch-project/sql/pull/1753
=> Backport https://github.com/opensearch-project/sql/pull/1753 to 2.x

integ-test/build.gradle
=> Bump bwc version

opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchRestClientTest.java
Renamed in https://github.com/opensearch-project/OpenSearch/pull/8940. Related to #1899.
Fix build.
=> Fix renamed imports

opensearch/src/main/java/org/opensearch/sql/opensearch/monitor/OpenSearchResourceMonitor.java, opensearch/src/main/java/org/opensearch/sql/opensearch/setting/LegacyOpenDistroSettings.java, opensearch/src/test/java/org/opensearch/sql/opensearch/monitor/OpenSearchResourceMonitorTest.java, opensearch/src/test/java/org/opensearch/sql/opensearch/setting/OpenSearchSettingsTest.java
Fixed breaking imports from https://github.com/opensearch-project/OpenSearch/pull/9006
=> Fixed refactored imports

release-notes/opensearch-sql.release-notes-1.3.12.0.md
=> Add release notes for 1.3.12

legacy/src/main/antlr/OpenSearchLegacySqlParser.g4, ppl/src/main/antlr/OpenSearchPPLParser.g4, sql/src/main/antlr/OpenSearchSQLParser.g4
Changed formatting of Antlr `parser` files based on Spotless changes. I have not applied the changes made to the `lexer` files as it completely rewrites the files to make them much less readable
N/A
=> Applied formatting improvements to Antlr files based on spotless changes

datasources/src/main/java/org/opensearch/sql/datasources/exceptions/DataSourceClientException.java, plugin/src/main/java/org/opensearch/sql/plugin/rest/RestPPLQueryAction.java, prometheus/src/main/java/org/opensearch/sql/prometheus/client/PrometheusClientImpl.java, prometheus/src/main/java/org/opensearch/sql/prometheus/exceptions/PrometheusClientException.java, prometheus/src/main/java/org/opensearch/sql/prometheus/request/system/PrometheusDescribeMetricRequest.java, prometheus/src/main/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactory.java, prometheus/src/test/java/org/opensearch/sql/prometheus/client/PrometheusClientImplTest.java, prometheus/src/test/java/org/opensearch/sql/prometheus/storage/PrometheusStorageFactoryTest.java, prometheus/src/test/resources/non_json_response.json
(cherry picked from commit 56bc7d5e168d22f2874d07179824c1ba6f660d27)
=> Fixed Security Exceptions For Requests Wihtout PPL Access (#2033)

integ-test/build.gradle, plugin/build.gradle
https://github.com/opensearch-project/sql/issues/2037
https://github.com/opensearch-project/sql/issues/2037
=> bump okhttp to 4.10.0

integ-test/build.gradle, plugin/build.gradle
backport https://github.com/opensearch-project/sql/pull/2043
=> [2.x] bump okhttp to 4.10.0 (#2043)

plugin/build.gradle
https://github.com/opensearch-project/sql/issues/2037
https://github.com/opensearch-project/sql/issues/2037
=> bump okio to 3.4.0

plugin/build.gradle
https://github.com/opensearch-project/sql/issues/2037
https://github.com/opensearch-project/sql/issues/2037
=> [2.x] bump okio to 3.4.0

release-notes/opensearch-sql.release-notes-2.10.0.0.md
=> add 2.10 release notes

release-notes/opensearch-sql.release-notes-2.11.0.0.md
Add 2.11 version release notes
=> release-notes-2.11

integ-test/build.gradle
=> Bump bwc verison to 2.12

spark/src/main/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcher.java, spark/src/main/java/org/opensearch/sql/spark/execution/statement/StatementModel.java, spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceImplSpecTest.java, spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
https://github.com/opensearch-project/sql/issues/2360
https://github.com/opensearch-project/sql/issues/2360
=> Create new session if client provided session is invalid

release-notes/opensearch-sql.release-notes-2.12.0.0.md
Added release notes for 2.12.0.0
=> Add release notes for 2.12.0.0

release-notes/opensearch-sql.release-notes-1.3.15.0.md
=> Add release notes for 1.3.15

spark/src/main/java/org/opensearch/sql/spark/asyncquery/model/SparkSubmitParameters.java, spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Wrap the query with double quotes
=> [Bugfix] Wrap the query with double quotes

docs/user/ppl/admin/connectors/spark_connector.rst, spark/src/main/java/org/opensearch/sql/spark/data/constants/SparkConstants.java, spark/src/test/java/org/opensearch/sql/spark/constants/TestConstants.java, spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java
Upgrade opensearch-spark jars to 0.3.0
=> Upgrade opensearch-spark jars to 0.3.0

release-notes/opensearch-sql.release-notes-2.13.0.0.md
Added release notes for 2.13.0.0
=> Added release notes for 2.13.0.0

release-notes/opensearch-sql.release-notes-2.13.0.0.md
- Updated opensearch-sql.release-notes-2.13.0.0.md to conform with OpenSearch guidelines
https://github.com/opensearch-project/sql/issues/2599
=> Update opensearch-sql.release-notes-2.13.0.0.md to conform with OpenSearch guidelines

integ-test/build.gradle
=> Bump bwc version to 2.14

release-notes/opensearch-sql.release-notes-2.14.0.0.md
=> release notes for 2.14.0.0

plugin/src/main/java/org/opensearch/sql/plugin/SQLPlugin.java, spark/src/main/java/org/opensearch/sql/spark/cluster/ClusterManagerEventListener.java, spark/src/main/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTask.java, spark/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java, spark/src/main/java/org/opensearch/sql/spark/dispatcher/QueryHandlerFactory.java, spark/src/main/java/org/opensearch/sql/spark/dispatcher/RefreshQueryHandler.java, spark/src/main/java/org/opensearch/sql/spark/flint/IndexDMLResultStorageService.java, spark/src/main/java/org/opensearch/sql/spark/flint/OpenSearchIndexDMLResultStorageService.java, spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOp.java, spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpAlter.java, spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpCancel.java, spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpDrop.java, spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpFactory.java, spark/src/main/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpVacuum.java, spark/src/main/java/org/opensearch/sql/spark/transport/config/AsyncExecutorServiceModule.java, spark/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryExecutorServiceSpec.java, spark/src/test/java/org/opensearch/sql/spark/cluster/FlintStreamingJobHouseKeeperTaskTest.java, spark/src/test/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandlerTest.java, spark/src/test/java/org/opensearch/sql/spark/dispatcher/SparkQueryDispatcherTest.java, spark/src/test/java/org/opensearch/sql/spark/flint/operation/FlintIndexOpTest.java
* Refactor IndexDMLHandler and related classes to reduce the direct dependency to StateStore and abstract data store.
N/A
=> Refactor IndexDMLHandler and related classes

release-notes/opensearch-sql.release-notes-2.15.0.0.md
- Added v2.15 release notes
- https://github.com/opensearch-project/sql/issues/2656
=> Add v2.15.0 release notes

core/src/main/java/org/opensearch/sql/datasource/model/DataSourceType.java
- Fix code style issue. (Seems I missed one code style issue in the last PR)
=> Fix code style issue

async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/InteractiveSession.java
- Fix statement to store requested langType
n/a
=> Fix statement to store requested langType

async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- Fix build failure due to the merge of multiple PRs
n/a
=> Fix build failure

.github/CODEOWNERS, MAINTAINERS.md
Welcome new maintainer [LantaoJin](https://github.com/LantaoJin)
n/a
=> Welcome new maintainer LantaoJin

.github/workflows/integ-tests-with-security.yml, .github/workflows/sql-test-and-build-workflow.yml
Manually backport https://github.com/opensearch-project/sql/pull/2831 due to conflicts
=> [Backport 2.x] Fix MacOS workflow failure

integ-test/src/test/java/org/opensearch/sql/datasource/DataSourceEnabledIT.java, integ-test/src/test/java/org/opensearch/sql/legacy/OpenSearchSQLRestTestCase.java
Fix integration tests issues with 2.16 release.
https://github.com/opensearch-project/sql/issues/2848
=> Fixes for 2.16 integ test failures

integ-test/src/test/java/org/opensearch/sql/legacy/SQLIntegTestCase.java, integ-test/src/test/java/org/opensearch/sql/legacy/TestUtils.java, integ-test/src/test/java/org/opensearch/sql/legacy/TestsConstants.java, integ-test/src/test/java/org/opensearch/sql/sql/GeopointFormatsIT.java, integ-test/src/test/resources/geopoints.json, integ-test/src/test/resources/indexDefinitions/geopoint_index_mapping.json, opensearch/src/main/java/org/opensearch/sql/opensearch/data/utils/OpenSearchJsonContent.java, opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java, opensearch/src/test/java/org/opensearch/sql/opensearch/data/utils/OpenSearchJsonContentTest.java, opensearch/src/test/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactoryTest.java
=> [Backport 2.x] Support common format geo point

core/src/main/java/org/opensearch/sql/executor/Explain.java, core/src/main/java/org/opensearch/sql/planner/DefaultImplementor.java, core/src/main/java/org/opensearch/sql/planner/physical/PhysicalPlanDSL.java, core/src/main/java/org/opensearch/sql/planner/physical/PhysicalPlanNodeVisitor.java, core/src/main/java/org/opensearch/sql/planner/physical/SortHelper.java, core/src/main/java/org/opensearch/sql/planner/physical/SortOperator.java, core/src/main/java/org/opensearch/sql/planner/physical/TakeOrderedOperator.java, core/src/test/java/org/opensearch/sql/executor/ExplainTest.java, core/src/test/java/org/opensearch/sql/planner/DefaultImplementorTest.java, core/src/test/java/org/opensearch/sql/planner/physical/PhysicalPlanNodeVisitorTest.java, core/src/test/java/org/opensearch/sql/planner/physical/TakeOrderedOperatorTest.java, docs/user/optimization/optimization.rst, opensearch/src/main/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtector.java, opensearch/src/test/java/org/opensearch/sql/opensearch/executor/protector/OpenSearchExecutionProtectorTest.java
=> [Backport 2.x] add TakeOrderedOperator

async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/BatchQueryHandler.java, async-query-core/src/main/java/org/opensearch/sql/spark/dispatcher/IndexDMLHandler.java, async-query-core/src/test/java/org/opensearch/sql/spark/asyncquery/AsyncQueryCoreIntegTest.java
- Fix jobType for Batch and IndexDML query
=> Fix jobType for Batch and IndexDML query

async-query/src/main/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposer.java, async-query/src/test/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposerTest.java
cherry-pick [22ee2b3](https://github.com/opensearch-project/sql/pull/2989/commits/22ee2b390fbc0a5481bfda1c6595da47e84a9219) from https://github.com/opensearch-project/sql/pull/2989
=> Fix type mismatch

integ-test/build.gradle
=> Bump BWC version to 2.17

async-query/src/main/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposer.java, async-query/src/test/java/org/opensearch/sql/spark/config/OpenSearchAsyncQuerySchedulerConfigComposerTest.java
Optimize scheduler interval conf
=> Optimize scheduler interval conf

.github/workflows/integ-tests-with-security.yml, .github/workflows/sql-test-and-build-workflow.yml, datasources/build.gradle
Backport https://github.com/opensearch-project/sql/commit/25064688db2d08e61579aaf7d21ff440c67605a4 from https://github.com/opensearch-project/sql/pull/3004.
=> [Backport 2.17] Upgrade org.bouncycastle:bcprov-jdk18on to 1.78.1

protocol/src/main/java/org/opensearch/sql/protocol/response/format/FlatResponseBase.java, protocol/src/test/java/org/opensearch/sql/protocol/response/format/CsvResponseFormatterTest.java, protocol/src/test/java/org/opensearch/sql/protocol/response/format/RawResponseFormatterTest.java
Fixes #3050
- [x ] New functionality includes testing.
- [x ] Commits are signed per the DCO using `--signoff`.
=> Fix: CSV and Raw output, escape quotes

protocol/src/test/java/org/opensearch/sql/protocol/response/format/CsvResponseFormatterTest.java
- Fix spotless check failure for #3148
n/a
=> Fix spotless check failure for #3148

async-query-core/src/main/java/org/opensearch/sql/spark/validator/GrammarElement.java
- Make GrammarElement public to make it usable from other package
n/a
=> Make GrammarElement public

docs/dev/intro-architecture.md, docs/user/general/datatypes.rst, docs/user/general/identifiers.rst
Some typo / broken link fixes on documentation.
N/A
=> Fix: Misc typo and broken link fixes

legacy/src/test/java/org/opensearch/sql/legacy/unittest/query/DefaultQueryActionTest.java, opensearch/src/test/java/org/opensearch/sql/opensearch/client/OpenSearchNodeClientTest.java, opensearch/src/test/java/org/opensearch/sql/opensearch/request/OpenSearchQueryRequestTest.java, opensearch/src/test/java/org/opensearch/sql/opensearch/storage/scan/OpenSearchIndexScanTest.java
Cleanup Only - Remove unused imports
None
- N/A - New functionality includes testing.
- N/A - New functionality has been documented.
- N/A - New functionality has javadoc added.
- N/A - New functionality has a user manual doc added.
- N/A - API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- N/A - Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTR …
=> Cleanup Only - Remove unused imports

MAINTAINERS.md
I recently merged my personal and work github accounts and this resulted in username change multiple times.
=> Incorporated vamsimanohar username change.

.github/workflows/codeql-analysis.yml, .github/workflows/integ-tests-with-security.yml, .github/workflows/link-checker.yml, .github/workflows/maven-publish.yml, .github/workflows/sql-test-and-build-workflow.yml
Backport Github action fix #3177 to 2.x branch.
Resolves #3177
=> [Backport 2.x] Fix: CI Github Action

core/src/main/java/org/opensearch/sql/analysis/Analyzer.java, core/src/main/java/org/opensearch/sql/analysis/ExpressionAnalyzer.java, core/src/main/java/org/opensearch/sql/executor/QueryService.java, integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteNewAddedCommandsIT.java, integ-test/src/test/java/org/opensearch/sql/calcite/standalone/CalcitePPLBasicIT.java, integ-test/src/test/java/org/opensearch/sql/ppl/NewAddedCommandsIT.java, opensearch/src/main/java/org/opensearch/sql/opensearch/executor/OpenSearchExecutionEngine.java
Backport 69b9e82b35a8d2b856ec7c6ae7dd2487a8c16a3a from #3571 manually
=> [Backport 3.0] New added commands should throw exception when calcite disabled (#3571)

integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3635.yml, opensearch/src/main/java/org/opensearch/sql/opensearch/request/AggregateAnalyzer.java, opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java, opensearch/src/main/java/org/opensearch/sql/opensearch/storage/scan/CalciteLogicalIndexScan.java, opensearch/src/test/java/org/opensearch/sql/opensearch/request/AggregateAnalyzerTest.java, opensearch/src/test/java/org/opensearch/sql/opensearch/request/PredicateAnalyzerTest.java
Fix pushing down filter with nested filed of the text type.
Resolves https://github.com/opensearch-project/sql/issues/3635
=> Fix pushing down filter with nested filed of the text type

docs/user/ppl/limitations/limitations.rst
Update [PPL limitations doc](https://github.com/penghuo/os-sql/blob/updateLimitations/docs/user/ppl/limitations/limitations.rst
) to reflect the latest state. 
n/a
=> Update PPL Limitation Docs

.github/get-sonatype-credentials.sh, .github/workflows/maven-publish.yml, .github/workflows/publish-snapshots-and-grammar-files.yml, async-query-core/build.gradle, language-grammar/build.gradle, language-grammar/src/main/antlr4/FlintSparkSqlExtensions.g4, language-grammar/src/main/antlr4/OpenSearchLegacySqlLexer.g4, language-grammar/src/main/antlr4/OpenSearchLegacySqlParser.g4, language-grammar/src/main/antlr4/OpenSearchPPLLexer.g4, language-grammar/src/main/antlr4/OpenSearchPPLParser.g4, language-grammar/src/main/antlr4/OpenSearchSQLLexer.g4, language-grammar/src/main/antlr4/OpenSearchSQLParser.g4, language-grammar/src/main/antlr4/SparkSqlBase.g4, language-grammar/src/main/antlr4/SqlBaseLexer.g4, language-grammar/src/main/antlr4/SqlBaseParser.g4, settings.gradle
Description
Publish to Maven: Grammar Files & Async Query Core
This PR adds a GitHub Actions workflow to automate the publication of artifacts to the Maven snapshot repository for the language-grammar package and the async-query-core module.
Key Features
Grammar File Publishing (language-grammar)
Collects .g4 ANTLR grammar files from the language-grammar module.
Packages them into a .zip artifact with a generated POM.
Publishes the zip artifact to Maven snapshot repo under org.opensearch:language-grammar.
Injects the current Git commit SHA into maven-metadata.xml as for traceability.
Async Query Core Publishing (async-query-core)
Builds a shaded JAR (shadowJar) of the async-query-core module using Gradle.
Prepares and publishes the JAR and generated POM to Maven snapshot repo under …
=> [Backport 2.x] Modified workflow: Grammar Files & Async Query Core

build.gradle
Resolves CVE nits for 3.1 release -- vuln doesn't actually affect us, but you know how CVE tooling is
N/A
=> Resolve commons beanutils to 2.0

release-notes/opensearch-sql.release-notes-3.1.0.0.md
=> Add 3.1.0 release notes

build.gradle, datasources/build.gradle
=> [Backport-main] Remove unneeded dependency on commons-validator

docs/dev/intro-v3-engine.md, docs/user/limitations/limitations.rst, docs/user/ppl/limitations/limitations.rst
=> Update the limitation docs

integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java, integ-test/src/test/resources/expectedOutput/calcite/explain_sarg_filter_push_multi_range.json, integ-test/src/test/resources/expectedOutput/calcite/explain_sarg_filter_push_single_range.json, integ-test/src/test/resources/expectedOutput/calcite/explain_sarg_filter_push_time_range.json, opensearch/src/main/java/org/opensearch/sql/opensearch/request/PredicateAnalyzer.java
=> [Backport 2.19-dev] Support filter push down for Sarg value #3840

docs/user/ppl/index.rst
Update ppl documentation index for new functions. There were several new functionalities added for PPL calcite engine. These are just missing from the main documentation index. 
Relevant PRs: 
JSON functions: https://github.com/opensearch-project/sql/pull/3559
Array/Collection/Multi-value functions : https://github.com/opensearch-project/sql/pull/3584
Cypro functions: https://github.com/opensearch-project/sql/pull/3574
=> Update ppl documentation index for new functions

integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3102.yml, integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3570.yml, integ-test/src/yamlRestTest/resources/rest-api-spec/test/issues/3881.yml
Fix 3 flaky tests in `RestHandlerClientYamlTestSuiteIT`
Resolves #3900 
=> Fix flaky tests in `RestHandlerClientYamlTestSuiteIT`

.github/workflows/enforce-labels.yml
Add 'testing' and 'security fix' to enforce-label-action
=> Add 'testing' and 'security fix' to enforce-label-action

.github/maven-publish-utils.sh, .github/workflows/publish-async-query-core.yml, .github/workflows/publish-grammar-files.yml
Backporting PR https://github.com/opensearch-project/sql/pull/4006 to 2.x
=> [Backport 2.19-dev] fix snapshot uploading (#4006)

docs/user/ppl/cmd/eval.rst
Modified eval.rst file to add an example for String concatenation
=> Add example for String concat in eval.rst

core/src/main/java/org/opensearch/sql/ast/tree/SPath.java, ppl/src/test/java/org/opensearch/sql/ppl/utils/SPathRewriteTest.java
=> Add missing license headers from #4120

.github/maven-publish-utils.sh, .github/workflows/publish-async-query-core.yml, .github/workflows/publish-grammar-files.yml
=> reroute commit-history

.github/get-sonatype-credentials.sh, .github/maven-publish-utils.sh, .github/workflows/publish-async-query-core.yml, .github/workflows/publish-grammar-files.yml
=> Reroute commit-history file

docs/user/ppl/cmd/stats.rst, integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java, integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLAggregationIT.java, integ-test/src/test/resources/expectedOutput/calcite/explain_max_string_field.json, integ-test/src/test/resources/expectedOutput/calcite/explain_min_string_field.json, integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_max_string_field.json, integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_min_string_field.json, opensearch/src/main/java/org/opensearch/sql/opensearch/request/AggregateAnalyzer.java, ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLAggregationTest.java
(cherry picked from commit 7088e0815131b41f3a350587d6568e623fadb276)
fix switch for Java 11
=> [Backport 2.19-dev] Add non-numeric field support for max/min functions (#4281)

DEVELOPER_GUIDE.rst, language-grammar/src/main/antlr4/OpenSearchPPLLexer.g4, language-grammar/src/main/antlr4/OpenSearchPPLParser.g4
Update language-grammar package with latest grammar files and documentation
Summary
- Updated all ANTLR grammar files in the language-grammar package with the latest versions from their respective source modules
- Added documentation to DEVELOPER_GUIDE.rst explaining the purpose and workflow of the language-grammar package
Documentation Updates
Added a new "Language Grammar Package" section to DEVELOPER_GUIDE.rst
Purpose
The language-grammar package serves as a centralized repository for all ANTLR grammar files, enabling consistent sharing between the main SQL repository and Spark repository while reducing duplication. This update ensures the package contains the latest grammar definitions.
Next Steps
Once merged, this will trigger CI to automatically publish the updated grammar files to …
=> Update grammar files and developer guide

docs/user/ppl/reference/splunk_to_ppl_cheat_sheet.md
Update timechart in SPL/PPL cheat sheet
n/a
=> Update timechart in SPL/PPL cheat sheet

docs/category.json, docs/user/dql/metadata.rst, docs/user/ppl/cmd/bin.rst, doctest/test_data/bank.json, doctest/test_data/time_test.json, doctest/test_docs.py
(cherry picked from #4384 commit 877e6d586287171019b4390231accd7f2a887c2a)
=> [Backport 2.19-dev] Update bin.rst and add `bin` to doctest (#4384)

build.gradle, opensearch/src/main/java/org/opensearch/sql/opensearch/data/type/OpenSearchDateType.java
Like #4036 except it actually works (read: includes @LantaoJin's fix)
#4037
=> Version bump: 3.3

docs/user/ppl/cmd/eventstats.rst
Fixed typo: evenstats -->  eventstats
Fixed typo: evenstats -->  eventstats
N/A
- Doc Issue only
- Doc Issue only
- Doc Issue only
- Doc Issue only
- Doc Issue only
=> [DOC] Fix typo: Update eventstats.rst

core/src/main/java/org/opensearch/sql/data/utils/MixedTypeComparator.java, core/src/main/java/org/opensearch/sql/expression/function/PPLBuiltinOperators.java, core/src/main/java/org/opensearch/sql/expression/function/PPLFuncImpTable.java, core/src/main/java/org/opensearch/sql/expression/function/udf/math/MaxFunction.java, core/src/main/java/org/opensearch/sql/expression/function/udf/math/MinFunction.java, core/src/test/java/org/opensearch/sql/data/utils/MixedTypeComparatorTest.java, docs/category.json, docs/user/ppl/functions/statistical.rst, integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalciteExplainIT.java, integ-test/src/test/java/org/opensearch/sql/calcite/remote/CalcitePPLEvalMaxMinFunctionIT.java, integ-test/src/test/resources/expectedOutput/calcite/explain_eval_max.json, integ-test/src/test/resources/expectedOutput/calcite/explain_eval_min.json, integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_eval_max.json, integ-test/src/test/resources/expectedOutput/calcite_no_pushdown/explain_eval_min.json, ppl/src/main/antlr/OpenSearchPPLParser.g4, ppl/src/test/java/org/opensearch/sql/ppl/calcite/CalcitePPLEvalTest.java
(cherry picked from commit fae06873a057f3bcdea1a7a113c74932fc801deb)
=> [Backport 2.19-dev] Add max/min eval functions (#4333)
